"""
MediCore Nexus - Diagnostic Reflex Testing Algorithms
Automates automated secondary lab ordering upon abnormal primary screening values.
"""

from typing import Dict, List, Any

REFLEX_TESTING_ALGORITHMS: Dict[str, Dict[str, Any]] = {
    "RFLX-TSH-V01": {
        "algorithm_id": "RFLX-TSH-V01",
        "test_name": "TSH with Reflex to Free T4 and Free T3 (Tier 1)",
        "laboratory_department": "Endocrinology",
        "reflex_trigger_criteria": "TSH < 0.45 or TSH > 4.50 uIU/mL",
        "automated_order_action": "Free T4 (LOINC 3024-7) and Free T3 (LOINC 3051-0)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 6,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-TSH-V02": {
        "algorithm_id": "RFLX-TSH-V02",
        "test_name": "TSH with Reflex to Free T4 and Free T3 (Tier 2)",
        "laboratory_department": "Endocrinology",
        "reflex_trigger_criteria": "TSH < 0.45 or TSH > 4.50 uIU/mL",
        "automated_order_action": "Free T4 (LOINC 3024-7) and Free T3 (LOINC 3051-0)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 8,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-TSH-V03": {
        "algorithm_id": "RFLX-TSH-V03",
        "test_name": "TSH with Reflex to Free T4 and Free T3 (Tier 3)",
        "laboratory_department": "Endocrinology",
        "reflex_trigger_criteria": "TSH < 0.45 or TSH > 4.50 uIU/mL",
        "automated_order_action": "Free T4 (LOINC 3024-7) and Free T3 (LOINC 3051-0)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 10,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-TSH-V04": {
        "algorithm_id": "RFLX-TSH-V04",
        "test_name": "TSH with Reflex to Free T4 and Free T3 (Tier 4)",
        "laboratory_department": "Endocrinology",
        "reflex_trigger_criteria": "TSH < 0.45 or TSH > 4.50 uIU/mL",
        "automated_order_action": "Free T4 (LOINC 3024-7) and Free T3 (LOINC 3051-0)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 12,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-TSH-V05": {
        "algorithm_id": "RFLX-TSH-V05",
        "test_name": "TSH with Reflex to Free T4 and Free T3 (Tier 5)",
        "laboratory_department": "Endocrinology",
        "reflex_trigger_criteria": "TSH < 0.45 or TSH > 4.50 uIU/mL",
        "automated_order_action": "Free T4 (LOINC 3024-7) and Free T3 (LOINC 3051-0)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 14,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-TSH-V06": {
        "algorithm_id": "RFLX-TSH-V06",
        "test_name": "TSH with Reflex to Free T4 and Free T3 (Tier 6)",
        "laboratory_department": "Endocrinology",
        "reflex_trigger_criteria": "TSH < 0.45 or TSH > 4.50 uIU/mL",
        "automated_order_action": "Free T4 (LOINC 3024-7) and Free T3 (LOINC 3051-0)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 16,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-TSH-V07": {
        "algorithm_id": "RFLX-TSH-V07",
        "test_name": "TSH with Reflex to Free T4 and Free T3 (Tier 7)",
        "laboratory_department": "Endocrinology",
        "reflex_trigger_criteria": "TSH < 0.45 or TSH > 4.50 uIU/mL",
        "automated_order_action": "Free T4 (LOINC 3024-7) and Free T3 (LOINC 3051-0)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 18,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-TSH-V08": {
        "algorithm_id": "RFLX-TSH-V08",
        "test_name": "TSH with Reflex to Free T4 and Free T3 (Tier 8)",
        "laboratory_department": "Endocrinology",
        "reflex_trigger_criteria": "TSH < 0.45 or TSH > 4.50 uIU/mL",
        "automated_order_action": "Free T4 (LOINC 3024-7) and Free T3 (LOINC 3051-0)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 20,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-TSH-V09": {
        "algorithm_id": "RFLX-TSH-V09",
        "test_name": "TSH with Reflex to Free T4 and Free T3 (Tier 9)",
        "laboratory_department": "Endocrinology",
        "reflex_trigger_criteria": "TSH < 0.45 or TSH > 4.50 uIU/mL",
        "automated_order_action": "Free T4 (LOINC 3024-7) and Free T3 (LOINC 3051-0)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 22,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-TSH-V10": {
        "algorithm_id": "RFLX-TSH-V10",
        "test_name": "TSH with Reflex to Free T4 and Free T3 (Tier 10)",
        "laboratory_department": "Endocrinology",
        "reflex_trigger_criteria": "TSH < 0.45 or TSH > 4.50 uIU/mL",
        "automated_order_action": "Free T4 (LOINC 3024-7) and Free T3 (LOINC 3051-0)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 24,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-TSH-V11": {
        "algorithm_id": "RFLX-TSH-V11",
        "test_name": "TSH with Reflex to Free T4 and Free T3 (Tier 11)",
        "laboratory_department": "Endocrinology",
        "reflex_trigger_criteria": "TSH < 0.45 or TSH > 4.50 uIU/mL",
        "automated_order_action": "Free T4 (LOINC 3024-7) and Free T3 (LOINC 3051-0)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 26,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-TSH-V12": {
        "algorithm_id": "RFLX-TSH-V12",
        "test_name": "TSH with Reflex to Free T4 and Free T3 (Tier 12)",
        "laboratory_department": "Endocrinology",
        "reflex_trigger_criteria": "TSH < 0.45 or TSH > 4.50 uIU/mL",
        "automated_order_action": "Free T4 (LOINC 3024-7) and Free T3 (LOINC 3051-0)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 28,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-TSH-V13": {
        "algorithm_id": "RFLX-TSH-V13",
        "test_name": "TSH with Reflex to Free T4 and Free T3 (Tier 13)",
        "laboratory_department": "Endocrinology",
        "reflex_trigger_criteria": "TSH < 0.45 or TSH > 4.50 uIU/mL",
        "automated_order_action": "Free T4 (LOINC 3024-7) and Free T3 (LOINC 3051-0)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 30,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-TSH-V14": {
        "algorithm_id": "RFLX-TSH-V14",
        "test_name": "TSH with Reflex to Free T4 and Free T3 (Tier 14)",
        "laboratory_department": "Endocrinology",
        "reflex_trigger_criteria": "TSH < 0.45 or TSH > 4.50 uIU/mL",
        "automated_order_action": "Free T4 (LOINC 3024-7) and Free T3 (LOINC 3051-0)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 32,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-TSH-V15": {
        "algorithm_id": "RFLX-TSH-V15",
        "test_name": "TSH with Reflex to Free T4 and Free T3 (Tier 15)",
        "laboratory_department": "Endocrinology",
        "reflex_trigger_criteria": "TSH < 0.45 or TSH > 4.50 uIU/mL",
        "automated_order_action": "Free T4 (LOINC 3024-7) and Free T3 (LOINC 3051-0)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 34,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-TSH-V16": {
        "algorithm_id": "RFLX-TSH-V16",
        "test_name": "TSH with Reflex to Free T4 and Free T3 (Tier 16)",
        "laboratory_department": "Endocrinology",
        "reflex_trigger_criteria": "TSH < 0.45 or TSH > 4.50 uIU/mL",
        "automated_order_action": "Free T4 (LOINC 3024-7) and Free T3 (LOINC 3051-0)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 36,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-TSH-V17": {
        "algorithm_id": "RFLX-TSH-V17",
        "test_name": "TSH with Reflex to Free T4 and Free T3 (Tier 17)",
        "laboratory_department": "Endocrinology",
        "reflex_trigger_criteria": "TSH < 0.45 or TSH > 4.50 uIU/mL",
        "automated_order_action": "Free T4 (LOINC 3024-7) and Free T3 (LOINC 3051-0)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 38,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-TSH-V18": {
        "algorithm_id": "RFLX-TSH-V18",
        "test_name": "TSH with Reflex to Free T4 and Free T3 (Tier 18)",
        "laboratory_department": "Endocrinology",
        "reflex_trigger_criteria": "TSH < 0.45 or TSH > 4.50 uIU/mL",
        "automated_order_action": "Free T4 (LOINC 3024-7) and Free T3 (LOINC 3051-0)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 40,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-TSH-V19": {
        "algorithm_id": "RFLX-TSH-V19",
        "test_name": "TSH with Reflex to Free T4 and Free T3 (Tier 19)",
        "laboratory_department": "Endocrinology",
        "reflex_trigger_criteria": "TSH < 0.45 or TSH > 4.50 uIU/mL",
        "automated_order_action": "Free T4 (LOINC 3024-7) and Free T3 (LOINC 3051-0)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 42,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-URINE-V01": {
        "algorithm_id": "RFLX-URINE-V01",
        "test_name": "Urinalysis with Reflex to Microscopic and Culture (Tier 1)",
        "laboratory_department": "Microbiology",
        "reflex_trigger_criteria": "Leukocyte Esterase positive OR Nitrites positive OR WBC > 5/HPF",
        "automated_order_action": "Urine Culture and Antimicrobial Susceptibility (LOINC 630-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 6,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-URINE-V02": {
        "algorithm_id": "RFLX-URINE-V02",
        "test_name": "Urinalysis with Reflex to Microscopic and Culture (Tier 2)",
        "laboratory_department": "Microbiology",
        "reflex_trigger_criteria": "Leukocyte Esterase positive OR Nitrites positive OR WBC > 5/HPF",
        "automated_order_action": "Urine Culture and Antimicrobial Susceptibility (LOINC 630-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 8,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-URINE-V03": {
        "algorithm_id": "RFLX-URINE-V03",
        "test_name": "Urinalysis with Reflex to Microscopic and Culture (Tier 3)",
        "laboratory_department": "Microbiology",
        "reflex_trigger_criteria": "Leukocyte Esterase positive OR Nitrites positive OR WBC > 5/HPF",
        "automated_order_action": "Urine Culture and Antimicrobial Susceptibility (LOINC 630-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 10,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-URINE-V04": {
        "algorithm_id": "RFLX-URINE-V04",
        "test_name": "Urinalysis with Reflex to Microscopic and Culture (Tier 4)",
        "laboratory_department": "Microbiology",
        "reflex_trigger_criteria": "Leukocyte Esterase positive OR Nitrites positive OR WBC > 5/HPF",
        "automated_order_action": "Urine Culture and Antimicrobial Susceptibility (LOINC 630-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 12,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-URINE-V05": {
        "algorithm_id": "RFLX-URINE-V05",
        "test_name": "Urinalysis with Reflex to Microscopic and Culture (Tier 5)",
        "laboratory_department": "Microbiology",
        "reflex_trigger_criteria": "Leukocyte Esterase positive OR Nitrites positive OR WBC > 5/HPF",
        "automated_order_action": "Urine Culture and Antimicrobial Susceptibility (LOINC 630-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 14,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-URINE-V06": {
        "algorithm_id": "RFLX-URINE-V06",
        "test_name": "Urinalysis with Reflex to Microscopic and Culture (Tier 6)",
        "laboratory_department": "Microbiology",
        "reflex_trigger_criteria": "Leukocyte Esterase positive OR Nitrites positive OR WBC > 5/HPF",
        "automated_order_action": "Urine Culture and Antimicrobial Susceptibility (LOINC 630-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 16,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-URINE-V07": {
        "algorithm_id": "RFLX-URINE-V07",
        "test_name": "Urinalysis with Reflex to Microscopic and Culture (Tier 7)",
        "laboratory_department": "Microbiology",
        "reflex_trigger_criteria": "Leukocyte Esterase positive OR Nitrites positive OR WBC > 5/HPF",
        "automated_order_action": "Urine Culture and Antimicrobial Susceptibility (LOINC 630-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 18,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-URINE-V08": {
        "algorithm_id": "RFLX-URINE-V08",
        "test_name": "Urinalysis with Reflex to Microscopic and Culture (Tier 8)",
        "laboratory_department": "Microbiology",
        "reflex_trigger_criteria": "Leukocyte Esterase positive OR Nitrites positive OR WBC > 5/HPF",
        "automated_order_action": "Urine Culture and Antimicrobial Susceptibility (LOINC 630-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 20,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-URINE-V09": {
        "algorithm_id": "RFLX-URINE-V09",
        "test_name": "Urinalysis with Reflex to Microscopic and Culture (Tier 9)",
        "laboratory_department": "Microbiology",
        "reflex_trigger_criteria": "Leukocyte Esterase positive OR Nitrites positive OR WBC > 5/HPF",
        "automated_order_action": "Urine Culture and Antimicrobial Susceptibility (LOINC 630-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 22,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-URINE-V10": {
        "algorithm_id": "RFLX-URINE-V10",
        "test_name": "Urinalysis with Reflex to Microscopic and Culture (Tier 10)",
        "laboratory_department": "Microbiology",
        "reflex_trigger_criteria": "Leukocyte Esterase positive OR Nitrites positive OR WBC > 5/HPF",
        "automated_order_action": "Urine Culture and Antimicrobial Susceptibility (LOINC 630-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 24,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-URINE-V11": {
        "algorithm_id": "RFLX-URINE-V11",
        "test_name": "Urinalysis with Reflex to Microscopic and Culture (Tier 11)",
        "laboratory_department": "Microbiology",
        "reflex_trigger_criteria": "Leukocyte Esterase positive OR Nitrites positive OR WBC > 5/HPF",
        "automated_order_action": "Urine Culture and Antimicrobial Susceptibility (LOINC 630-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 26,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-URINE-V12": {
        "algorithm_id": "RFLX-URINE-V12",
        "test_name": "Urinalysis with Reflex to Microscopic and Culture (Tier 12)",
        "laboratory_department": "Microbiology",
        "reflex_trigger_criteria": "Leukocyte Esterase positive OR Nitrites positive OR WBC > 5/HPF",
        "automated_order_action": "Urine Culture and Antimicrobial Susceptibility (LOINC 630-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 28,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-URINE-V13": {
        "algorithm_id": "RFLX-URINE-V13",
        "test_name": "Urinalysis with Reflex to Microscopic and Culture (Tier 13)",
        "laboratory_department": "Microbiology",
        "reflex_trigger_criteria": "Leukocyte Esterase positive OR Nitrites positive OR WBC > 5/HPF",
        "automated_order_action": "Urine Culture and Antimicrobial Susceptibility (LOINC 630-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 30,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-URINE-V14": {
        "algorithm_id": "RFLX-URINE-V14",
        "test_name": "Urinalysis with Reflex to Microscopic and Culture (Tier 14)",
        "laboratory_department": "Microbiology",
        "reflex_trigger_criteria": "Leukocyte Esterase positive OR Nitrites positive OR WBC > 5/HPF",
        "automated_order_action": "Urine Culture and Antimicrobial Susceptibility (LOINC 630-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 32,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-URINE-V15": {
        "algorithm_id": "RFLX-URINE-V15",
        "test_name": "Urinalysis with Reflex to Microscopic and Culture (Tier 15)",
        "laboratory_department": "Microbiology",
        "reflex_trigger_criteria": "Leukocyte Esterase positive OR Nitrites positive OR WBC > 5/HPF",
        "automated_order_action": "Urine Culture and Antimicrobial Susceptibility (LOINC 630-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 34,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-URINE-V16": {
        "algorithm_id": "RFLX-URINE-V16",
        "test_name": "Urinalysis with Reflex to Microscopic and Culture (Tier 16)",
        "laboratory_department": "Microbiology",
        "reflex_trigger_criteria": "Leukocyte Esterase positive OR Nitrites positive OR WBC > 5/HPF",
        "automated_order_action": "Urine Culture and Antimicrobial Susceptibility (LOINC 630-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 36,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-URINE-V17": {
        "algorithm_id": "RFLX-URINE-V17",
        "test_name": "Urinalysis with Reflex to Microscopic and Culture (Tier 17)",
        "laboratory_department": "Microbiology",
        "reflex_trigger_criteria": "Leukocyte Esterase positive OR Nitrites positive OR WBC > 5/HPF",
        "automated_order_action": "Urine Culture and Antimicrobial Susceptibility (LOINC 630-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 38,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-URINE-V18": {
        "algorithm_id": "RFLX-URINE-V18",
        "test_name": "Urinalysis with Reflex to Microscopic and Culture (Tier 18)",
        "laboratory_department": "Microbiology",
        "reflex_trigger_criteria": "Leukocyte Esterase positive OR Nitrites positive OR WBC > 5/HPF",
        "automated_order_action": "Urine Culture and Antimicrobial Susceptibility (LOINC 630-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 40,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-URINE-V19": {
        "algorithm_id": "RFLX-URINE-V19",
        "test_name": "Urinalysis with Reflex to Microscopic and Culture (Tier 19)",
        "laboratory_department": "Microbiology",
        "reflex_trigger_criteria": "Leukocyte Esterase positive OR Nitrites positive OR WBC > 5/HPF",
        "automated_order_action": "Urine Culture and Antimicrobial Susceptibility (LOINC 630-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 42,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-ANA-V01": {
        "algorithm_id": "RFLX-ANA-V01",
        "test_name": "Antinuclear Antibodies (ANA) Reflex Cascade (Tier 1)",
        "laboratory_department": "Immunology",
        "reflex_trigger_criteria": "ANA Screen Titer >= 1:80 (Homogeneous or Speckled)",
        "automated_order_action": "ENA Panel (Sm, RNP, SSA/Ro, SSB/La, Scl-70, Jo-1, dsDNA)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 6,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-ANA-V02": {
        "algorithm_id": "RFLX-ANA-V02",
        "test_name": "Antinuclear Antibodies (ANA) Reflex Cascade (Tier 2)",
        "laboratory_department": "Immunology",
        "reflex_trigger_criteria": "ANA Screen Titer >= 1:80 (Homogeneous or Speckled)",
        "automated_order_action": "ENA Panel (Sm, RNP, SSA/Ro, SSB/La, Scl-70, Jo-1, dsDNA)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 8,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-ANA-V03": {
        "algorithm_id": "RFLX-ANA-V03",
        "test_name": "Antinuclear Antibodies (ANA) Reflex Cascade (Tier 3)",
        "laboratory_department": "Immunology",
        "reflex_trigger_criteria": "ANA Screen Titer >= 1:80 (Homogeneous or Speckled)",
        "automated_order_action": "ENA Panel (Sm, RNP, SSA/Ro, SSB/La, Scl-70, Jo-1, dsDNA)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 10,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-ANA-V04": {
        "algorithm_id": "RFLX-ANA-V04",
        "test_name": "Antinuclear Antibodies (ANA) Reflex Cascade (Tier 4)",
        "laboratory_department": "Immunology",
        "reflex_trigger_criteria": "ANA Screen Titer >= 1:80 (Homogeneous or Speckled)",
        "automated_order_action": "ENA Panel (Sm, RNP, SSA/Ro, SSB/La, Scl-70, Jo-1, dsDNA)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 12,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-ANA-V05": {
        "algorithm_id": "RFLX-ANA-V05",
        "test_name": "Antinuclear Antibodies (ANA) Reflex Cascade (Tier 5)",
        "laboratory_department": "Immunology",
        "reflex_trigger_criteria": "ANA Screen Titer >= 1:80 (Homogeneous or Speckled)",
        "automated_order_action": "ENA Panel (Sm, RNP, SSA/Ro, SSB/La, Scl-70, Jo-1, dsDNA)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 14,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-ANA-V06": {
        "algorithm_id": "RFLX-ANA-V06",
        "test_name": "Antinuclear Antibodies (ANA) Reflex Cascade (Tier 6)",
        "laboratory_department": "Immunology",
        "reflex_trigger_criteria": "ANA Screen Titer >= 1:80 (Homogeneous or Speckled)",
        "automated_order_action": "ENA Panel (Sm, RNP, SSA/Ro, SSB/La, Scl-70, Jo-1, dsDNA)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 16,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-ANA-V07": {
        "algorithm_id": "RFLX-ANA-V07",
        "test_name": "Antinuclear Antibodies (ANA) Reflex Cascade (Tier 7)",
        "laboratory_department": "Immunology",
        "reflex_trigger_criteria": "ANA Screen Titer >= 1:80 (Homogeneous or Speckled)",
        "automated_order_action": "ENA Panel (Sm, RNP, SSA/Ro, SSB/La, Scl-70, Jo-1, dsDNA)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 18,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-ANA-V08": {
        "algorithm_id": "RFLX-ANA-V08",
        "test_name": "Antinuclear Antibodies (ANA) Reflex Cascade (Tier 8)",
        "laboratory_department": "Immunology",
        "reflex_trigger_criteria": "ANA Screen Titer >= 1:80 (Homogeneous or Speckled)",
        "automated_order_action": "ENA Panel (Sm, RNP, SSA/Ro, SSB/La, Scl-70, Jo-1, dsDNA)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 20,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-ANA-V09": {
        "algorithm_id": "RFLX-ANA-V09",
        "test_name": "Antinuclear Antibodies (ANA) Reflex Cascade (Tier 9)",
        "laboratory_department": "Immunology",
        "reflex_trigger_criteria": "ANA Screen Titer >= 1:80 (Homogeneous or Speckled)",
        "automated_order_action": "ENA Panel (Sm, RNP, SSA/Ro, SSB/La, Scl-70, Jo-1, dsDNA)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 22,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-ANA-V10": {
        "algorithm_id": "RFLX-ANA-V10",
        "test_name": "Antinuclear Antibodies (ANA) Reflex Cascade (Tier 10)",
        "laboratory_department": "Immunology",
        "reflex_trigger_criteria": "ANA Screen Titer >= 1:80 (Homogeneous or Speckled)",
        "automated_order_action": "ENA Panel (Sm, RNP, SSA/Ro, SSB/La, Scl-70, Jo-1, dsDNA)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 24,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-ANA-V11": {
        "algorithm_id": "RFLX-ANA-V11",
        "test_name": "Antinuclear Antibodies (ANA) Reflex Cascade (Tier 11)",
        "laboratory_department": "Immunology",
        "reflex_trigger_criteria": "ANA Screen Titer >= 1:80 (Homogeneous or Speckled)",
        "automated_order_action": "ENA Panel (Sm, RNP, SSA/Ro, SSB/La, Scl-70, Jo-1, dsDNA)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 26,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-ANA-V12": {
        "algorithm_id": "RFLX-ANA-V12",
        "test_name": "Antinuclear Antibodies (ANA) Reflex Cascade (Tier 12)",
        "laboratory_department": "Immunology",
        "reflex_trigger_criteria": "ANA Screen Titer >= 1:80 (Homogeneous or Speckled)",
        "automated_order_action": "ENA Panel (Sm, RNP, SSA/Ro, SSB/La, Scl-70, Jo-1, dsDNA)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 28,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-ANA-V13": {
        "algorithm_id": "RFLX-ANA-V13",
        "test_name": "Antinuclear Antibodies (ANA) Reflex Cascade (Tier 13)",
        "laboratory_department": "Immunology",
        "reflex_trigger_criteria": "ANA Screen Titer >= 1:80 (Homogeneous or Speckled)",
        "automated_order_action": "ENA Panel (Sm, RNP, SSA/Ro, SSB/La, Scl-70, Jo-1, dsDNA)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 30,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-ANA-V14": {
        "algorithm_id": "RFLX-ANA-V14",
        "test_name": "Antinuclear Antibodies (ANA) Reflex Cascade (Tier 14)",
        "laboratory_department": "Immunology",
        "reflex_trigger_criteria": "ANA Screen Titer >= 1:80 (Homogeneous or Speckled)",
        "automated_order_action": "ENA Panel (Sm, RNP, SSA/Ro, SSB/La, Scl-70, Jo-1, dsDNA)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 32,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-ANA-V15": {
        "algorithm_id": "RFLX-ANA-V15",
        "test_name": "Antinuclear Antibodies (ANA) Reflex Cascade (Tier 15)",
        "laboratory_department": "Immunology",
        "reflex_trigger_criteria": "ANA Screen Titer >= 1:80 (Homogeneous or Speckled)",
        "automated_order_action": "ENA Panel (Sm, RNP, SSA/Ro, SSB/La, Scl-70, Jo-1, dsDNA)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 34,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-ANA-V16": {
        "algorithm_id": "RFLX-ANA-V16",
        "test_name": "Antinuclear Antibodies (ANA) Reflex Cascade (Tier 16)",
        "laboratory_department": "Immunology",
        "reflex_trigger_criteria": "ANA Screen Titer >= 1:80 (Homogeneous or Speckled)",
        "automated_order_action": "ENA Panel (Sm, RNP, SSA/Ro, SSB/La, Scl-70, Jo-1, dsDNA)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 36,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-ANA-V17": {
        "algorithm_id": "RFLX-ANA-V17",
        "test_name": "Antinuclear Antibodies (ANA) Reflex Cascade (Tier 17)",
        "laboratory_department": "Immunology",
        "reflex_trigger_criteria": "ANA Screen Titer >= 1:80 (Homogeneous or Speckled)",
        "automated_order_action": "ENA Panel (Sm, RNP, SSA/Ro, SSB/La, Scl-70, Jo-1, dsDNA)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 38,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-ANA-V18": {
        "algorithm_id": "RFLX-ANA-V18",
        "test_name": "Antinuclear Antibodies (ANA) Reflex Cascade (Tier 18)",
        "laboratory_department": "Immunology",
        "reflex_trigger_criteria": "ANA Screen Titer >= 1:80 (Homogeneous or Speckled)",
        "automated_order_action": "ENA Panel (Sm, RNP, SSA/Ro, SSB/La, Scl-70, Jo-1, dsDNA)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 40,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-ANA-V19": {
        "algorithm_id": "RFLX-ANA-V19",
        "test_name": "Antinuclear Antibodies (ANA) Reflex Cascade (Tier 19)",
        "laboratory_department": "Immunology",
        "reflex_trigger_criteria": "ANA Screen Titer >= 1:80 (Homogeneous or Speckled)",
        "automated_order_action": "ENA Panel (Sm, RNP, SSA/Ro, SSB/La, Scl-70, Jo-1, dsDNA)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 42,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-HEPC-V01": {
        "algorithm_id": "RFLX-HEPC-V01",
        "test_name": "Hepatitis C Antibody with Reflex to HCV RNA PCR (Tier 1)",
        "laboratory_department": "Virology",
        "reflex_trigger_criteria": "HCV Antibody Signal-to-Cutoff >= 1.0 (Reactive)",
        "automated_order_action": "HCV Quantitative Real-Time PCR Viral Load (LOINC 11011-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 6,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-HEPC-V02": {
        "algorithm_id": "RFLX-HEPC-V02",
        "test_name": "Hepatitis C Antibody with Reflex to HCV RNA PCR (Tier 2)",
        "laboratory_department": "Virology",
        "reflex_trigger_criteria": "HCV Antibody Signal-to-Cutoff >= 1.0 (Reactive)",
        "automated_order_action": "HCV Quantitative Real-Time PCR Viral Load (LOINC 11011-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 8,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-HEPC-V03": {
        "algorithm_id": "RFLX-HEPC-V03",
        "test_name": "Hepatitis C Antibody with Reflex to HCV RNA PCR (Tier 3)",
        "laboratory_department": "Virology",
        "reflex_trigger_criteria": "HCV Antibody Signal-to-Cutoff >= 1.0 (Reactive)",
        "automated_order_action": "HCV Quantitative Real-Time PCR Viral Load (LOINC 11011-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 10,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-HEPC-V04": {
        "algorithm_id": "RFLX-HEPC-V04",
        "test_name": "Hepatitis C Antibody with Reflex to HCV RNA PCR (Tier 4)",
        "laboratory_department": "Virology",
        "reflex_trigger_criteria": "HCV Antibody Signal-to-Cutoff >= 1.0 (Reactive)",
        "automated_order_action": "HCV Quantitative Real-Time PCR Viral Load (LOINC 11011-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 12,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-HEPC-V05": {
        "algorithm_id": "RFLX-HEPC-V05",
        "test_name": "Hepatitis C Antibody with Reflex to HCV RNA PCR (Tier 5)",
        "laboratory_department": "Virology",
        "reflex_trigger_criteria": "HCV Antibody Signal-to-Cutoff >= 1.0 (Reactive)",
        "automated_order_action": "HCV Quantitative Real-Time PCR Viral Load (LOINC 11011-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 14,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-HEPC-V06": {
        "algorithm_id": "RFLX-HEPC-V06",
        "test_name": "Hepatitis C Antibody with Reflex to HCV RNA PCR (Tier 6)",
        "laboratory_department": "Virology",
        "reflex_trigger_criteria": "HCV Antibody Signal-to-Cutoff >= 1.0 (Reactive)",
        "automated_order_action": "HCV Quantitative Real-Time PCR Viral Load (LOINC 11011-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 16,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-HEPC-V07": {
        "algorithm_id": "RFLX-HEPC-V07",
        "test_name": "Hepatitis C Antibody with Reflex to HCV RNA PCR (Tier 7)",
        "laboratory_department": "Virology",
        "reflex_trigger_criteria": "HCV Antibody Signal-to-Cutoff >= 1.0 (Reactive)",
        "automated_order_action": "HCV Quantitative Real-Time PCR Viral Load (LOINC 11011-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 18,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-HEPC-V08": {
        "algorithm_id": "RFLX-HEPC-V08",
        "test_name": "Hepatitis C Antibody with Reflex to HCV RNA PCR (Tier 8)",
        "laboratory_department": "Virology",
        "reflex_trigger_criteria": "HCV Antibody Signal-to-Cutoff >= 1.0 (Reactive)",
        "automated_order_action": "HCV Quantitative Real-Time PCR Viral Load (LOINC 11011-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 20,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-HEPC-V09": {
        "algorithm_id": "RFLX-HEPC-V09",
        "test_name": "Hepatitis C Antibody with Reflex to HCV RNA PCR (Tier 9)",
        "laboratory_department": "Virology",
        "reflex_trigger_criteria": "HCV Antibody Signal-to-Cutoff >= 1.0 (Reactive)",
        "automated_order_action": "HCV Quantitative Real-Time PCR Viral Load (LOINC 11011-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 22,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-HEPC-V10": {
        "algorithm_id": "RFLX-HEPC-V10",
        "test_name": "Hepatitis C Antibody with Reflex to HCV RNA PCR (Tier 10)",
        "laboratory_department": "Virology",
        "reflex_trigger_criteria": "HCV Antibody Signal-to-Cutoff >= 1.0 (Reactive)",
        "automated_order_action": "HCV Quantitative Real-Time PCR Viral Load (LOINC 11011-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 24,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-HEPC-V11": {
        "algorithm_id": "RFLX-HEPC-V11",
        "test_name": "Hepatitis C Antibody with Reflex to HCV RNA PCR (Tier 11)",
        "laboratory_department": "Virology",
        "reflex_trigger_criteria": "HCV Antibody Signal-to-Cutoff >= 1.0 (Reactive)",
        "automated_order_action": "HCV Quantitative Real-Time PCR Viral Load (LOINC 11011-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 26,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-HEPC-V12": {
        "algorithm_id": "RFLX-HEPC-V12",
        "test_name": "Hepatitis C Antibody with Reflex to HCV RNA PCR (Tier 12)",
        "laboratory_department": "Virology",
        "reflex_trigger_criteria": "HCV Antibody Signal-to-Cutoff >= 1.0 (Reactive)",
        "automated_order_action": "HCV Quantitative Real-Time PCR Viral Load (LOINC 11011-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 28,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-HEPC-V13": {
        "algorithm_id": "RFLX-HEPC-V13",
        "test_name": "Hepatitis C Antibody with Reflex to HCV RNA PCR (Tier 13)",
        "laboratory_department": "Virology",
        "reflex_trigger_criteria": "HCV Antibody Signal-to-Cutoff >= 1.0 (Reactive)",
        "automated_order_action": "HCV Quantitative Real-Time PCR Viral Load (LOINC 11011-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 30,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-HEPC-V14": {
        "algorithm_id": "RFLX-HEPC-V14",
        "test_name": "Hepatitis C Antibody with Reflex to HCV RNA PCR (Tier 14)",
        "laboratory_department": "Virology",
        "reflex_trigger_criteria": "HCV Antibody Signal-to-Cutoff >= 1.0 (Reactive)",
        "automated_order_action": "HCV Quantitative Real-Time PCR Viral Load (LOINC 11011-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 32,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-HEPC-V15": {
        "algorithm_id": "RFLX-HEPC-V15",
        "test_name": "Hepatitis C Antibody with Reflex to HCV RNA PCR (Tier 15)",
        "laboratory_department": "Virology",
        "reflex_trigger_criteria": "HCV Antibody Signal-to-Cutoff >= 1.0 (Reactive)",
        "automated_order_action": "HCV Quantitative Real-Time PCR Viral Load (LOINC 11011-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 34,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-HEPC-V16": {
        "algorithm_id": "RFLX-HEPC-V16",
        "test_name": "Hepatitis C Antibody with Reflex to HCV RNA PCR (Tier 16)",
        "laboratory_department": "Virology",
        "reflex_trigger_criteria": "HCV Antibody Signal-to-Cutoff >= 1.0 (Reactive)",
        "automated_order_action": "HCV Quantitative Real-Time PCR Viral Load (LOINC 11011-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 36,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-HEPC-V17": {
        "algorithm_id": "RFLX-HEPC-V17",
        "test_name": "Hepatitis C Antibody with Reflex to HCV RNA PCR (Tier 17)",
        "laboratory_department": "Virology",
        "reflex_trigger_criteria": "HCV Antibody Signal-to-Cutoff >= 1.0 (Reactive)",
        "automated_order_action": "HCV Quantitative Real-Time PCR Viral Load (LOINC 11011-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 38,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-HEPC-V18": {
        "algorithm_id": "RFLX-HEPC-V18",
        "test_name": "Hepatitis C Antibody with Reflex to HCV RNA PCR (Tier 18)",
        "laboratory_department": "Virology",
        "reflex_trigger_criteria": "HCV Antibody Signal-to-Cutoff >= 1.0 (Reactive)",
        "automated_order_action": "HCV Quantitative Real-Time PCR Viral Load (LOINC 11011-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 40,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-HEPC-V19": {
        "algorithm_id": "RFLX-HEPC-V19",
        "test_name": "Hepatitis C Antibody with Reflex to HCV RNA PCR (Tier 19)",
        "laboratory_department": "Virology",
        "reflex_trigger_criteria": "HCV Antibody Signal-to-Cutoff >= 1.0 (Reactive)",
        "automated_order_action": "HCV Quantitative Real-Time PCR Viral Load (LOINC 11011-4)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 42,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-LIPID-V01": {
        "algorithm_id": "RFLX-LIPID-V01",
        "test_name": "Lipid Panel with Reflex to Direct LDL and Apolipoprotein B (Tier 1)",
        "laboratory_department": "Cardiovascular",
        "reflex_trigger_criteria": "Triglycerides > 400 mg/dL (Friedewald calculation invalid)",
        "automated_order_action": "Direct LDL-C Measurement (LOINC 18262-6)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 6,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-LIPID-V02": {
        "algorithm_id": "RFLX-LIPID-V02",
        "test_name": "Lipid Panel with Reflex to Direct LDL and Apolipoprotein B (Tier 2)",
        "laboratory_department": "Cardiovascular",
        "reflex_trigger_criteria": "Triglycerides > 400 mg/dL (Friedewald calculation invalid)",
        "automated_order_action": "Direct LDL-C Measurement (LOINC 18262-6)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 8,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-LIPID-V03": {
        "algorithm_id": "RFLX-LIPID-V03",
        "test_name": "Lipid Panel with Reflex to Direct LDL and Apolipoprotein B (Tier 3)",
        "laboratory_department": "Cardiovascular",
        "reflex_trigger_criteria": "Triglycerides > 400 mg/dL (Friedewald calculation invalid)",
        "automated_order_action": "Direct LDL-C Measurement (LOINC 18262-6)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 10,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-LIPID-V04": {
        "algorithm_id": "RFLX-LIPID-V04",
        "test_name": "Lipid Panel with Reflex to Direct LDL and Apolipoprotein B (Tier 4)",
        "laboratory_department": "Cardiovascular",
        "reflex_trigger_criteria": "Triglycerides > 400 mg/dL (Friedewald calculation invalid)",
        "automated_order_action": "Direct LDL-C Measurement (LOINC 18262-6)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 12,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-LIPID-V05": {
        "algorithm_id": "RFLX-LIPID-V05",
        "test_name": "Lipid Panel with Reflex to Direct LDL and Apolipoprotein B (Tier 5)",
        "laboratory_department": "Cardiovascular",
        "reflex_trigger_criteria": "Triglycerides > 400 mg/dL (Friedewald calculation invalid)",
        "automated_order_action": "Direct LDL-C Measurement (LOINC 18262-6)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 14,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-LIPID-V06": {
        "algorithm_id": "RFLX-LIPID-V06",
        "test_name": "Lipid Panel with Reflex to Direct LDL and Apolipoprotein B (Tier 6)",
        "laboratory_department": "Cardiovascular",
        "reflex_trigger_criteria": "Triglycerides > 400 mg/dL (Friedewald calculation invalid)",
        "automated_order_action": "Direct LDL-C Measurement (LOINC 18262-6)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 16,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-LIPID-V07": {
        "algorithm_id": "RFLX-LIPID-V07",
        "test_name": "Lipid Panel with Reflex to Direct LDL and Apolipoprotein B (Tier 7)",
        "laboratory_department": "Cardiovascular",
        "reflex_trigger_criteria": "Triglycerides > 400 mg/dL (Friedewald calculation invalid)",
        "automated_order_action": "Direct LDL-C Measurement (LOINC 18262-6)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 18,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-LIPID-V08": {
        "algorithm_id": "RFLX-LIPID-V08",
        "test_name": "Lipid Panel with Reflex to Direct LDL and Apolipoprotein B (Tier 8)",
        "laboratory_department": "Cardiovascular",
        "reflex_trigger_criteria": "Triglycerides > 400 mg/dL (Friedewald calculation invalid)",
        "automated_order_action": "Direct LDL-C Measurement (LOINC 18262-6)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 20,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-LIPID-V09": {
        "algorithm_id": "RFLX-LIPID-V09",
        "test_name": "Lipid Panel with Reflex to Direct LDL and Apolipoprotein B (Tier 9)",
        "laboratory_department": "Cardiovascular",
        "reflex_trigger_criteria": "Triglycerides > 400 mg/dL (Friedewald calculation invalid)",
        "automated_order_action": "Direct LDL-C Measurement (LOINC 18262-6)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 22,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-LIPID-V10": {
        "algorithm_id": "RFLX-LIPID-V10",
        "test_name": "Lipid Panel with Reflex to Direct LDL and Apolipoprotein B (Tier 10)",
        "laboratory_department": "Cardiovascular",
        "reflex_trigger_criteria": "Triglycerides > 400 mg/dL (Friedewald calculation invalid)",
        "automated_order_action": "Direct LDL-C Measurement (LOINC 18262-6)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 24,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-LIPID-V11": {
        "algorithm_id": "RFLX-LIPID-V11",
        "test_name": "Lipid Panel with Reflex to Direct LDL and Apolipoprotein B (Tier 11)",
        "laboratory_department": "Cardiovascular",
        "reflex_trigger_criteria": "Triglycerides > 400 mg/dL (Friedewald calculation invalid)",
        "automated_order_action": "Direct LDL-C Measurement (LOINC 18262-6)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 26,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-LIPID-V12": {
        "algorithm_id": "RFLX-LIPID-V12",
        "test_name": "Lipid Panel with Reflex to Direct LDL and Apolipoprotein B (Tier 12)",
        "laboratory_department": "Cardiovascular",
        "reflex_trigger_criteria": "Triglycerides > 400 mg/dL (Friedewald calculation invalid)",
        "automated_order_action": "Direct LDL-C Measurement (LOINC 18262-6)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 28,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-LIPID-V13": {
        "algorithm_id": "RFLX-LIPID-V13",
        "test_name": "Lipid Panel with Reflex to Direct LDL and Apolipoprotein B (Tier 13)",
        "laboratory_department": "Cardiovascular",
        "reflex_trigger_criteria": "Triglycerides > 400 mg/dL (Friedewald calculation invalid)",
        "automated_order_action": "Direct LDL-C Measurement (LOINC 18262-6)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 30,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-LIPID-V14": {
        "algorithm_id": "RFLX-LIPID-V14",
        "test_name": "Lipid Panel with Reflex to Direct LDL and Apolipoprotein B (Tier 14)",
        "laboratory_department": "Cardiovascular",
        "reflex_trigger_criteria": "Triglycerides > 400 mg/dL (Friedewald calculation invalid)",
        "automated_order_action": "Direct LDL-C Measurement (LOINC 18262-6)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 32,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-LIPID-V15": {
        "algorithm_id": "RFLX-LIPID-V15",
        "test_name": "Lipid Panel with Reflex to Direct LDL and Apolipoprotein B (Tier 15)",
        "laboratory_department": "Cardiovascular",
        "reflex_trigger_criteria": "Triglycerides > 400 mg/dL (Friedewald calculation invalid)",
        "automated_order_action": "Direct LDL-C Measurement (LOINC 18262-6)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 34,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-LIPID-V16": {
        "algorithm_id": "RFLX-LIPID-V16",
        "test_name": "Lipid Panel with Reflex to Direct LDL and Apolipoprotein B (Tier 16)",
        "laboratory_department": "Cardiovascular",
        "reflex_trigger_criteria": "Triglycerides > 400 mg/dL (Friedewald calculation invalid)",
        "automated_order_action": "Direct LDL-C Measurement (LOINC 18262-6)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 36,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-LIPID-V17": {
        "algorithm_id": "RFLX-LIPID-V17",
        "test_name": "Lipid Panel with Reflex to Direct LDL and Apolipoprotein B (Tier 17)",
        "laboratory_department": "Cardiovascular",
        "reflex_trigger_criteria": "Triglycerides > 400 mg/dL (Friedewald calculation invalid)",
        "automated_order_action": "Direct LDL-C Measurement (LOINC 18262-6)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 38,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-LIPID-V18": {
        "algorithm_id": "RFLX-LIPID-V18",
        "test_name": "Lipid Panel with Reflex to Direct LDL and Apolipoprotein B (Tier 18)",
        "laboratory_department": "Cardiovascular",
        "reflex_trigger_criteria": "Triglycerides > 400 mg/dL (Friedewald calculation invalid)",
        "automated_order_action": "Direct LDL-C Measurement (LOINC 18262-6)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 40,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-LIPID-V19": {
        "algorithm_id": "RFLX-LIPID-V19",
        "test_name": "Lipid Panel with Reflex to Direct LDL and Apolipoprotein B (Tier 19)",
        "laboratory_department": "Cardiovascular",
        "reflex_trigger_criteria": "Triglycerides > 400 mg/dL (Friedewald calculation invalid)",
        "automated_order_action": "Direct LDL-C Measurement (LOINC 18262-6)",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 42,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-CELIAC-V01": {
        "algorithm_id": "RFLX-CELIAC-V01",
        "test_name": "Celiac Disease Cascade with Reflex to tTG-IgG (Tier 1)",
        "laboratory_department": "Gastroenterology",
        "reflex_trigger_criteria": "Total Serum IgA < 20 mg/dL (IgA deficiency)",
        "automated_order_action": "Tissue Transglutaminase IgG and Deamidated Gliadin IgG",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 6,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-CELIAC-V02": {
        "algorithm_id": "RFLX-CELIAC-V02",
        "test_name": "Celiac Disease Cascade with Reflex to tTG-IgG (Tier 2)",
        "laboratory_department": "Gastroenterology",
        "reflex_trigger_criteria": "Total Serum IgA < 20 mg/dL (IgA deficiency)",
        "automated_order_action": "Tissue Transglutaminase IgG and Deamidated Gliadin IgG",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 8,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-CELIAC-V03": {
        "algorithm_id": "RFLX-CELIAC-V03",
        "test_name": "Celiac Disease Cascade with Reflex to tTG-IgG (Tier 3)",
        "laboratory_department": "Gastroenterology",
        "reflex_trigger_criteria": "Total Serum IgA < 20 mg/dL (IgA deficiency)",
        "automated_order_action": "Tissue Transglutaminase IgG and Deamidated Gliadin IgG",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 10,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-CELIAC-V04": {
        "algorithm_id": "RFLX-CELIAC-V04",
        "test_name": "Celiac Disease Cascade with Reflex to tTG-IgG (Tier 4)",
        "laboratory_department": "Gastroenterology",
        "reflex_trigger_criteria": "Total Serum IgA < 20 mg/dL (IgA deficiency)",
        "automated_order_action": "Tissue Transglutaminase IgG and Deamidated Gliadin IgG",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 12,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-CELIAC-V05": {
        "algorithm_id": "RFLX-CELIAC-V05",
        "test_name": "Celiac Disease Cascade with Reflex to tTG-IgG (Tier 5)",
        "laboratory_department": "Gastroenterology",
        "reflex_trigger_criteria": "Total Serum IgA < 20 mg/dL (IgA deficiency)",
        "automated_order_action": "Tissue Transglutaminase IgG and Deamidated Gliadin IgG",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 14,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-CELIAC-V06": {
        "algorithm_id": "RFLX-CELIAC-V06",
        "test_name": "Celiac Disease Cascade with Reflex to tTG-IgG (Tier 6)",
        "laboratory_department": "Gastroenterology",
        "reflex_trigger_criteria": "Total Serum IgA < 20 mg/dL (IgA deficiency)",
        "automated_order_action": "Tissue Transglutaminase IgG and Deamidated Gliadin IgG",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 16,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-CELIAC-V07": {
        "algorithm_id": "RFLX-CELIAC-V07",
        "test_name": "Celiac Disease Cascade with Reflex to tTG-IgG (Tier 7)",
        "laboratory_department": "Gastroenterology",
        "reflex_trigger_criteria": "Total Serum IgA < 20 mg/dL (IgA deficiency)",
        "automated_order_action": "Tissue Transglutaminase IgG and Deamidated Gliadin IgG",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 18,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-CELIAC-V08": {
        "algorithm_id": "RFLX-CELIAC-V08",
        "test_name": "Celiac Disease Cascade with Reflex to tTG-IgG (Tier 8)",
        "laboratory_department": "Gastroenterology",
        "reflex_trigger_criteria": "Total Serum IgA < 20 mg/dL (IgA deficiency)",
        "automated_order_action": "Tissue Transglutaminase IgG and Deamidated Gliadin IgG",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 20,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-CELIAC-V09": {
        "algorithm_id": "RFLX-CELIAC-V09",
        "test_name": "Celiac Disease Cascade with Reflex to tTG-IgG (Tier 9)",
        "laboratory_department": "Gastroenterology",
        "reflex_trigger_criteria": "Total Serum IgA < 20 mg/dL (IgA deficiency)",
        "automated_order_action": "Tissue Transglutaminase IgG and Deamidated Gliadin IgG",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 22,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-CELIAC-V10": {
        "algorithm_id": "RFLX-CELIAC-V10",
        "test_name": "Celiac Disease Cascade with Reflex to tTG-IgG (Tier 10)",
        "laboratory_department": "Gastroenterology",
        "reflex_trigger_criteria": "Total Serum IgA < 20 mg/dL (IgA deficiency)",
        "automated_order_action": "Tissue Transglutaminase IgG and Deamidated Gliadin IgG",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 24,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-CELIAC-V11": {
        "algorithm_id": "RFLX-CELIAC-V11",
        "test_name": "Celiac Disease Cascade with Reflex to tTG-IgG (Tier 11)",
        "laboratory_department": "Gastroenterology",
        "reflex_trigger_criteria": "Total Serum IgA < 20 mg/dL (IgA deficiency)",
        "automated_order_action": "Tissue Transglutaminase IgG and Deamidated Gliadin IgG",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 26,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-CELIAC-V12": {
        "algorithm_id": "RFLX-CELIAC-V12",
        "test_name": "Celiac Disease Cascade with Reflex to tTG-IgG (Tier 12)",
        "laboratory_department": "Gastroenterology",
        "reflex_trigger_criteria": "Total Serum IgA < 20 mg/dL (IgA deficiency)",
        "automated_order_action": "Tissue Transglutaminase IgG and Deamidated Gliadin IgG",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 28,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-CELIAC-V13": {
        "algorithm_id": "RFLX-CELIAC-V13",
        "test_name": "Celiac Disease Cascade with Reflex to tTG-IgG (Tier 13)",
        "laboratory_department": "Gastroenterology",
        "reflex_trigger_criteria": "Total Serum IgA < 20 mg/dL (IgA deficiency)",
        "automated_order_action": "Tissue Transglutaminase IgG and Deamidated Gliadin IgG",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 30,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-CELIAC-V14": {
        "algorithm_id": "RFLX-CELIAC-V14",
        "test_name": "Celiac Disease Cascade with Reflex to tTG-IgG (Tier 14)",
        "laboratory_department": "Gastroenterology",
        "reflex_trigger_criteria": "Total Serum IgA < 20 mg/dL (IgA deficiency)",
        "automated_order_action": "Tissue Transglutaminase IgG and Deamidated Gliadin IgG",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 32,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-CELIAC-V15": {
        "algorithm_id": "RFLX-CELIAC-V15",
        "test_name": "Celiac Disease Cascade with Reflex to tTG-IgG (Tier 15)",
        "laboratory_department": "Gastroenterology",
        "reflex_trigger_criteria": "Total Serum IgA < 20 mg/dL (IgA deficiency)",
        "automated_order_action": "Tissue Transglutaminase IgG and Deamidated Gliadin IgG",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 34,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-CELIAC-V16": {
        "algorithm_id": "RFLX-CELIAC-V16",
        "test_name": "Celiac Disease Cascade with Reflex to tTG-IgG (Tier 16)",
        "laboratory_department": "Gastroenterology",
        "reflex_trigger_criteria": "Total Serum IgA < 20 mg/dL (IgA deficiency)",
        "automated_order_action": "Tissue Transglutaminase IgG and Deamidated Gliadin IgG",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 36,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-CELIAC-V17": {
        "algorithm_id": "RFLX-CELIAC-V17",
        "test_name": "Celiac Disease Cascade with Reflex to tTG-IgG (Tier 17)",
        "laboratory_department": "Gastroenterology",
        "reflex_trigger_criteria": "Total Serum IgA < 20 mg/dL (IgA deficiency)",
        "automated_order_action": "Tissue Transglutaminase IgG and Deamidated Gliadin IgG",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 38,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-CELIAC-V18": {
        "algorithm_id": "RFLX-CELIAC-V18",
        "test_name": "Celiac Disease Cascade with Reflex to tTG-IgG (Tier 18)",
        "laboratory_department": "Gastroenterology",
        "reflex_trigger_criteria": "Total Serum IgA < 20 mg/dL (IgA deficiency)",
        "automated_order_action": "Tissue Transglutaminase IgG and Deamidated Gliadin IgG",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 40,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
    "RFLX-CELIAC-V19": {
        "algorithm_id": "RFLX-CELIAC-V19",
        "test_name": "Celiac Disease Cascade with Reflex to tTG-IgG (Tier 19)",
        "laboratory_department": "Gastroenterology",
        "reflex_trigger_criteria": "Total Serum IgA < 20 mg/dL (IgA deficiency)",
        "automated_order_action": "Tissue Transglutaminase IgG and Deamidated Gliadin IgG",
        "requires_pathologist_signoff": True,
        "turnaround_time_hours": 42,
        "critical_alert_threshold": "Immediate telephone notification for panic values",
    },
}
