/**
 * MediCore Nexus - Unified Client API Service
 * Supports direct API proxy to FastAPI backend with client-side mock fallback
 */

import {
  User,
  UserRole,
  Patient,
  Doctor,
  Appointment,
  ClinicalEncounter,
  MedicineMaster,
  InventoryBatch,
  Prescription,
  SafetyCheckResult,
  LabOrder,
  Invoice,
  InsuranceClaim,
  TelemedicineSession,
  NotificationItem,
  AuditLog
} from '../types';

const API_BASE = '/api/v1';

// Seed Personas for 1-Click Instant Login
export const DEMO_USERS: Record<string, { user: User; password_hint: string }> = {
  superadmin: {
    user: {
      id: 'usr-admin-01',
      email: 'admin@medicorenexus.io',
      username: 'superadmin',
      full_name: 'Dr. Alexander Wright, MD (System Admin)',
      phone_number: '+1 (555) 019-2831',
      role: 'Super Admin',
      hospital_id: 'hosp-001',
      department_id: 'dept-exec',
      is_active: true,
      is_verified: true,
      mfa_enabled: false,
      avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    },
    password_hint: 'Admin@12345',
  },
  doctor: {
    user: {
      id: 'usr-doc-01',
      email: 'dr.sarah.chen@medicorenexus.io',
      username: 'dr.sarah',
      full_name: 'Dr. Sarah Chen, MD (Cardiologist)',
      phone_number: '+1 (555) 432-8765',
      role: 'Doctor',
      hospital_id: 'hosp-001',
      department_id: 'dept-cardio',
      is_active: true,
      is_verified: true,
      mfa_enabled: false,
      avatar_url: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150',
    },
    password_hint: 'Doctor@12345',
  },
  pharmacist: {
    user: {
      id: 'usr-pharm-01',
      email: 'marcus.vance@medicorenexus.io',
      username: 'marcus.pharm',
      full_name: 'Marcus Vance, PharmD (Chief Pharmacist)',
      phone_number: '+1 (555) 789-0123',
      role: 'Pharmacist',
      hospital_id: 'hosp-001',
      department_id: 'dept-pharm',
      is_active: true,
      is_verified: true,
      mfa_enabled: false,
      avatar_url: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150',
    },
    password_hint: 'Pharm@12345',
  },
  nurse: {
    user: {
      id: 'usr-nurse-01',
      email: 'elena.rodriguez@medicorenexus.io',
      username: 'nurse.elena',
      full_name: 'Elena Rodriguez, RN (Triage Nurse)',
      phone_number: '+1 (555) 321-6540',
      role: 'Nurse',
      hospital_id: 'hosp-001',
      department_id: 'dept-er',
      is_active: true,
      is_verified: true,
      mfa_enabled: false,
      avatar_url: 'https://images.unsplash.com/photo-1594824813590-78965a329433?w=150',
    },
    password_hint: 'Nurse@12345',
  },
  labtech: {
    user: {
      id: 'usr-lab-01',
      email: 'david.kim@medicorenexus.io',
      username: 'david.lab',
      full_name: 'David Kim, MLS (Pathologist & Lab Tech)',
      phone_number: '+1 (555) 654-9871',
      role: 'Lab Technician',
      hospital_id: 'hosp-001',
      department_id: 'dept-lab',
      is_active: true,
      is_verified: true,
      mfa_enabled: false,
      avatar_url: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150',
    },
    password_hint: 'Lab@12345',
  },
  patient: {
    user: {
      id: 'usr-pat-01',
      email: 'john.doe@patient.medicorenexus.io',
      username: 'johndoe',
      full_name: 'Johnathan Doe (Patient)',
      phone_number: '+1 (555) 901-2345',
      role: 'Patient',
      hospital_id: 'hosp-001',
      is_active: true,
      is_verified: true,
      mfa_enabled: false,
      avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    },
    password_hint: 'Patient@12345',
  },
};

// Initial Seed Data for Frontend Fallback
export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'pat-001',
    mrn: 'MRN-2026-004128',
    first_name: 'Eleanor',
    last_name: 'Vance',
    dob: '1968-04-12',
    gender: 'Female',
    blood_group: 'A+',
    email: 'eleanor.vance@example.com',
    phone: '+1 (555) 234-5678',
    address: '45 Beacon Hill Rd',
    city: 'Boston',
    state: 'MA',
    zip_code: '02108',
    emergency_contact_name: 'Thomas Vance',
    emergency_contact_phone: '+1 (555) 234-9988',
    emergency_contact_relationship: 'Spouse',
    allergies: ['Penicillin', 'Sulfa Drugs'],
    chronic_conditions: ['Type 2 Diabetes Mellitus', 'Hypertension', 'Hyperlipidemia'],
    medical_alerts: ['Fall Risk Alert', 'Diabetic Foot Care Protocol'],
    primary_physician_id: 'usr-doc-01',
    insurance_policy_number: 'POL-BCBS-889104',
    insurance_provider: 'Blue Cross Blue Shield',
    created_at: '2026-05-02T10:00:00Z',
    is_active: true,
  },
  {
    id: 'pat-002',
    mrn: 'MRN-2026-004129',
    first_name: 'Michael',
    last_name: 'Chang',
    dob: '1985-09-24',
    gender: 'Male',
    blood_group: 'O+',
    email: 'm.chang85@example.com',
    phone: '+1 (555) 345-6789',
    address: '88 Commonwealth Ave',
    city: 'Boston',
    state: 'MA',
    zip_code: '02215',
    emergency_contact_name: 'Grace Chang',
    emergency_contact_phone: '+1 (555) 345-1122',
    emergency_contact_relationship: 'Sister',
    allergies: ['Aspirin', 'Ibuprofen / NSAIDs'],
    chronic_conditions: ['Moderate Persistent Asthma', 'Seasonal Allergic Rhinitis'],
    medical_alerts: ['Severe Aspirin-Exacerbated Respiratory Disease (AERD)'],
    primary_physician_id: 'usr-doc-01',
    insurance_policy_number: 'POL-AETNA-449120',
    insurance_provider: 'Aetna Health',
    created_at: '2026-06-15T14:30:00Z',
    is_active: true,
  },
  {
    id: 'pat-003',
    mrn: 'MRN-2026-004130',
    first_name: 'Sophia',
    last_name: 'Martinez',
    dob: '1992-11-03',
    gender: 'Female',
    blood_group: 'B+',
    email: 'sophia.m@example.com',
    phone: '+1 (555) 456-7890',
    address: '210 Tremont Street',
    city: 'Boston',
    state: 'MA',
    zip_code: '02116',
    emergency_contact_name: 'Carlos Martinez',
    emergency_contact_phone: '+1 (555) 456-3344',
    emergency_contact_relationship: 'Brother',
    allergies: ['Codeine'],
    chronic_conditions: ['Migraine with Aura', 'Generalized Anxiety Disorder'],
    medical_alerts: ['Renal Clearance Monitoring Required'],
    primary_physician_id: 'usr-doc-01',
    insurance_policy_number: 'POL-UHC-992384',
    insurance_provider: 'UnitedHealthcare',
    created_at: '2026-07-20T09:15:00Z',
    is_active: true,
  }
];

export const INITIAL_MEDICINES: MedicineMaster[] = [
  {
    id: 'med-001',
    brand_name: 'Lipitor',
    generic_name: 'Atorvastatin Calcium',
    sku_code: 'SKU-ATV-40MG',
    barcode: '8901088231901',
    dosage_form: 'Tablet',
    strength: '40 mg',
    unit_of_measure: 'Strip of 10 Tablets',
    route_of_administration: 'Oral',
    manufacturer: 'Pfizer Pharmaceuticals',
    therapeutic_class: 'HMG-CoA Reductase Inhibitor (Statin)',
    is_prescription_required: true,
    is_controlled_substance: false,
    storage_condition: 'Store at 20°C to 25°C',
    contraindications: ['Active Liver Disease', 'Pregnancy / Nursing'],
    standard_unit_price: 14.5,
    mrp: 18.0,
    is_active: true,
  },
  {
    id: 'med-002',
    brand_name: 'Glucophage XR',
    generic_name: 'Metformin Hydrochloride Extended-Release',
    sku_code: 'SKU-MET-500MG-XR',
    barcode: '8901088231902',
    dosage_form: 'Extended-Release Tablet',
    strength: '500 mg',
    unit_of_measure: 'Box of 60 Tablets',
    route_of_administration: 'Oral',
    manufacturer: 'Merck Healthcare',
    therapeutic_class: 'Biguanide Antidiabetic',
    is_prescription_required: true,
    is_controlled_substance: false,
    storage_condition: 'Store below 30°C. Protect from moisture.',
    contraindications: ['Severe Renal Dysfunction', 'Acute Acidosis'],
    standard_unit_price: 9.2,
    mrp: 12.5,
    is_active: true,
  },
  {
    id: 'med-003',
    brand_name: 'Amoxil',
    generic_name: 'Amoxicillin Trihydrate',
    sku_code: 'SKU-AMX-500MG',
    barcode: '8901088231903',
    dosage_form: 'Capsule',
    strength: '500 mg',
    unit_of_measure: 'Strip of 20 Capsules',
    route_of_administration: 'Oral',
    manufacturer: 'GlaxoSmithKline (GSK)',
    therapeutic_class: 'Beta-Lactam Penicillin Antibiotic',
    is_prescription_required: true,
    is_controlled_substance: false,
    storage_condition: 'Store at room temperature',
    contraindications: ['Penicillin Allergy'],
    standard_unit_price: 8.0,
    mrp: 11.0,
    is_active: true,
  },
  {
    id: 'med-004',
    brand_name: 'Ventolin HFA',
    generic_name: 'Albuterol Sulfate',
    sku_code: 'SKU-ALB-100MCG',
    barcode: '8901088231904',
    dosage_form: 'Metered Dose Inhaler',
    strength: '100 mcg/actuation',
    unit_of_measure: 'Canister (200 Puffs)',
    route_of_administration: 'Inhalation',
    manufacturer: 'GlaxoSmithKline (GSK)',
    therapeutic_class: 'SABA Bronchodilator',
    is_prescription_required: true,
    is_controlled_substance: false,
    storage_condition: 'Store upright between 15°C and 25°C',
    contraindications: ['Hypersensitivity to Albuterol'],
    standard_unit_price: 22.0,
    mrp: 28.5,
    is_active: true,
  },
  {
    id: 'med-005',
    brand_name: 'Tylenol Extra Strength',
    generic_name: 'Acetaminophen / Paracetamol',
    sku_code: 'SKU-APAP-500MG',
    barcode: '8901088231905',
    dosage_form: 'Caplet',
    strength: '500 mg',
    unit_of_measure: 'Bottle of 100 Caplets',
    route_of_administration: 'Oral',
    manufacturer: 'Johnson & Johnson',
    therapeutic_class: 'Analgesic & Antipyretic (OTC)',
    is_prescription_required: false,
    is_controlled_substance: false,
    storage_condition: 'Store at 20°C to 25°C',
    contraindications: ['Severe Hepatic Impairment'],
    standard_unit_price: 6.5,
    mrp: 8.99,
    is_active: true,
  },
  {
    id: 'med-006',
    brand_name: 'Plavix',
    generic_name: 'Clopidogrel Bisulfate',
    sku_code: 'SKU-CLOP-75MG',
    barcode: '8901088231906',
    dosage_form: 'Film-Coated Tablet',
    strength: '75 mg',
    unit_of_measure: 'Box of 28 Tablets',
    route_of_administration: 'Oral',
    manufacturer: 'Sanofi',
    therapeutic_class: 'Antiplatelet P2Y12 Inhibitor',
    is_prescription_required: true,
    is_controlled_substance: false,
    storage_condition: 'Store below 25°C',
    contraindications: ['Active Bleeding', 'Severe Hepatic Disease'],
    standard_unit_price: 28.0,
    mrp: 35.0,
    is_active: true,
  },
];

export const INITIAL_BATCHES: InventoryBatch[] = [
  {
    id: 'bat-001',
    medicine_id: 'med-001',
    medicine_name: 'Lipitor (Atorvastatin 40mg)',
    batch_number: 'ATV-2026-B1',
    lot_number: 'LOT-8891-PF',
    expiry_date: '2026-11-30',
    manufacturing_date: '2025-05-15',
    quantity_on_hand: 140,
    quantity_reserved: 10,
    reorder_level: 50,
    cost_per_unit: 11.2,
    selling_price_per_unit: 18.0,
    warehouse_name: 'Central Hospital Pharmacy Depot',
    shelf_location: 'Aisle 1 - Shelf A3',
    supplier_id: 'sup-001',
    days_to_expiry: 91,
    is_near_expiry: false,
    is_expired: false,
    is_low_stock: false,
  },
  {
    id: 'bat-003',
    medicine_id: 'med-002',
    medicine_name: 'Glucophage XR (Metformin 500mg)',
    batch_number: 'MET-2026-M1',
    lot_number: 'LOT-4412-MK',
    expiry_date: '2026-10-15',
    manufacturing_date: '2025-04-01',
    quantity_on_hand: 28,
    quantity_reserved: 5,
    reorder_level: 50,
    cost_per_unit: 7.5,
    selling_price_per_unit: 12.5,
    warehouse_name: 'Central Hospital Pharmacy Depot',
    shelf_location: 'Aisle 2 - Shelf B1',
    supplier_id: 'sup-002',
    days_to_expiry: 45,
    is_near_expiry: true,
    is_expired: false,
    is_low_stock: true,
  },
  {
    id: 'bat-004',
    medicine_id: 'med-003',
    medicine_name: 'Amoxil (Amoxicillin 500mg)',
    batch_number: 'AMX-2026-G1',
    lot_number: 'LOT-7731-GSK',
    expiry_date: '2026-09-20',
    manufacturing_date: '2025-03-10',
    quantity_on_hand: 85,
    quantity_reserved: 0,
    reorder_level: 40,
    cost_per_unit: 6.8,
    selling_price_per_unit: 11.0,
    warehouse_name: 'Emergency Ward Pharmacy',
    shelf_location: 'Aisle 3 - Shelf C1',
    supplier_id: 'sup-003',
    days_to_expiry: 20,
    is_near_expiry: true,
    is_expired: false,
    is_low_stock: false,
  },
  {
    id: 'bat-006',
    medicine_id: 'med-005',
    medicine_name: 'Tylenol Extra Strength 500mg',
    batch_number: 'TYL-2027-T1',
    lot_number: 'LOT-1192-JJ',
    expiry_date: '2027-12-31',
    manufacturing_date: '2025-11-20',
    quantity_on_hand: 210,
    quantity_reserved: 0,
    reorder_level: 50,
    cost_per_unit: 4.5,
    selling_price_per_unit: 8.99,
    warehouse_name: 'Retail OTC Pharmacy Counter',
    shelf_location: 'OTC Front Display Bay 2',
    supplier_id: 'sup-002',
    days_to_expiry: 487,
    is_near_expiry: false,
    is_expired: false,
    is_low_stock: false,
  },
];

export const INITIAL_PRESCRIPTIONS: Prescription[] = [
  {
    id: 'rx-001',
    rx_number: 'RX-2026-889101',
    patient_id: 'pat-001',
    patient_name: 'Eleanor Vance',
    doctor_id: 'doc-001',
    doctor_name: 'Dr. Sarah Chen, MD',
    encounter_id: 'enc-001',
    diagnosis_summary: 'Essential Hypertension, Type 2 Diabetes Mellitus, Hyperlipidemia',
    clinical_notes: 'Patient advised on regular lipid monitoring and low-sodium diet.',
    items: [
      {
        medicine_id: 'med-001',
        medicine_name: 'Lipitor (Atorvastatin 40mg)',
        dosage: '40 mg',
        frequency: 'Once daily at bedtime (QHS)',
        duration_days: 30,
        quantity: 30,
        route: 'Oral',
        instructions: 'Take 1 tablet every night before sleep.',
        refills_allowed: 3,
        refills_remaining: 3,
      },
      {
        medicine_id: 'med-002',
        medicine_name: 'Glucophage XR (Metformin 500mg)',
        dosage: '500 mg',
        frequency: 'Twice daily with meals (BID)',
        duration_days: 30,
        quantity: 60,
        route: 'Oral',
        instructions: 'Take with breakfast and dinner.',
        refills_allowed: 3,
        refills_remaining: 3,
      },
    ],
    digital_signature_hash: 'SIG-ECDSA-SHA256-CHEN-99210-AUTH-VALID',
    qr_code_payload: 'https://rx.medicorenexus.io/verify/RX-2026-889101',
    status: 'Validated',
    created_at: '2026-08-28T11:00:00Z',
    validated_at: '2026-08-28T11:30:00Z',
    validated_by_pharmacist: 'Marcus Vance, PharmD',
  },
  {
    id: 'rx-002',
    rx_number: 'RX-2026-889102',
    patient_id: 'pat-002',
    patient_name: 'Michael Chang',
    doctor_id: 'doc-001',
    doctor_name: 'Dr. Sarah Chen, MD',
    diagnosis_summary: 'Moderate Persistent Asthma with acute bronchospasm prophylaxis',
    clinical_notes: 'Keep rescue inhaler accessible at all times.',
    items: [
      {
        medicine_id: 'med-004',
        medicine_name: 'Ventolin HFA (Albuterol Inhaler)',
        dosage: '100 mcg',
        frequency: '1-2 puffs PRN wheezing',
        duration_days: 60,
        quantity: 1,
        route: 'Inhalation',
        instructions: 'Inhale 2 puffs as needed for shortness of breath.',
        refills_allowed: 2,
        refills_remaining: 2,
      },
    ],
    digital_signature_hash: 'SIG-ECDSA-SHA256-CHEN-99211-AUTH-VALID',
    qr_code_payload: 'https://rx.medicorenexus.io/verify/RX-2026-889102',
    status: 'Active',
    created_at: '2026-08-31T09:00:00Z',
  },
];
