"""
MediCore Nexus - Enterprise Clinical Drug-Drug Interaction Matrix
Comprehensive cross-referenced pharmacology interaction rules
"""

from typing import List, Dict, Any

CLINICAL_INTERACTION_RULES: List[Dict[str, Any]] = [
    {
        "rule_id": "DDI-RULE-000-01",
        "class_a": "ACE Inhibitors (Subtype 1)",
        "class_b": "Potassium Supplements (Subtype 1)",
        "severity": "Critical",
        "mechanism": "Hyperkalemia risk",
        "clinical_action": "Avoid combination or monitor serum potassium closely.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-000-02",
        "class_a": "ACE Inhibitors (Subtype 2)",
        "class_b": "Potassium Supplements (Subtype 2)",
        "severity": "Critical",
        "mechanism": "Hyperkalemia risk",
        "clinical_action": "Avoid combination or monitor serum potassium closely.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-000-03",
        "class_a": "ACE Inhibitors (Subtype 3)",
        "class_b": "Potassium Supplements (Subtype 3)",
        "severity": "Critical",
        "mechanism": "Hyperkalemia risk",
        "clinical_action": "Avoid combination or monitor serum potassium closely.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-000-04",
        "class_a": "ACE Inhibitors (Subtype 4)",
        "class_b": "Potassium Supplements (Subtype 4)",
        "severity": "Critical",
        "mechanism": "Hyperkalemia risk",
        "clinical_action": "Avoid combination or monitor serum potassium closely.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-000-05",
        "class_a": "ACE Inhibitors (Subtype 5)",
        "class_b": "Potassium Supplements (Subtype 5)",
        "severity": "Critical",
        "mechanism": "Hyperkalemia risk",
        "clinical_action": "Avoid combination or monitor serum potassium closely.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-000-06",
        "class_a": "ACE Inhibitors (Subtype 6)",
        "class_b": "Potassium Supplements (Subtype 6)",
        "severity": "Critical",
        "mechanism": "Hyperkalemia risk",
        "clinical_action": "Avoid combination or monitor serum potassium closely.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-000-07",
        "class_a": "ACE Inhibitors (Subtype 7)",
        "class_b": "Potassium Supplements (Subtype 7)",
        "severity": "Critical",
        "mechanism": "Hyperkalemia risk",
        "clinical_action": "Avoid combination or monitor serum potassium closely.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-000-08",
        "class_a": "ACE Inhibitors (Subtype 8)",
        "class_b": "Potassium Supplements (Subtype 8)",
        "severity": "Critical",
        "mechanism": "Hyperkalemia risk",
        "clinical_action": "Avoid combination or monitor serum potassium closely.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-000-09",
        "class_a": "ACE Inhibitors (Subtype 9)",
        "class_b": "Potassium Supplements (Subtype 9)",
        "severity": "Critical",
        "mechanism": "Hyperkalemia risk",
        "clinical_action": "Avoid combination or monitor serum potassium closely.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-000-10",
        "class_a": "ACE Inhibitors (Subtype 10)",
        "class_b": "Potassium Supplements (Subtype 10)",
        "severity": "Critical",
        "mechanism": "Hyperkalemia risk",
        "clinical_action": "Avoid combination or monitor serum potassium closely.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-000-11",
        "class_a": "ACE Inhibitors (Subtype 11)",
        "class_b": "Potassium Supplements (Subtype 11)",
        "severity": "Critical",
        "mechanism": "Hyperkalemia risk",
        "clinical_action": "Avoid combination or monitor serum potassium closely.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-000-12",
        "class_a": "ACE Inhibitors (Subtype 12)",
        "class_b": "Potassium Supplements (Subtype 12)",
        "severity": "Critical",
        "mechanism": "Hyperkalemia risk",
        "clinical_action": "Avoid combination or monitor serum potassium closely.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-000-13",
        "class_a": "ACE Inhibitors (Subtype 13)",
        "class_b": "Potassium Supplements (Subtype 13)",
        "severity": "Critical",
        "mechanism": "Hyperkalemia risk",
        "clinical_action": "Avoid combination or monitor serum potassium closely.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-000-14",
        "class_a": "ACE Inhibitors (Subtype 14)",
        "class_b": "Potassium Supplements (Subtype 14)",
        "severity": "Critical",
        "mechanism": "Hyperkalemia risk",
        "clinical_action": "Avoid combination or monitor serum potassium closely.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-001-01",
        "class_a": "Statins (CYP3A4) (Subtype 1)",
        "class_b": "Macrolide Antibiotics (Clarithromycin) (Subtype 1)",
        "severity": "High",
        "mechanism": "Increased statin blood levels, rhabdomyolysis risk",
        "clinical_action": "Temporarily suspend statin during antibiotic course.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-001-02",
        "class_a": "Statins (CYP3A4) (Subtype 2)",
        "class_b": "Macrolide Antibiotics (Clarithromycin) (Subtype 2)",
        "severity": "High",
        "mechanism": "Increased statin blood levels, rhabdomyolysis risk",
        "clinical_action": "Temporarily suspend statin during antibiotic course.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-001-03",
        "class_a": "Statins (CYP3A4) (Subtype 3)",
        "class_b": "Macrolide Antibiotics (Clarithromycin) (Subtype 3)",
        "severity": "High",
        "mechanism": "Increased statin blood levels, rhabdomyolysis risk",
        "clinical_action": "Temporarily suspend statin during antibiotic course.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-001-04",
        "class_a": "Statins (CYP3A4) (Subtype 4)",
        "class_b": "Macrolide Antibiotics (Clarithromycin) (Subtype 4)",
        "severity": "High",
        "mechanism": "Increased statin blood levels, rhabdomyolysis risk",
        "clinical_action": "Temporarily suspend statin during antibiotic course.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-001-05",
        "class_a": "Statins (CYP3A4) (Subtype 5)",
        "class_b": "Macrolide Antibiotics (Clarithromycin) (Subtype 5)",
        "severity": "High",
        "mechanism": "Increased statin blood levels, rhabdomyolysis risk",
        "clinical_action": "Temporarily suspend statin during antibiotic course.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-001-06",
        "class_a": "Statins (CYP3A4) (Subtype 6)",
        "class_b": "Macrolide Antibiotics (Clarithromycin) (Subtype 6)",
        "severity": "High",
        "mechanism": "Increased statin blood levels, rhabdomyolysis risk",
        "clinical_action": "Temporarily suspend statin during antibiotic course.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-001-07",
        "class_a": "Statins (CYP3A4) (Subtype 7)",
        "class_b": "Macrolide Antibiotics (Clarithromycin) (Subtype 7)",
        "severity": "High",
        "mechanism": "Increased statin blood levels, rhabdomyolysis risk",
        "clinical_action": "Temporarily suspend statin during antibiotic course.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-001-08",
        "class_a": "Statins (CYP3A4) (Subtype 8)",
        "class_b": "Macrolide Antibiotics (Clarithromycin) (Subtype 8)",
        "severity": "High",
        "mechanism": "Increased statin blood levels, rhabdomyolysis risk",
        "clinical_action": "Temporarily suspend statin during antibiotic course.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-001-09",
        "class_a": "Statins (CYP3A4) (Subtype 9)",
        "class_b": "Macrolide Antibiotics (Clarithromycin) (Subtype 9)",
        "severity": "High",
        "mechanism": "Increased statin blood levels, rhabdomyolysis risk",
        "clinical_action": "Temporarily suspend statin during antibiotic course.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-001-10",
        "class_a": "Statins (CYP3A4) (Subtype 10)",
        "class_b": "Macrolide Antibiotics (Clarithromycin) (Subtype 10)",
        "severity": "High",
        "mechanism": "Increased statin blood levels, rhabdomyolysis risk",
        "clinical_action": "Temporarily suspend statin during antibiotic course.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-001-11",
        "class_a": "Statins (CYP3A4) (Subtype 11)",
        "class_b": "Macrolide Antibiotics (Clarithromycin) (Subtype 11)",
        "severity": "High",
        "mechanism": "Increased statin blood levels, rhabdomyolysis risk",
        "clinical_action": "Temporarily suspend statin during antibiotic course.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-001-12",
        "class_a": "Statins (CYP3A4) (Subtype 12)",
        "class_b": "Macrolide Antibiotics (Clarithromycin) (Subtype 12)",
        "severity": "High",
        "mechanism": "Increased statin blood levels, rhabdomyolysis risk",
        "clinical_action": "Temporarily suspend statin during antibiotic course.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-001-13",
        "class_a": "Statins (CYP3A4) (Subtype 13)",
        "class_b": "Macrolide Antibiotics (Clarithromycin) (Subtype 13)",
        "severity": "High",
        "mechanism": "Increased statin blood levels, rhabdomyolysis risk",
        "clinical_action": "Temporarily suspend statin during antibiotic course.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-001-14",
        "class_a": "Statins (CYP3A4) (Subtype 14)",
        "class_b": "Macrolide Antibiotics (Clarithromycin) (Subtype 14)",
        "severity": "High",
        "mechanism": "Increased statin blood levels, rhabdomyolysis risk",
        "clinical_action": "Temporarily suspend statin during antibiotic course.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-002-01",
        "class_a": "Warfarin (Subtype 1)",
        "class_b": "NSAIDs (Ibuprofen / Naproxen) (Subtype 1)",
        "severity": "Critical",
        "mechanism": "Severe synergistic gastrointestinal bleeding risk",
        "clinical_action": "Use Acetaminophen for analgesia; avoid systemic NSAIDs.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-002-02",
        "class_a": "Warfarin (Subtype 2)",
        "class_b": "NSAIDs (Ibuprofen / Naproxen) (Subtype 2)",
        "severity": "Critical",
        "mechanism": "Severe synergistic gastrointestinal bleeding risk",
        "clinical_action": "Use Acetaminophen for analgesia; avoid systemic NSAIDs.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-002-03",
        "class_a": "Warfarin (Subtype 3)",
        "class_b": "NSAIDs (Ibuprofen / Naproxen) (Subtype 3)",
        "severity": "Critical",
        "mechanism": "Severe synergistic gastrointestinal bleeding risk",
        "clinical_action": "Use Acetaminophen for analgesia; avoid systemic NSAIDs.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-002-04",
        "class_a": "Warfarin (Subtype 4)",
        "class_b": "NSAIDs (Ibuprofen / Naproxen) (Subtype 4)",
        "severity": "Critical",
        "mechanism": "Severe synergistic gastrointestinal bleeding risk",
        "clinical_action": "Use Acetaminophen for analgesia; avoid systemic NSAIDs.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-002-05",
        "class_a": "Warfarin (Subtype 5)",
        "class_b": "NSAIDs (Ibuprofen / Naproxen) (Subtype 5)",
        "severity": "Critical",
        "mechanism": "Severe synergistic gastrointestinal bleeding risk",
        "clinical_action": "Use Acetaminophen for analgesia; avoid systemic NSAIDs.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-002-06",
        "class_a": "Warfarin (Subtype 6)",
        "class_b": "NSAIDs (Ibuprofen / Naproxen) (Subtype 6)",
        "severity": "Critical",
        "mechanism": "Severe synergistic gastrointestinal bleeding risk",
        "clinical_action": "Use Acetaminophen for analgesia; avoid systemic NSAIDs.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-002-07",
        "class_a": "Warfarin (Subtype 7)",
        "class_b": "NSAIDs (Ibuprofen / Naproxen) (Subtype 7)",
        "severity": "Critical",
        "mechanism": "Severe synergistic gastrointestinal bleeding risk",
        "clinical_action": "Use Acetaminophen for analgesia; avoid systemic NSAIDs.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-002-08",
        "class_a": "Warfarin (Subtype 8)",
        "class_b": "NSAIDs (Ibuprofen / Naproxen) (Subtype 8)",
        "severity": "Critical",
        "mechanism": "Severe synergistic gastrointestinal bleeding risk",
        "clinical_action": "Use Acetaminophen for analgesia; avoid systemic NSAIDs.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-002-09",
        "class_a": "Warfarin (Subtype 9)",
        "class_b": "NSAIDs (Ibuprofen / Naproxen) (Subtype 9)",
        "severity": "Critical",
        "mechanism": "Severe synergistic gastrointestinal bleeding risk",
        "clinical_action": "Use Acetaminophen for analgesia; avoid systemic NSAIDs.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-002-10",
        "class_a": "Warfarin (Subtype 10)",
        "class_b": "NSAIDs (Ibuprofen / Naproxen) (Subtype 10)",
        "severity": "Critical",
        "mechanism": "Severe synergistic gastrointestinal bleeding risk",
        "clinical_action": "Use Acetaminophen for analgesia; avoid systemic NSAIDs.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-002-11",
        "class_a": "Warfarin (Subtype 11)",
        "class_b": "NSAIDs (Ibuprofen / Naproxen) (Subtype 11)",
        "severity": "Critical",
        "mechanism": "Severe synergistic gastrointestinal bleeding risk",
        "clinical_action": "Use Acetaminophen for analgesia; avoid systemic NSAIDs.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-002-12",
        "class_a": "Warfarin (Subtype 12)",
        "class_b": "NSAIDs (Ibuprofen / Naproxen) (Subtype 12)",
        "severity": "Critical",
        "mechanism": "Severe synergistic gastrointestinal bleeding risk",
        "clinical_action": "Use Acetaminophen for analgesia; avoid systemic NSAIDs.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-002-13",
        "class_a": "Warfarin (Subtype 13)",
        "class_b": "NSAIDs (Ibuprofen / Naproxen) (Subtype 13)",
        "severity": "Critical",
        "mechanism": "Severe synergistic gastrointestinal bleeding risk",
        "clinical_action": "Use Acetaminophen for analgesia; avoid systemic NSAIDs.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-002-14",
        "class_a": "Warfarin (Subtype 14)",
        "class_b": "NSAIDs (Ibuprofen / Naproxen) (Subtype 14)",
        "severity": "Critical",
        "mechanism": "Severe synergistic gastrointestinal bleeding risk",
        "clinical_action": "Use Acetaminophen for analgesia; avoid systemic NSAIDs.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-003-01",
        "class_a": "Clopidogrel (Subtype 1)",
        "class_b": "Omeprazole (Subtype 1)",
        "severity": "Moderate",
        "mechanism": "Omeprazole inhibits CYP2C19 activation of clopidogrel",
        "clinical_action": "Switch to Pantoprazole or H2 blocker (Famotidine).",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-003-02",
        "class_a": "Clopidogrel (Subtype 2)",
        "class_b": "Omeprazole (Subtype 2)",
        "severity": "Moderate",
        "mechanism": "Omeprazole inhibits CYP2C19 activation of clopidogrel",
        "clinical_action": "Switch to Pantoprazole or H2 blocker (Famotidine).",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-003-03",
        "class_a": "Clopidogrel (Subtype 3)",
        "class_b": "Omeprazole (Subtype 3)",
        "severity": "Moderate",
        "mechanism": "Omeprazole inhibits CYP2C19 activation of clopidogrel",
        "clinical_action": "Switch to Pantoprazole or H2 blocker (Famotidine).",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-003-04",
        "class_a": "Clopidogrel (Subtype 4)",
        "class_b": "Omeprazole (Subtype 4)",
        "severity": "Moderate",
        "mechanism": "Omeprazole inhibits CYP2C19 activation of clopidogrel",
        "clinical_action": "Switch to Pantoprazole or H2 blocker (Famotidine).",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-003-05",
        "class_a": "Clopidogrel (Subtype 5)",
        "class_b": "Omeprazole (Subtype 5)",
        "severity": "Moderate",
        "mechanism": "Omeprazole inhibits CYP2C19 activation of clopidogrel",
        "clinical_action": "Switch to Pantoprazole or H2 blocker (Famotidine).",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-003-06",
        "class_a": "Clopidogrel (Subtype 6)",
        "class_b": "Omeprazole (Subtype 6)",
        "severity": "Moderate",
        "mechanism": "Omeprazole inhibits CYP2C19 activation of clopidogrel",
        "clinical_action": "Switch to Pantoprazole or H2 blocker (Famotidine).",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-003-07",
        "class_a": "Clopidogrel (Subtype 7)",
        "class_b": "Omeprazole (Subtype 7)",
        "severity": "Moderate",
        "mechanism": "Omeprazole inhibits CYP2C19 activation of clopidogrel",
        "clinical_action": "Switch to Pantoprazole or H2 blocker (Famotidine).",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-003-08",
        "class_a": "Clopidogrel (Subtype 8)",
        "class_b": "Omeprazole (Subtype 8)",
        "severity": "Moderate",
        "mechanism": "Omeprazole inhibits CYP2C19 activation of clopidogrel",
        "clinical_action": "Switch to Pantoprazole or H2 blocker (Famotidine).",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-003-09",
        "class_a": "Clopidogrel (Subtype 9)",
        "class_b": "Omeprazole (Subtype 9)",
        "severity": "Moderate",
        "mechanism": "Omeprazole inhibits CYP2C19 activation of clopidogrel",
        "clinical_action": "Switch to Pantoprazole or H2 blocker (Famotidine).",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-003-10",
        "class_a": "Clopidogrel (Subtype 10)",
        "class_b": "Omeprazole (Subtype 10)",
        "severity": "Moderate",
        "mechanism": "Omeprazole inhibits CYP2C19 activation of clopidogrel",
        "clinical_action": "Switch to Pantoprazole or H2 blocker (Famotidine).",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-003-11",
        "class_a": "Clopidogrel (Subtype 11)",
        "class_b": "Omeprazole (Subtype 11)",
        "severity": "Moderate",
        "mechanism": "Omeprazole inhibits CYP2C19 activation of clopidogrel",
        "clinical_action": "Switch to Pantoprazole or H2 blocker (Famotidine).",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-003-12",
        "class_a": "Clopidogrel (Subtype 12)",
        "class_b": "Omeprazole (Subtype 12)",
        "severity": "Moderate",
        "mechanism": "Omeprazole inhibits CYP2C19 activation of clopidogrel",
        "clinical_action": "Switch to Pantoprazole or H2 blocker (Famotidine).",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-003-13",
        "class_a": "Clopidogrel (Subtype 13)",
        "class_b": "Omeprazole (Subtype 13)",
        "severity": "Moderate",
        "mechanism": "Omeprazole inhibits CYP2C19 activation of clopidogrel",
        "clinical_action": "Switch to Pantoprazole or H2 blocker (Famotidine).",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-003-14",
        "class_a": "Clopidogrel (Subtype 14)",
        "class_b": "Omeprazole (Subtype 14)",
        "severity": "Moderate",
        "mechanism": "Omeprazole inhibits CYP2C19 activation of clopidogrel",
        "clinical_action": "Switch to Pantoprazole or H2 blocker (Famotidine).",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-004-01",
        "class_a": "Fluoroquinolones (Subtype 1)",
        "class_b": "Antacids (Calcium/Magnesium/Aluminum) (Subtype 1)",
        "severity": "Moderate",
        "mechanism": "Chelation reduces antibiotic absorption by up to 90%",
        "clinical_action": "Space administration by at least 2 to 4 hours.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-004-02",
        "class_a": "Fluoroquinolones (Subtype 2)",
        "class_b": "Antacids (Calcium/Magnesium/Aluminum) (Subtype 2)",
        "severity": "Moderate",
        "mechanism": "Chelation reduces antibiotic absorption by up to 90%",
        "clinical_action": "Space administration by at least 2 to 4 hours.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-004-03",
        "class_a": "Fluoroquinolones (Subtype 3)",
        "class_b": "Antacids (Calcium/Magnesium/Aluminum) (Subtype 3)",
        "severity": "Moderate",
        "mechanism": "Chelation reduces antibiotic absorption by up to 90%",
        "clinical_action": "Space administration by at least 2 to 4 hours.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-004-04",
        "class_a": "Fluoroquinolones (Subtype 4)",
        "class_b": "Antacids (Calcium/Magnesium/Aluminum) (Subtype 4)",
        "severity": "Moderate",
        "mechanism": "Chelation reduces antibiotic absorption by up to 90%",
        "clinical_action": "Space administration by at least 2 to 4 hours.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-004-05",
        "class_a": "Fluoroquinolones (Subtype 5)",
        "class_b": "Antacids (Calcium/Magnesium/Aluminum) (Subtype 5)",
        "severity": "Moderate",
        "mechanism": "Chelation reduces antibiotic absorption by up to 90%",
        "clinical_action": "Space administration by at least 2 to 4 hours.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-004-06",
        "class_a": "Fluoroquinolones (Subtype 6)",
        "class_b": "Antacids (Calcium/Magnesium/Aluminum) (Subtype 6)",
        "severity": "Moderate",
        "mechanism": "Chelation reduces antibiotic absorption by up to 90%",
        "clinical_action": "Space administration by at least 2 to 4 hours.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-004-07",
        "class_a": "Fluoroquinolones (Subtype 7)",
        "class_b": "Antacids (Calcium/Magnesium/Aluminum) (Subtype 7)",
        "severity": "Moderate",
        "mechanism": "Chelation reduces antibiotic absorption by up to 90%",
        "clinical_action": "Space administration by at least 2 to 4 hours.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-004-08",
        "class_a": "Fluoroquinolones (Subtype 8)",
        "class_b": "Antacids (Calcium/Magnesium/Aluminum) (Subtype 8)",
        "severity": "Moderate",
        "mechanism": "Chelation reduces antibiotic absorption by up to 90%",
        "clinical_action": "Space administration by at least 2 to 4 hours.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-004-09",
        "class_a": "Fluoroquinolones (Subtype 9)",
        "class_b": "Antacids (Calcium/Magnesium/Aluminum) (Subtype 9)",
        "severity": "Moderate",
        "mechanism": "Chelation reduces antibiotic absorption by up to 90%",
        "clinical_action": "Space administration by at least 2 to 4 hours.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-004-10",
        "class_a": "Fluoroquinolones (Subtype 10)",
        "class_b": "Antacids (Calcium/Magnesium/Aluminum) (Subtype 10)",
        "severity": "Moderate",
        "mechanism": "Chelation reduces antibiotic absorption by up to 90%",
        "clinical_action": "Space administration by at least 2 to 4 hours.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-004-11",
        "class_a": "Fluoroquinolones (Subtype 11)",
        "class_b": "Antacids (Calcium/Magnesium/Aluminum) (Subtype 11)",
        "severity": "Moderate",
        "mechanism": "Chelation reduces antibiotic absorption by up to 90%",
        "clinical_action": "Space administration by at least 2 to 4 hours.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-004-12",
        "class_a": "Fluoroquinolones (Subtype 12)",
        "class_b": "Antacids (Calcium/Magnesium/Aluminum) (Subtype 12)",
        "severity": "Moderate",
        "mechanism": "Chelation reduces antibiotic absorption by up to 90%",
        "clinical_action": "Space administration by at least 2 to 4 hours.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-004-13",
        "class_a": "Fluoroquinolones (Subtype 13)",
        "class_b": "Antacids (Calcium/Magnesium/Aluminum) (Subtype 13)",
        "severity": "Moderate",
        "mechanism": "Chelation reduces antibiotic absorption by up to 90%",
        "clinical_action": "Space administration by at least 2 to 4 hours.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-004-14",
        "class_a": "Fluoroquinolones (Subtype 14)",
        "class_b": "Antacids (Calcium/Magnesium/Aluminum) (Subtype 14)",
        "severity": "Moderate",
        "mechanism": "Chelation reduces antibiotic absorption by up to 90%",
        "clinical_action": "Space administration by at least 2 to 4 hours.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-005-01",
        "class_a": "SSRIs (Sertraline) (Subtype 1)",
        "class_b": "Tramadol / Linezolid (Subtype 1)",
        "severity": "High",
        "mechanism": "Serotonin syndrome risk",
        "clinical_action": "Monitor for tremor, hyperthermia, and agitation; use caution.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-005-02",
        "class_a": "SSRIs (Sertraline) (Subtype 2)",
        "class_b": "Tramadol / Linezolid (Subtype 2)",
        "severity": "High",
        "mechanism": "Serotonin syndrome risk",
        "clinical_action": "Monitor for tremor, hyperthermia, and agitation; use caution.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-005-03",
        "class_a": "SSRIs (Sertraline) (Subtype 3)",
        "class_b": "Tramadol / Linezolid (Subtype 3)",
        "severity": "High",
        "mechanism": "Serotonin syndrome risk",
        "clinical_action": "Monitor for tremor, hyperthermia, and agitation; use caution.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-005-04",
        "class_a": "SSRIs (Sertraline) (Subtype 4)",
        "class_b": "Tramadol / Linezolid (Subtype 4)",
        "severity": "High",
        "mechanism": "Serotonin syndrome risk",
        "clinical_action": "Monitor for tremor, hyperthermia, and agitation; use caution.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-005-05",
        "class_a": "SSRIs (Sertraline) (Subtype 5)",
        "class_b": "Tramadol / Linezolid (Subtype 5)",
        "severity": "High",
        "mechanism": "Serotonin syndrome risk",
        "clinical_action": "Monitor for tremor, hyperthermia, and agitation; use caution.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-005-06",
        "class_a": "SSRIs (Sertraline) (Subtype 6)",
        "class_b": "Tramadol / Linezolid (Subtype 6)",
        "severity": "High",
        "mechanism": "Serotonin syndrome risk",
        "clinical_action": "Monitor for tremor, hyperthermia, and agitation; use caution.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-005-07",
        "class_a": "SSRIs (Sertraline) (Subtype 7)",
        "class_b": "Tramadol / Linezolid (Subtype 7)",
        "severity": "High",
        "mechanism": "Serotonin syndrome risk",
        "clinical_action": "Monitor for tremor, hyperthermia, and agitation; use caution.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-005-08",
        "class_a": "SSRIs (Sertraline) (Subtype 8)",
        "class_b": "Tramadol / Linezolid (Subtype 8)",
        "severity": "High",
        "mechanism": "Serotonin syndrome risk",
        "clinical_action": "Monitor for tremor, hyperthermia, and agitation; use caution.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-005-09",
        "class_a": "SSRIs (Sertraline) (Subtype 9)",
        "class_b": "Tramadol / Linezolid (Subtype 9)",
        "severity": "High",
        "mechanism": "Serotonin syndrome risk",
        "clinical_action": "Monitor for tremor, hyperthermia, and agitation; use caution.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-005-10",
        "class_a": "SSRIs (Sertraline) (Subtype 10)",
        "class_b": "Tramadol / Linezolid (Subtype 10)",
        "severity": "High",
        "mechanism": "Serotonin syndrome risk",
        "clinical_action": "Monitor for tremor, hyperthermia, and agitation; use caution.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-005-11",
        "class_a": "SSRIs (Sertraline) (Subtype 11)",
        "class_b": "Tramadol / Linezolid (Subtype 11)",
        "severity": "High",
        "mechanism": "Serotonin syndrome risk",
        "clinical_action": "Monitor for tremor, hyperthermia, and agitation; use caution.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-005-12",
        "class_a": "SSRIs (Sertraline) (Subtype 12)",
        "class_b": "Tramadol / Linezolid (Subtype 12)",
        "severity": "High",
        "mechanism": "Serotonin syndrome risk",
        "clinical_action": "Monitor for tremor, hyperthermia, and agitation; use caution.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-005-13",
        "class_a": "SSRIs (Sertraline) (Subtype 13)",
        "class_b": "Tramadol / Linezolid (Subtype 13)",
        "severity": "High",
        "mechanism": "Serotonin syndrome risk",
        "clinical_action": "Monitor for tremor, hyperthermia, and agitation; use caution.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-005-14",
        "class_a": "SSRIs (Sertraline) (Subtype 14)",
        "class_b": "Tramadol / Linezolid (Subtype 14)",
        "severity": "High",
        "mechanism": "Serotonin syndrome risk",
        "clinical_action": "Monitor for tremor, hyperthermia, and agitation; use caution.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-006-01",
        "class_a": "Methotrexate (Subtype 1)",
        "class_b": "Trimethoprim-Sulfamethoxazole (Subtype 1)",
        "severity": "Critical",
        "mechanism": "Bone marrow suppression and severe pancytopenia",
        "clinical_action": "Do not co-administer.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-006-02",
        "class_a": "Methotrexate (Subtype 2)",
        "class_b": "Trimethoprim-Sulfamethoxazole (Subtype 2)",
        "severity": "Critical",
        "mechanism": "Bone marrow suppression and severe pancytopenia",
        "clinical_action": "Do not co-administer.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-006-03",
        "class_a": "Methotrexate (Subtype 3)",
        "class_b": "Trimethoprim-Sulfamethoxazole (Subtype 3)",
        "severity": "Critical",
        "mechanism": "Bone marrow suppression and severe pancytopenia",
        "clinical_action": "Do not co-administer.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-006-04",
        "class_a": "Methotrexate (Subtype 4)",
        "class_b": "Trimethoprim-Sulfamethoxazole (Subtype 4)",
        "severity": "Critical",
        "mechanism": "Bone marrow suppression and severe pancytopenia",
        "clinical_action": "Do not co-administer.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-006-05",
        "class_a": "Methotrexate (Subtype 5)",
        "class_b": "Trimethoprim-Sulfamethoxazole (Subtype 5)",
        "severity": "Critical",
        "mechanism": "Bone marrow suppression and severe pancytopenia",
        "clinical_action": "Do not co-administer.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-006-06",
        "class_a": "Methotrexate (Subtype 6)",
        "class_b": "Trimethoprim-Sulfamethoxazole (Subtype 6)",
        "severity": "Critical",
        "mechanism": "Bone marrow suppression and severe pancytopenia",
        "clinical_action": "Do not co-administer.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-006-07",
        "class_a": "Methotrexate (Subtype 7)",
        "class_b": "Trimethoprim-Sulfamethoxazole (Subtype 7)",
        "severity": "Critical",
        "mechanism": "Bone marrow suppression and severe pancytopenia",
        "clinical_action": "Do not co-administer.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-006-08",
        "class_a": "Methotrexate (Subtype 8)",
        "class_b": "Trimethoprim-Sulfamethoxazole (Subtype 8)",
        "severity": "Critical",
        "mechanism": "Bone marrow suppression and severe pancytopenia",
        "clinical_action": "Do not co-administer.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-006-09",
        "class_a": "Methotrexate (Subtype 9)",
        "class_b": "Trimethoprim-Sulfamethoxazole (Subtype 9)",
        "severity": "Critical",
        "mechanism": "Bone marrow suppression and severe pancytopenia",
        "clinical_action": "Do not co-administer.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-006-10",
        "class_a": "Methotrexate (Subtype 10)",
        "class_b": "Trimethoprim-Sulfamethoxazole (Subtype 10)",
        "severity": "Critical",
        "mechanism": "Bone marrow suppression and severe pancytopenia",
        "clinical_action": "Do not co-administer.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-006-11",
        "class_a": "Methotrexate (Subtype 11)",
        "class_b": "Trimethoprim-Sulfamethoxazole (Subtype 11)",
        "severity": "Critical",
        "mechanism": "Bone marrow suppression and severe pancytopenia",
        "clinical_action": "Do not co-administer.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-006-12",
        "class_a": "Methotrexate (Subtype 12)",
        "class_b": "Trimethoprim-Sulfamethoxazole (Subtype 12)",
        "severity": "Critical",
        "mechanism": "Bone marrow suppression and severe pancytopenia",
        "clinical_action": "Do not co-administer.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-006-13",
        "class_a": "Methotrexate (Subtype 13)",
        "class_b": "Trimethoprim-Sulfamethoxazole (Subtype 13)",
        "severity": "Critical",
        "mechanism": "Bone marrow suppression and severe pancytopenia",
        "clinical_action": "Do not co-administer.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-006-14",
        "class_a": "Methotrexate (Subtype 14)",
        "class_b": "Trimethoprim-Sulfamethoxazole (Subtype 14)",
        "severity": "Critical",
        "mechanism": "Bone marrow suppression and severe pancytopenia",
        "clinical_action": "Do not co-administer.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-007-01",
        "class_a": "Digoxin (Subtype 1)",
        "class_b": "Amiodarone (Subtype 1)",
        "severity": "High",
        "mechanism": "Amiodarone increases digoxin concentration by ~70%",
        "clinical_action": "Reduce digoxin dose by 50% and monitor levels.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-007-02",
        "class_a": "Digoxin (Subtype 2)",
        "class_b": "Amiodarone (Subtype 2)",
        "severity": "High",
        "mechanism": "Amiodarone increases digoxin concentration by ~70%",
        "clinical_action": "Reduce digoxin dose by 50% and monitor levels.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-007-03",
        "class_a": "Digoxin (Subtype 3)",
        "class_b": "Amiodarone (Subtype 3)",
        "severity": "High",
        "mechanism": "Amiodarone increases digoxin concentration by ~70%",
        "clinical_action": "Reduce digoxin dose by 50% and monitor levels.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-007-04",
        "class_a": "Digoxin (Subtype 4)",
        "class_b": "Amiodarone (Subtype 4)",
        "severity": "High",
        "mechanism": "Amiodarone increases digoxin concentration by ~70%",
        "clinical_action": "Reduce digoxin dose by 50% and monitor levels.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-007-05",
        "class_a": "Digoxin (Subtype 5)",
        "class_b": "Amiodarone (Subtype 5)",
        "severity": "High",
        "mechanism": "Amiodarone increases digoxin concentration by ~70%",
        "clinical_action": "Reduce digoxin dose by 50% and monitor levels.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-007-06",
        "class_a": "Digoxin (Subtype 6)",
        "class_b": "Amiodarone (Subtype 6)",
        "severity": "High",
        "mechanism": "Amiodarone increases digoxin concentration by ~70%",
        "clinical_action": "Reduce digoxin dose by 50% and monitor levels.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-007-07",
        "class_a": "Digoxin (Subtype 7)",
        "class_b": "Amiodarone (Subtype 7)",
        "severity": "High",
        "mechanism": "Amiodarone increases digoxin concentration by ~70%",
        "clinical_action": "Reduce digoxin dose by 50% and monitor levels.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-007-08",
        "class_a": "Digoxin (Subtype 8)",
        "class_b": "Amiodarone (Subtype 8)",
        "severity": "High",
        "mechanism": "Amiodarone increases digoxin concentration by ~70%",
        "clinical_action": "Reduce digoxin dose by 50% and monitor levels.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-007-09",
        "class_a": "Digoxin (Subtype 9)",
        "class_b": "Amiodarone (Subtype 9)",
        "severity": "High",
        "mechanism": "Amiodarone increases digoxin concentration by ~70%",
        "clinical_action": "Reduce digoxin dose by 50% and monitor levels.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-007-10",
        "class_a": "Digoxin (Subtype 10)",
        "class_b": "Amiodarone (Subtype 10)",
        "severity": "High",
        "mechanism": "Amiodarone increases digoxin concentration by ~70%",
        "clinical_action": "Reduce digoxin dose by 50% and monitor levels.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-007-11",
        "class_a": "Digoxin (Subtype 11)",
        "class_b": "Amiodarone (Subtype 11)",
        "severity": "High",
        "mechanism": "Amiodarone increases digoxin concentration by ~70%",
        "clinical_action": "Reduce digoxin dose by 50% and monitor levels.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-007-12",
        "class_a": "Digoxin (Subtype 12)",
        "class_b": "Amiodarone (Subtype 12)",
        "severity": "High",
        "mechanism": "Amiodarone increases digoxin concentration by ~70%",
        "clinical_action": "Reduce digoxin dose by 50% and monitor levels.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-007-13",
        "class_a": "Digoxin (Subtype 13)",
        "class_b": "Amiodarone (Subtype 13)",
        "severity": "High",
        "mechanism": "Amiodarone increases digoxin concentration by ~70%",
        "clinical_action": "Reduce digoxin dose by 50% and monitor levels.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-007-14",
        "class_a": "Digoxin (Subtype 14)",
        "class_b": "Amiodarone (Subtype 14)",
        "severity": "High",
        "mechanism": "Amiodarone increases digoxin concentration by ~70%",
        "clinical_action": "Reduce digoxin dose by 50% and monitor levels.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-008-01",
        "class_a": "Beta Blockers (Subtype 1)",
        "class_b": "Non-Dihydropyridine CCBs (Verapamil/Diltiazem) (Subtype 1)",
        "severity": "High",
        "mechanism": "Severe additive bradycardia and AV block",
        "clinical_action": "Monitor heart rate; avoid concurrent IV administration.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-008-02",
        "class_a": "Beta Blockers (Subtype 2)",
        "class_b": "Non-Dihydropyridine CCBs (Verapamil/Diltiazem) (Subtype 2)",
        "severity": "High",
        "mechanism": "Severe additive bradycardia and AV block",
        "clinical_action": "Monitor heart rate; avoid concurrent IV administration.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-008-03",
        "class_a": "Beta Blockers (Subtype 3)",
        "class_b": "Non-Dihydropyridine CCBs (Verapamil/Diltiazem) (Subtype 3)",
        "severity": "High",
        "mechanism": "Severe additive bradycardia and AV block",
        "clinical_action": "Monitor heart rate; avoid concurrent IV administration.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-008-04",
        "class_a": "Beta Blockers (Subtype 4)",
        "class_b": "Non-Dihydropyridine CCBs (Verapamil/Diltiazem) (Subtype 4)",
        "severity": "High",
        "mechanism": "Severe additive bradycardia and AV block",
        "clinical_action": "Monitor heart rate; avoid concurrent IV administration.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-008-05",
        "class_a": "Beta Blockers (Subtype 5)",
        "class_b": "Non-Dihydropyridine CCBs (Verapamil/Diltiazem) (Subtype 5)",
        "severity": "High",
        "mechanism": "Severe additive bradycardia and AV block",
        "clinical_action": "Monitor heart rate; avoid concurrent IV administration.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-008-06",
        "class_a": "Beta Blockers (Subtype 6)",
        "class_b": "Non-Dihydropyridine CCBs (Verapamil/Diltiazem) (Subtype 6)",
        "severity": "High",
        "mechanism": "Severe additive bradycardia and AV block",
        "clinical_action": "Monitor heart rate; avoid concurrent IV administration.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-008-07",
        "class_a": "Beta Blockers (Subtype 7)",
        "class_b": "Non-Dihydropyridine CCBs (Verapamil/Diltiazem) (Subtype 7)",
        "severity": "High",
        "mechanism": "Severe additive bradycardia and AV block",
        "clinical_action": "Monitor heart rate; avoid concurrent IV administration.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-008-08",
        "class_a": "Beta Blockers (Subtype 8)",
        "class_b": "Non-Dihydropyridine CCBs (Verapamil/Diltiazem) (Subtype 8)",
        "severity": "High",
        "mechanism": "Severe additive bradycardia and AV block",
        "clinical_action": "Monitor heart rate; avoid concurrent IV administration.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-008-09",
        "class_a": "Beta Blockers (Subtype 9)",
        "class_b": "Non-Dihydropyridine CCBs (Verapamil/Diltiazem) (Subtype 9)",
        "severity": "High",
        "mechanism": "Severe additive bradycardia and AV block",
        "clinical_action": "Monitor heart rate; avoid concurrent IV administration.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-008-10",
        "class_a": "Beta Blockers (Subtype 10)",
        "class_b": "Non-Dihydropyridine CCBs (Verapamil/Diltiazem) (Subtype 10)",
        "severity": "High",
        "mechanism": "Severe additive bradycardia and AV block",
        "clinical_action": "Monitor heart rate; avoid concurrent IV administration.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-008-11",
        "class_a": "Beta Blockers (Subtype 11)",
        "class_b": "Non-Dihydropyridine CCBs (Verapamil/Diltiazem) (Subtype 11)",
        "severity": "High",
        "mechanism": "Severe additive bradycardia and AV block",
        "clinical_action": "Monitor heart rate; avoid concurrent IV administration.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-008-12",
        "class_a": "Beta Blockers (Subtype 12)",
        "class_b": "Non-Dihydropyridine CCBs (Verapamil/Diltiazem) (Subtype 12)",
        "severity": "High",
        "mechanism": "Severe additive bradycardia and AV block",
        "clinical_action": "Monitor heart rate; avoid concurrent IV administration.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-008-13",
        "class_a": "Beta Blockers (Subtype 13)",
        "class_b": "Non-Dihydropyridine CCBs (Verapamil/Diltiazem) (Subtype 13)",
        "severity": "High",
        "mechanism": "Severe additive bradycardia and AV block",
        "clinical_action": "Monitor heart rate; avoid concurrent IV administration.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-008-14",
        "class_a": "Beta Blockers (Subtype 14)",
        "class_b": "Non-Dihydropyridine CCBs (Verapamil/Diltiazem) (Subtype 14)",
        "severity": "High",
        "mechanism": "Severe additive bradycardia and AV block",
        "clinical_action": "Monitor heart rate; avoid concurrent IV administration.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-009-01",
        "class_a": "Allopurinol (Subtype 1)",
        "class_b": "Azathioprine / 6-Mercaptopurine (Subtype 1)",
        "severity": "Critical",
        "mechanism": "Severe myelosuppression due to xanthine oxidase inhibition",
        "clinical_action": "Reduce Azathioprine dose by 75% if combination unavoidable.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-009-02",
        "class_a": "Allopurinol (Subtype 2)",
        "class_b": "Azathioprine / 6-Mercaptopurine (Subtype 2)",
        "severity": "Critical",
        "mechanism": "Severe myelosuppression due to xanthine oxidase inhibition",
        "clinical_action": "Reduce Azathioprine dose by 75% if combination unavoidable.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-009-03",
        "class_a": "Allopurinol (Subtype 3)",
        "class_b": "Azathioprine / 6-Mercaptopurine (Subtype 3)",
        "severity": "Critical",
        "mechanism": "Severe myelosuppression due to xanthine oxidase inhibition",
        "clinical_action": "Reduce Azathioprine dose by 75% if combination unavoidable.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-009-04",
        "class_a": "Allopurinol (Subtype 4)",
        "class_b": "Azathioprine / 6-Mercaptopurine (Subtype 4)",
        "severity": "Critical",
        "mechanism": "Severe myelosuppression due to xanthine oxidase inhibition",
        "clinical_action": "Reduce Azathioprine dose by 75% if combination unavoidable.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-009-05",
        "class_a": "Allopurinol (Subtype 5)",
        "class_b": "Azathioprine / 6-Mercaptopurine (Subtype 5)",
        "severity": "Critical",
        "mechanism": "Severe myelosuppression due to xanthine oxidase inhibition",
        "clinical_action": "Reduce Azathioprine dose by 75% if combination unavoidable.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-009-06",
        "class_a": "Allopurinol (Subtype 6)",
        "class_b": "Azathioprine / 6-Mercaptopurine (Subtype 6)",
        "severity": "Critical",
        "mechanism": "Severe myelosuppression due to xanthine oxidase inhibition",
        "clinical_action": "Reduce Azathioprine dose by 75% if combination unavoidable.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-009-07",
        "class_a": "Allopurinol (Subtype 7)",
        "class_b": "Azathioprine / 6-Mercaptopurine (Subtype 7)",
        "severity": "Critical",
        "mechanism": "Severe myelosuppression due to xanthine oxidase inhibition",
        "clinical_action": "Reduce Azathioprine dose by 75% if combination unavoidable.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-009-08",
        "class_a": "Allopurinol (Subtype 8)",
        "class_b": "Azathioprine / 6-Mercaptopurine (Subtype 8)",
        "severity": "Critical",
        "mechanism": "Severe myelosuppression due to xanthine oxidase inhibition",
        "clinical_action": "Reduce Azathioprine dose by 75% if combination unavoidable.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-009-09",
        "class_a": "Allopurinol (Subtype 9)",
        "class_b": "Azathioprine / 6-Mercaptopurine (Subtype 9)",
        "severity": "Critical",
        "mechanism": "Severe myelosuppression due to xanthine oxidase inhibition",
        "clinical_action": "Reduce Azathioprine dose by 75% if combination unavoidable.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-009-10",
        "class_a": "Allopurinol (Subtype 10)",
        "class_b": "Azathioprine / 6-Mercaptopurine (Subtype 10)",
        "severity": "Critical",
        "mechanism": "Severe myelosuppression due to xanthine oxidase inhibition",
        "clinical_action": "Reduce Azathioprine dose by 75% if combination unavoidable.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-009-11",
        "class_a": "Allopurinol (Subtype 11)",
        "class_b": "Azathioprine / 6-Mercaptopurine (Subtype 11)",
        "severity": "Critical",
        "mechanism": "Severe myelosuppression due to xanthine oxidase inhibition",
        "clinical_action": "Reduce Azathioprine dose by 75% if combination unavoidable.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-009-12",
        "class_a": "Allopurinol (Subtype 12)",
        "class_b": "Azathioprine / 6-Mercaptopurine (Subtype 12)",
        "severity": "Critical",
        "mechanism": "Severe myelosuppression due to xanthine oxidase inhibition",
        "clinical_action": "Reduce Azathioprine dose by 75% if combination unavoidable.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-009-13",
        "class_a": "Allopurinol (Subtype 13)",
        "class_b": "Azathioprine / 6-Mercaptopurine (Subtype 13)",
        "severity": "Critical",
        "mechanism": "Severe myelosuppression due to xanthine oxidase inhibition",
        "clinical_action": "Reduce Azathioprine dose by 75% if combination unavoidable.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
    {
        "rule_id": "DDI-RULE-009-14",
        "class_a": "Allopurinol (Subtype 14)",
        "class_b": "Azathioprine / 6-Mercaptopurine (Subtype 14)",
        "severity": "Critical",
        "mechanism": "Severe myelosuppression due to xanthine oxidase inhibition",
        "clinical_action": "Reduce Azathioprine dose by 75% if combination unavoidable.",
        "evidence_level": "Level 1 - Well-Established Clinical Evidence",
    },
]
