"""
MediCore Nexus - Revenue Cycle Management (RCM) & Claims Adjudication Rules
Automates scrub rules, modifier validations (25, 59, 76), and clearinghouse denial mitigation.
"""

from typing import Dict, List, Any

REVENUE_CYCLE_RULES: Dict[str, Dict[str, Any]] = {
    "RCM-MOD-25-V01": {
        "rule_id": "RCM-MOD-25-V01",
        "rule_title": "Significant Separately Identifiable E/M Service (Rule Engine Tier 1)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 25 required when E/M occurs on same day as minor procedure (0-10 global days).",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-25-V02": {
        "rule_id": "RCM-MOD-25-V02",
        "rule_title": "Significant Separately Identifiable E/M Service (Rule Engine Tier 2)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 25 required when E/M occurs on same day as minor procedure (0-10 global days).",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-25-V03": {
        "rule_id": "RCM-MOD-25-V03",
        "rule_title": "Significant Separately Identifiable E/M Service (Rule Engine Tier 3)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 25 required when E/M occurs on same day as minor procedure (0-10 global days).",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-25-V04": {
        "rule_id": "RCM-MOD-25-V04",
        "rule_title": "Significant Separately Identifiable E/M Service (Rule Engine Tier 4)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 25 required when E/M occurs on same day as minor procedure (0-10 global days).",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-25-V05": {
        "rule_id": "RCM-MOD-25-V05",
        "rule_title": "Significant Separately Identifiable E/M Service (Rule Engine Tier 5)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 25 required when E/M occurs on same day as minor procedure (0-10 global days).",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-25-V06": {
        "rule_id": "RCM-MOD-25-V06",
        "rule_title": "Significant Separately Identifiable E/M Service (Rule Engine Tier 6)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 25 required when E/M occurs on same day as minor procedure (0-10 global days).",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-25-V07": {
        "rule_id": "RCM-MOD-25-V07",
        "rule_title": "Significant Separately Identifiable E/M Service (Rule Engine Tier 7)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 25 required when E/M occurs on same day as minor procedure (0-10 global days).",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-25-V08": {
        "rule_id": "RCM-MOD-25-V08",
        "rule_title": "Significant Separately Identifiable E/M Service (Rule Engine Tier 8)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 25 required when E/M occurs on same day as minor procedure (0-10 global days).",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-25-V09": {
        "rule_id": "RCM-MOD-25-V09",
        "rule_title": "Significant Separately Identifiable E/M Service (Rule Engine Tier 9)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 25 required when E/M occurs on same day as minor procedure (0-10 global days).",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-25-V10": {
        "rule_id": "RCM-MOD-25-V10",
        "rule_title": "Significant Separately Identifiable E/M Service (Rule Engine Tier 10)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 25 required when E/M occurs on same day as minor procedure (0-10 global days).",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-25-V11": {
        "rule_id": "RCM-MOD-25-V11",
        "rule_title": "Significant Separately Identifiable E/M Service (Rule Engine Tier 11)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 25 required when E/M occurs on same day as minor procedure (0-10 global days).",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-25-V12": {
        "rule_id": "RCM-MOD-25-V12",
        "rule_title": "Significant Separately Identifiable E/M Service (Rule Engine Tier 12)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 25 required when E/M occurs on same day as minor procedure (0-10 global days).",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-25-V13": {
        "rule_id": "RCM-MOD-25-V13",
        "rule_title": "Significant Separately Identifiable E/M Service (Rule Engine Tier 13)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 25 required when E/M occurs on same day as minor procedure (0-10 global days).",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-25-V14": {
        "rule_id": "RCM-MOD-25-V14",
        "rule_title": "Significant Separately Identifiable E/M Service (Rule Engine Tier 14)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 25 required when E/M occurs on same day as minor procedure (0-10 global days).",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-25-V15": {
        "rule_id": "RCM-MOD-25-V15",
        "rule_title": "Significant Separately Identifiable E/M Service (Rule Engine Tier 15)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 25 required when E/M occurs on same day as minor procedure (0-10 global days).",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-25-V16": {
        "rule_id": "RCM-MOD-25-V16",
        "rule_title": "Significant Separately Identifiable E/M Service (Rule Engine Tier 16)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 25 required when E/M occurs on same day as minor procedure (0-10 global days).",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-25-V17": {
        "rule_id": "RCM-MOD-25-V17",
        "rule_title": "Significant Separately Identifiable E/M Service (Rule Engine Tier 17)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 25 required when E/M occurs on same day as minor procedure (0-10 global days).",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-25-V18": {
        "rule_id": "RCM-MOD-25-V18",
        "rule_title": "Significant Separately Identifiable E/M Service (Rule Engine Tier 18)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 25 required when E/M occurs on same day as minor procedure (0-10 global days).",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-25-V19": {
        "rule_id": "RCM-MOD-25-V19",
        "rule_title": "Significant Separately Identifiable E/M Service (Rule Engine Tier 19)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 25 required when E/M occurs on same day as minor procedure (0-10 global days).",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-59-V01": {
        "rule_id": "RCM-MOD-59-V01",
        "rule_title": "Distinct Procedural Service (Rule Engine Tier 1)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 59 used to unbundle procedures that are normally bundled under NCCI edits when performed at separate anatomical sites.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-59-V02": {
        "rule_id": "RCM-MOD-59-V02",
        "rule_title": "Distinct Procedural Service (Rule Engine Tier 2)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 59 used to unbundle procedures that are normally bundled under NCCI edits when performed at separate anatomical sites.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-59-V03": {
        "rule_id": "RCM-MOD-59-V03",
        "rule_title": "Distinct Procedural Service (Rule Engine Tier 3)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 59 used to unbundle procedures that are normally bundled under NCCI edits when performed at separate anatomical sites.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-59-V04": {
        "rule_id": "RCM-MOD-59-V04",
        "rule_title": "Distinct Procedural Service (Rule Engine Tier 4)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 59 used to unbundle procedures that are normally bundled under NCCI edits when performed at separate anatomical sites.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-59-V05": {
        "rule_id": "RCM-MOD-59-V05",
        "rule_title": "Distinct Procedural Service (Rule Engine Tier 5)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 59 used to unbundle procedures that are normally bundled under NCCI edits when performed at separate anatomical sites.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-59-V06": {
        "rule_id": "RCM-MOD-59-V06",
        "rule_title": "Distinct Procedural Service (Rule Engine Tier 6)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 59 used to unbundle procedures that are normally bundled under NCCI edits when performed at separate anatomical sites.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-59-V07": {
        "rule_id": "RCM-MOD-59-V07",
        "rule_title": "Distinct Procedural Service (Rule Engine Tier 7)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 59 used to unbundle procedures that are normally bundled under NCCI edits when performed at separate anatomical sites.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-59-V08": {
        "rule_id": "RCM-MOD-59-V08",
        "rule_title": "Distinct Procedural Service (Rule Engine Tier 8)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 59 used to unbundle procedures that are normally bundled under NCCI edits when performed at separate anatomical sites.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-59-V09": {
        "rule_id": "RCM-MOD-59-V09",
        "rule_title": "Distinct Procedural Service (Rule Engine Tier 9)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 59 used to unbundle procedures that are normally bundled under NCCI edits when performed at separate anatomical sites.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-59-V10": {
        "rule_id": "RCM-MOD-59-V10",
        "rule_title": "Distinct Procedural Service (Rule Engine Tier 10)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 59 used to unbundle procedures that are normally bundled under NCCI edits when performed at separate anatomical sites.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-59-V11": {
        "rule_id": "RCM-MOD-59-V11",
        "rule_title": "Distinct Procedural Service (Rule Engine Tier 11)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 59 used to unbundle procedures that are normally bundled under NCCI edits when performed at separate anatomical sites.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-59-V12": {
        "rule_id": "RCM-MOD-59-V12",
        "rule_title": "Distinct Procedural Service (Rule Engine Tier 12)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 59 used to unbundle procedures that are normally bundled under NCCI edits when performed at separate anatomical sites.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-59-V13": {
        "rule_id": "RCM-MOD-59-V13",
        "rule_title": "Distinct Procedural Service (Rule Engine Tier 13)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 59 used to unbundle procedures that are normally bundled under NCCI edits when performed at separate anatomical sites.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-59-V14": {
        "rule_id": "RCM-MOD-59-V14",
        "rule_title": "Distinct Procedural Service (Rule Engine Tier 14)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 59 used to unbundle procedures that are normally bundled under NCCI edits when performed at separate anatomical sites.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-59-V15": {
        "rule_id": "RCM-MOD-59-V15",
        "rule_title": "Distinct Procedural Service (Rule Engine Tier 15)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 59 used to unbundle procedures that are normally bundled under NCCI edits when performed at separate anatomical sites.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-59-V16": {
        "rule_id": "RCM-MOD-59-V16",
        "rule_title": "Distinct Procedural Service (Rule Engine Tier 16)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 59 used to unbundle procedures that are normally bundled under NCCI edits when performed at separate anatomical sites.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-59-V17": {
        "rule_id": "RCM-MOD-59-V17",
        "rule_title": "Distinct Procedural Service (Rule Engine Tier 17)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 59 used to unbundle procedures that are normally bundled under NCCI edits when performed at separate anatomical sites.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-59-V18": {
        "rule_id": "RCM-MOD-59-V18",
        "rule_title": "Distinct Procedural Service (Rule Engine Tier 18)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 59 used to unbundle procedures that are normally bundled under NCCI edits when performed at separate anatomical sites.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MOD-59-V19": {
        "rule_id": "RCM-MOD-59-V19",
        "rule_title": "Distinct Procedural Service (Rule Engine Tier 19)",
        "category": "Billing Claim Scrubber",
        "rule_logic": "Modifier 59 used to unbundle procedures that are normally bundled under NCCI edits when performed at separate anatomical sites.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-NCCI-COL1-COL2-V01": {
        "rule_id": "RCM-NCCI-COL1-COL2-V01",
        "rule_title": "National Correct Coding Initiative (NCCI) PTP Edit (Rule Engine Tier 1)",
        "category": "Claims Clearinghouse",
        "rule_logic": "Column 1 and Column 2 code combinations cannot be billed together without qualifying modifier.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-NCCI-COL1-COL2-V02": {
        "rule_id": "RCM-NCCI-COL1-COL2-V02",
        "rule_title": "National Correct Coding Initiative (NCCI) PTP Edit (Rule Engine Tier 2)",
        "category": "Claims Clearinghouse",
        "rule_logic": "Column 1 and Column 2 code combinations cannot be billed together without qualifying modifier.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-NCCI-COL1-COL2-V03": {
        "rule_id": "RCM-NCCI-COL1-COL2-V03",
        "rule_title": "National Correct Coding Initiative (NCCI) PTP Edit (Rule Engine Tier 3)",
        "category": "Claims Clearinghouse",
        "rule_logic": "Column 1 and Column 2 code combinations cannot be billed together without qualifying modifier.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-NCCI-COL1-COL2-V04": {
        "rule_id": "RCM-NCCI-COL1-COL2-V04",
        "rule_title": "National Correct Coding Initiative (NCCI) PTP Edit (Rule Engine Tier 4)",
        "category": "Claims Clearinghouse",
        "rule_logic": "Column 1 and Column 2 code combinations cannot be billed together without qualifying modifier.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-NCCI-COL1-COL2-V05": {
        "rule_id": "RCM-NCCI-COL1-COL2-V05",
        "rule_title": "National Correct Coding Initiative (NCCI) PTP Edit (Rule Engine Tier 5)",
        "category": "Claims Clearinghouse",
        "rule_logic": "Column 1 and Column 2 code combinations cannot be billed together without qualifying modifier.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-NCCI-COL1-COL2-V06": {
        "rule_id": "RCM-NCCI-COL1-COL2-V06",
        "rule_title": "National Correct Coding Initiative (NCCI) PTP Edit (Rule Engine Tier 6)",
        "category": "Claims Clearinghouse",
        "rule_logic": "Column 1 and Column 2 code combinations cannot be billed together without qualifying modifier.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-NCCI-COL1-COL2-V07": {
        "rule_id": "RCM-NCCI-COL1-COL2-V07",
        "rule_title": "National Correct Coding Initiative (NCCI) PTP Edit (Rule Engine Tier 7)",
        "category": "Claims Clearinghouse",
        "rule_logic": "Column 1 and Column 2 code combinations cannot be billed together without qualifying modifier.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-NCCI-COL1-COL2-V08": {
        "rule_id": "RCM-NCCI-COL1-COL2-V08",
        "rule_title": "National Correct Coding Initiative (NCCI) PTP Edit (Rule Engine Tier 8)",
        "category": "Claims Clearinghouse",
        "rule_logic": "Column 1 and Column 2 code combinations cannot be billed together without qualifying modifier.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-NCCI-COL1-COL2-V09": {
        "rule_id": "RCM-NCCI-COL1-COL2-V09",
        "rule_title": "National Correct Coding Initiative (NCCI) PTP Edit (Rule Engine Tier 9)",
        "category": "Claims Clearinghouse",
        "rule_logic": "Column 1 and Column 2 code combinations cannot be billed together without qualifying modifier.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-NCCI-COL1-COL2-V10": {
        "rule_id": "RCM-NCCI-COL1-COL2-V10",
        "rule_title": "National Correct Coding Initiative (NCCI) PTP Edit (Rule Engine Tier 10)",
        "category": "Claims Clearinghouse",
        "rule_logic": "Column 1 and Column 2 code combinations cannot be billed together without qualifying modifier.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-NCCI-COL1-COL2-V11": {
        "rule_id": "RCM-NCCI-COL1-COL2-V11",
        "rule_title": "National Correct Coding Initiative (NCCI) PTP Edit (Rule Engine Tier 11)",
        "category": "Claims Clearinghouse",
        "rule_logic": "Column 1 and Column 2 code combinations cannot be billed together without qualifying modifier.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-NCCI-COL1-COL2-V12": {
        "rule_id": "RCM-NCCI-COL1-COL2-V12",
        "rule_title": "National Correct Coding Initiative (NCCI) PTP Edit (Rule Engine Tier 12)",
        "category": "Claims Clearinghouse",
        "rule_logic": "Column 1 and Column 2 code combinations cannot be billed together without qualifying modifier.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-NCCI-COL1-COL2-V13": {
        "rule_id": "RCM-NCCI-COL1-COL2-V13",
        "rule_title": "National Correct Coding Initiative (NCCI) PTP Edit (Rule Engine Tier 13)",
        "category": "Claims Clearinghouse",
        "rule_logic": "Column 1 and Column 2 code combinations cannot be billed together without qualifying modifier.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-NCCI-COL1-COL2-V14": {
        "rule_id": "RCM-NCCI-COL1-COL2-V14",
        "rule_title": "National Correct Coding Initiative (NCCI) PTP Edit (Rule Engine Tier 14)",
        "category": "Claims Clearinghouse",
        "rule_logic": "Column 1 and Column 2 code combinations cannot be billed together without qualifying modifier.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-NCCI-COL1-COL2-V15": {
        "rule_id": "RCM-NCCI-COL1-COL2-V15",
        "rule_title": "National Correct Coding Initiative (NCCI) PTP Edit (Rule Engine Tier 15)",
        "category": "Claims Clearinghouse",
        "rule_logic": "Column 1 and Column 2 code combinations cannot be billed together without qualifying modifier.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-NCCI-COL1-COL2-V16": {
        "rule_id": "RCM-NCCI-COL1-COL2-V16",
        "rule_title": "National Correct Coding Initiative (NCCI) PTP Edit (Rule Engine Tier 16)",
        "category": "Claims Clearinghouse",
        "rule_logic": "Column 1 and Column 2 code combinations cannot be billed together without qualifying modifier.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-NCCI-COL1-COL2-V17": {
        "rule_id": "RCM-NCCI-COL1-COL2-V17",
        "rule_title": "National Correct Coding Initiative (NCCI) PTP Edit (Rule Engine Tier 17)",
        "category": "Claims Clearinghouse",
        "rule_logic": "Column 1 and Column 2 code combinations cannot be billed together without qualifying modifier.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-NCCI-COL1-COL2-V18": {
        "rule_id": "RCM-NCCI-COL1-COL2-V18",
        "rule_title": "National Correct Coding Initiative (NCCI) PTP Edit (Rule Engine Tier 18)",
        "category": "Claims Clearinghouse",
        "rule_logic": "Column 1 and Column 2 code combinations cannot be billed together without qualifying modifier.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-NCCI-COL1-COL2-V19": {
        "rule_id": "RCM-NCCI-COL1-COL2-V19",
        "rule_title": "National Correct Coding Initiative (NCCI) PTP Edit (Rule Engine Tier 19)",
        "category": "Claims Clearinghouse",
        "rule_logic": "Column 1 and Column 2 code combinations cannot be billed together without qualifying modifier.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MED-NECESSITY-V01": {
        "rule_id": "RCM-MED-NECESSITY-V01",
        "rule_title": "LCD / NCD Medical Necessity Validation (Rule Engine Tier 1)",
        "category": "Pre-Authorization Engine",
        "rule_logic": "Primary diagnosis ICD-10 code must match payer-approved coverage policy for high-cost diagnostic testing.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MED-NECESSITY-V02": {
        "rule_id": "RCM-MED-NECESSITY-V02",
        "rule_title": "LCD / NCD Medical Necessity Validation (Rule Engine Tier 2)",
        "category": "Pre-Authorization Engine",
        "rule_logic": "Primary diagnosis ICD-10 code must match payer-approved coverage policy for high-cost diagnostic testing.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MED-NECESSITY-V03": {
        "rule_id": "RCM-MED-NECESSITY-V03",
        "rule_title": "LCD / NCD Medical Necessity Validation (Rule Engine Tier 3)",
        "category": "Pre-Authorization Engine",
        "rule_logic": "Primary diagnosis ICD-10 code must match payer-approved coverage policy for high-cost diagnostic testing.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MED-NECESSITY-V04": {
        "rule_id": "RCM-MED-NECESSITY-V04",
        "rule_title": "LCD / NCD Medical Necessity Validation (Rule Engine Tier 4)",
        "category": "Pre-Authorization Engine",
        "rule_logic": "Primary diagnosis ICD-10 code must match payer-approved coverage policy for high-cost diagnostic testing.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MED-NECESSITY-V05": {
        "rule_id": "RCM-MED-NECESSITY-V05",
        "rule_title": "LCD / NCD Medical Necessity Validation (Rule Engine Tier 5)",
        "category": "Pre-Authorization Engine",
        "rule_logic": "Primary diagnosis ICD-10 code must match payer-approved coverage policy for high-cost diagnostic testing.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MED-NECESSITY-V06": {
        "rule_id": "RCM-MED-NECESSITY-V06",
        "rule_title": "LCD / NCD Medical Necessity Validation (Rule Engine Tier 6)",
        "category": "Pre-Authorization Engine",
        "rule_logic": "Primary diagnosis ICD-10 code must match payer-approved coverage policy for high-cost diagnostic testing.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MED-NECESSITY-V07": {
        "rule_id": "RCM-MED-NECESSITY-V07",
        "rule_title": "LCD / NCD Medical Necessity Validation (Rule Engine Tier 7)",
        "category": "Pre-Authorization Engine",
        "rule_logic": "Primary diagnosis ICD-10 code must match payer-approved coverage policy for high-cost diagnostic testing.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MED-NECESSITY-V08": {
        "rule_id": "RCM-MED-NECESSITY-V08",
        "rule_title": "LCD / NCD Medical Necessity Validation (Rule Engine Tier 8)",
        "category": "Pre-Authorization Engine",
        "rule_logic": "Primary diagnosis ICD-10 code must match payer-approved coverage policy for high-cost diagnostic testing.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MED-NECESSITY-V09": {
        "rule_id": "RCM-MED-NECESSITY-V09",
        "rule_title": "LCD / NCD Medical Necessity Validation (Rule Engine Tier 9)",
        "category": "Pre-Authorization Engine",
        "rule_logic": "Primary diagnosis ICD-10 code must match payer-approved coverage policy for high-cost diagnostic testing.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MED-NECESSITY-V10": {
        "rule_id": "RCM-MED-NECESSITY-V10",
        "rule_title": "LCD / NCD Medical Necessity Validation (Rule Engine Tier 10)",
        "category": "Pre-Authorization Engine",
        "rule_logic": "Primary diagnosis ICD-10 code must match payer-approved coverage policy for high-cost diagnostic testing.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MED-NECESSITY-V11": {
        "rule_id": "RCM-MED-NECESSITY-V11",
        "rule_title": "LCD / NCD Medical Necessity Validation (Rule Engine Tier 11)",
        "category": "Pre-Authorization Engine",
        "rule_logic": "Primary diagnosis ICD-10 code must match payer-approved coverage policy for high-cost diagnostic testing.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MED-NECESSITY-V12": {
        "rule_id": "RCM-MED-NECESSITY-V12",
        "rule_title": "LCD / NCD Medical Necessity Validation (Rule Engine Tier 12)",
        "category": "Pre-Authorization Engine",
        "rule_logic": "Primary diagnosis ICD-10 code must match payer-approved coverage policy for high-cost diagnostic testing.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MED-NECESSITY-V13": {
        "rule_id": "RCM-MED-NECESSITY-V13",
        "rule_title": "LCD / NCD Medical Necessity Validation (Rule Engine Tier 13)",
        "category": "Pre-Authorization Engine",
        "rule_logic": "Primary diagnosis ICD-10 code must match payer-approved coverage policy for high-cost diagnostic testing.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MED-NECESSITY-V14": {
        "rule_id": "RCM-MED-NECESSITY-V14",
        "rule_title": "LCD / NCD Medical Necessity Validation (Rule Engine Tier 14)",
        "category": "Pre-Authorization Engine",
        "rule_logic": "Primary diagnosis ICD-10 code must match payer-approved coverage policy for high-cost diagnostic testing.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MED-NECESSITY-V15": {
        "rule_id": "RCM-MED-NECESSITY-V15",
        "rule_title": "LCD / NCD Medical Necessity Validation (Rule Engine Tier 15)",
        "category": "Pre-Authorization Engine",
        "rule_logic": "Primary diagnosis ICD-10 code must match payer-approved coverage policy for high-cost diagnostic testing.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MED-NECESSITY-V16": {
        "rule_id": "RCM-MED-NECESSITY-V16",
        "rule_title": "LCD / NCD Medical Necessity Validation (Rule Engine Tier 16)",
        "category": "Pre-Authorization Engine",
        "rule_logic": "Primary diagnosis ICD-10 code must match payer-approved coverage policy for high-cost diagnostic testing.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MED-NECESSITY-V17": {
        "rule_id": "RCM-MED-NECESSITY-V17",
        "rule_title": "LCD / NCD Medical Necessity Validation (Rule Engine Tier 17)",
        "category": "Pre-Authorization Engine",
        "rule_logic": "Primary diagnosis ICD-10 code must match payer-approved coverage policy for high-cost diagnostic testing.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MED-NECESSITY-V18": {
        "rule_id": "RCM-MED-NECESSITY-V18",
        "rule_title": "LCD / NCD Medical Necessity Validation (Rule Engine Tier 18)",
        "category": "Pre-Authorization Engine",
        "rule_logic": "Primary diagnosis ICD-10 code must match payer-approved coverage policy for high-cost diagnostic testing.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-MED-NECESSITY-V19": {
        "rule_id": "RCM-MED-NECESSITY-V19",
        "rule_title": "LCD / NCD Medical Necessity Validation (Rule Engine Tier 19)",
        "category": "Pre-Authorization Engine",
        "rule_logic": "Primary diagnosis ICD-10 code must match payer-approved coverage policy for high-cost diagnostic testing.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-TIMELY-FILING-V01": {
        "rule_id": "RCM-TIMELY-FILING-V01",
        "rule_title": "Timely Filing Limits Monitor (Rule Engine Tier 1)",
        "category": "Revenue Assurance",
        "rule_logic": "Commercial claims must be filed within 90 days of service date; Medicare within 365 days.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-TIMELY-FILING-V02": {
        "rule_id": "RCM-TIMELY-FILING-V02",
        "rule_title": "Timely Filing Limits Monitor (Rule Engine Tier 2)",
        "category": "Revenue Assurance",
        "rule_logic": "Commercial claims must be filed within 90 days of service date; Medicare within 365 days.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-TIMELY-FILING-V03": {
        "rule_id": "RCM-TIMELY-FILING-V03",
        "rule_title": "Timely Filing Limits Monitor (Rule Engine Tier 3)",
        "category": "Revenue Assurance",
        "rule_logic": "Commercial claims must be filed within 90 days of service date; Medicare within 365 days.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-TIMELY-FILING-V04": {
        "rule_id": "RCM-TIMELY-FILING-V04",
        "rule_title": "Timely Filing Limits Monitor (Rule Engine Tier 4)",
        "category": "Revenue Assurance",
        "rule_logic": "Commercial claims must be filed within 90 days of service date; Medicare within 365 days.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-TIMELY-FILING-V05": {
        "rule_id": "RCM-TIMELY-FILING-V05",
        "rule_title": "Timely Filing Limits Monitor (Rule Engine Tier 5)",
        "category": "Revenue Assurance",
        "rule_logic": "Commercial claims must be filed within 90 days of service date; Medicare within 365 days.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-TIMELY-FILING-V06": {
        "rule_id": "RCM-TIMELY-FILING-V06",
        "rule_title": "Timely Filing Limits Monitor (Rule Engine Tier 6)",
        "category": "Revenue Assurance",
        "rule_logic": "Commercial claims must be filed within 90 days of service date; Medicare within 365 days.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-TIMELY-FILING-V07": {
        "rule_id": "RCM-TIMELY-FILING-V07",
        "rule_title": "Timely Filing Limits Monitor (Rule Engine Tier 7)",
        "category": "Revenue Assurance",
        "rule_logic": "Commercial claims must be filed within 90 days of service date; Medicare within 365 days.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-TIMELY-FILING-V08": {
        "rule_id": "RCM-TIMELY-FILING-V08",
        "rule_title": "Timely Filing Limits Monitor (Rule Engine Tier 8)",
        "category": "Revenue Assurance",
        "rule_logic": "Commercial claims must be filed within 90 days of service date; Medicare within 365 days.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-TIMELY-FILING-V09": {
        "rule_id": "RCM-TIMELY-FILING-V09",
        "rule_title": "Timely Filing Limits Monitor (Rule Engine Tier 9)",
        "category": "Revenue Assurance",
        "rule_logic": "Commercial claims must be filed within 90 days of service date; Medicare within 365 days.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-TIMELY-FILING-V10": {
        "rule_id": "RCM-TIMELY-FILING-V10",
        "rule_title": "Timely Filing Limits Monitor (Rule Engine Tier 10)",
        "category": "Revenue Assurance",
        "rule_logic": "Commercial claims must be filed within 90 days of service date; Medicare within 365 days.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-TIMELY-FILING-V11": {
        "rule_id": "RCM-TIMELY-FILING-V11",
        "rule_title": "Timely Filing Limits Monitor (Rule Engine Tier 11)",
        "category": "Revenue Assurance",
        "rule_logic": "Commercial claims must be filed within 90 days of service date; Medicare within 365 days.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-TIMELY-FILING-V12": {
        "rule_id": "RCM-TIMELY-FILING-V12",
        "rule_title": "Timely Filing Limits Monitor (Rule Engine Tier 12)",
        "category": "Revenue Assurance",
        "rule_logic": "Commercial claims must be filed within 90 days of service date; Medicare within 365 days.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-TIMELY-FILING-V13": {
        "rule_id": "RCM-TIMELY-FILING-V13",
        "rule_title": "Timely Filing Limits Monitor (Rule Engine Tier 13)",
        "category": "Revenue Assurance",
        "rule_logic": "Commercial claims must be filed within 90 days of service date; Medicare within 365 days.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-TIMELY-FILING-V14": {
        "rule_id": "RCM-TIMELY-FILING-V14",
        "rule_title": "Timely Filing Limits Monitor (Rule Engine Tier 14)",
        "category": "Revenue Assurance",
        "rule_logic": "Commercial claims must be filed within 90 days of service date; Medicare within 365 days.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-TIMELY-FILING-V15": {
        "rule_id": "RCM-TIMELY-FILING-V15",
        "rule_title": "Timely Filing Limits Monitor (Rule Engine Tier 15)",
        "category": "Revenue Assurance",
        "rule_logic": "Commercial claims must be filed within 90 days of service date; Medicare within 365 days.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-TIMELY-FILING-V16": {
        "rule_id": "RCM-TIMELY-FILING-V16",
        "rule_title": "Timely Filing Limits Monitor (Rule Engine Tier 16)",
        "category": "Revenue Assurance",
        "rule_logic": "Commercial claims must be filed within 90 days of service date; Medicare within 365 days.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-TIMELY-FILING-V17": {
        "rule_id": "RCM-TIMELY-FILING-V17",
        "rule_title": "Timely Filing Limits Monitor (Rule Engine Tier 17)",
        "category": "Revenue Assurance",
        "rule_logic": "Commercial claims must be filed within 90 days of service date; Medicare within 365 days.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-TIMELY-FILING-V18": {
        "rule_id": "RCM-TIMELY-FILING-V18",
        "rule_title": "Timely Filing Limits Monitor (Rule Engine Tier 18)",
        "category": "Revenue Assurance",
        "rule_logic": "Commercial claims must be filed within 90 days of service date; Medicare within 365 days.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-TIMELY-FILING-V19": {
        "rule_id": "RCM-TIMELY-FILING-V19",
        "rule_title": "Timely Filing Limits Monitor (Rule Engine Tier 19)",
        "category": "Revenue Assurance",
        "rule_logic": "Commercial claims must be filed within 90 days of service date; Medicare within 365 days.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-COB-RULES-V01": {
        "rule_id": "RCM-COB-RULES-V01",
        "rule_title": "Coordination of Benefits (COB) Primary vs Secondary (Rule Engine Tier 1)",
        "category": "Payer Clearinghouse",
        "rule_logic": "Birthday rule applied for dependent children; Medicare secondary payer questionnaire (MSPQ) verification.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-COB-RULES-V02": {
        "rule_id": "RCM-COB-RULES-V02",
        "rule_title": "Coordination of Benefits (COB) Primary vs Secondary (Rule Engine Tier 2)",
        "category": "Payer Clearinghouse",
        "rule_logic": "Birthday rule applied for dependent children; Medicare secondary payer questionnaire (MSPQ) verification.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-COB-RULES-V03": {
        "rule_id": "RCM-COB-RULES-V03",
        "rule_title": "Coordination of Benefits (COB) Primary vs Secondary (Rule Engine Tier 3)",
        "category": "Payer Clearinghouse",
        "rule_logic": "Birthday rule applied for dependent children; Medicare secondary payer questionnaire (MSPQ) verification.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-COB-RULES-V04": {
        "rule_id": "RCM-COB-RULES-V04",
        "rule_title": "Coordination of Benefits (COB) Primary vs Secondary (Rule Engine Tier 4)",
        "category": "Payer Clearinghouse",
        "rule_logic": "Birthday rule applied for dependent children; Medicare secondary payer questionnaire (MSPQ) verification.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-COB-RULES-V05": {
        "rule_id": "RCM-COB-RULES-V05",
        "rule_title": "Coordination of Benefits (COB) Primary vs Secondary (Rule Engine Tier 5)",
        "category": "Payer Clearinghouse",
        "rule_logic": "Birthday rule applied for dependent children; Medicare secondary payer questionnaire (MSPQ) verification.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-COB-RULES-V06": {
        "rule_id": "RCM-COB-RULES-V06",
        "rule_title": "Coordination of Benefits (COB) Primary vs Secondary (Rule Engine Tier 6)",
        "category": "Payer Clearinghouse",
        "rule_logic": "Birthday rule applied for dependent children; Medicare secondary payer questionnaire (MSPQ) verification.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-COB-RULES-V07": {
        "rule_id": "RCM-COB-RULES-V07",
        "rule_title": "Coordination of Benefits (COB) Primary vs Secondary (Rule Engine Tier 7)",
        "category": "Payer Clearinghouse",
        "rule_logic": "Birthday rule applied for dependent children; Medicare secondary payer questionnaire (MSPQ) verification.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-COB-RULES-V08": {
        "rule_id": "RCM-COB-RULES-V08",
        "rule_title": "Coordination of Benefits (COB) Primary vs Secondary (Rule Engine Tier 8)",
        "category": "Payer Clearinghouse",
        "rule_logic": "Birthday rule applied for dependent children; Medicare secondary payer questionnaire (MSPQ) verification.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-COB-RULES-V09": {
        "rule_id": "RCM-COB-RULES-V09",
        "rule_title": "Coordination of Benefits (COB) Primary vs Secondary (Rule Engine Tier 9)",
        "category": "Payer Clearinghouse",
        "rule_logic": "Birthday rule applied for dependent children; Medicare secondary payer questionnaire (MSPQ) verification.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-COB-RULES-V10": {
        "rule_id": "RCM-COB-RULES-V10",
        "rule_title": "Coordination of Benefits (COB) Primary vs Secondary (Rule Engine Tier 10)",
        "category": "Payer Clearinghouse",
        "rule_logic": "Birthday rule applied for dependent children; Medicare secondary payer questionnaire (MSPQ) verification.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-COB-RULES-V11": {
        "rule_id": "RCM-COB-RULES-V11",
        "rule_title": "Coordination of Benefits (COB) Primary vs Secondary (Rule Engine Tier 11)",
        "category": "Payer Clearinghouse",
        "rule_logic": "Birthday rule applied for dependent children; Medicare secondary payer questionnaire (MSPQ) verification.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-COB-RULES-V12": {
        "rule_id": "RCM-COB-RULES-V12",
        "rule_title": "Coordination of Benefits (COB) Primary vs Secondary (Rule Engine Tier 12)",
        "category": "Payer Clearinghouse",
        "rule_logic": "Birthday rule applied for dependent children; Medicare secondary payer questionnaire (MSPQ) verification.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-COB-RULES-V13": {
        "rule_id": "RCM-COB-RULES-V13",
        "rule_title": "Coordination of Benefits (COB) Primary vs Secondary (Rule Engine Tier 13)",
        "category": "Payer Clearinghouse",
        "rule_logic": "Birthday rule applied for dependent children; Medicare secondary payer questionnaire (MSPQ) verification.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-COB-RULES-V14": {
        "rule_id": "RCM-COB-RULES-V14",
        "rule_title": "Coordination of Benefits (COB) Primary vs Secondary (Rule Engine Tier 14)",
        "category": "Payer Clearinghouse",
        "rule_logic": "Birthday rule applied for dependent children; Medicare secondary payer questionnaire (MSPQ) verification.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-COB-RULES-V15": {
        "rule_id": "RCM-COB-RULES-V15",
        "rule_title": "Coordination of Benefits (COB) Primary vs Secondary (Rule Engine Tier 15)",
        "category": "Payer Clearinghouse",
        "rule_logic": "Birthday rule applied for dependent children; Medicare secondary payer questionnaire (MSPQ) verification.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-COB-RULES-V16": {
        "rule_id": "RCM-COB-RULES-V16",
        "rule_title": "Coordination of Benefits (COB) Primary vs Secondary (Rule Engine Tier 16)",
        "category": "Payer Clearinghouse",
        "rule_logic": "Birthday rule applied for dependent children; Medicare secondary payer questionnaire (MSPQ) verification.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-COB-RULES-V17": {
        "rule_id": "RCM-COB-RULES-V17",
        "rule_title": "Coordination of Benefits (COB) Primary vs Secondary (Rule Engine Tier 17)",
        "category": "Payer Clearinghouse",
        "rule_logic": "Birthday rule applied for dependent children; Medicare secondary payer questionnaire (MSPQ) verification.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-COB-RULES-V18": {
        "rule_id": "RCM-COB-RULES-V18",
        "rule_title": "Coordination of Benefits (COB) Primary vs Secondary (Rule Engine Tier 18)",
        "category": "Payer Clearinghouse",
        "rule_logic": "Birthday rule applied for dependent children; Medicare secondary payer questionnaire (MSPQ) verification.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
    "RCM-COB-RULES-V19": {
        "rule_id": "RCM-COB-RULES-V19",
        "rule_title": "Coordination of Benefits (COB) Primary vs Secondary (Rule Engine Tier 19)",
        "category": "Payer Clearinghouse",
        "rule_logic": "Birthday rule applied for dependent children; Medicare secondary payer questionnaire (MSPQ) verification.",
        "auto_correction_enabled": True,
        "prevent_claim_denial_risk_pct": 98.4,
        "affected_payers": ["Medicare Part B", "Blue Cross Blue Shield", "Aetna", "UnitedHealthcare", "Cigna"],
    },
}
