"""
MediCore Nexus - IoT Pharmaceutical Cold-Chain & Vaccine Monitoring
Continuous telemetry monitoring for temperature-sensitive biologics, insulins, and vaccines (2°C to 8°C).
"""

from typing import Dict, List, Any

IOT_COLD_CHAIN_REFRIGERATORS: Dict[str, Dict[str, Any]] = {
    "CC-FRIDGE-01-U01": {
        "unit_id": "CC-FRIDGE-01-U01",
        "unit_name": "Central Pharmacy Main Biologics Unit (Sensor Node 1)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.25,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Insulins, Monoclonal Antibodies, Erythropoietin",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-01-U02": {
        "unit_id": "CC-FRIDGE-01-U02",
        "unit_name": "Central Pharmacy Main Biologics Unit (Sensor Node 2)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.30,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Insulins, Monoclonal Antibodies, Erythropoietin",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-01-U03": {
        "unit_id": "CC-FRIDGE-01-U03",
        "unit_name": "Central Pharmacy Main Biologics Unit (Sensor Node 3)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.35,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Insulins, Monoclonal Antibodies, Erythropoietin",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-01-U04": {
        "unit_id": "CC-FRIDGE-01-U04",
        "unit_name": "Central Pharmacy Main Biologics Unit (Sensor Node 4)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.40,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Insulins, Monoclonal Antibodies, Erythropoietin",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-01-U05": {
        "unit_id": "CC-FRIDGE-01-U05",
        "unit_name": "Central Pharmacy Main Biologics Unit (Sensor Node 5)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.45,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Insulins, Monoclonal Antibodies, Erythropoietin",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-01-U06": {
        "unit_id": "CC-FRIDGE-01-U06",
        "unit_name": "Central Pharmacy Main Biologics Unit (Sensor Node 6)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.50,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Insulins, Monoclonal Antibodies, Erythropoietin",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-01-U07": {
        "unit_id": "CC-FRIDGE-01-U07",
        "unit_name": "Central Pharmacy Main Biologics Unit (Sensor Node 7)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.55,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Insulins, Monoclonal Antibodies, Erythropoietin",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-01-U08": {
        "unit_id": "CC-FRIDGE-01-U08",
        "unit_name": "Central Pharmacy Main Biologics Unit (Sensor Node 8)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.60,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Insulins, Monoclonal Antibodies, Erythropoietin",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-01-U09": {
        "unit_id": "CC-FRIDGE-01-U09",
        "unit_name": "Central Pharmacy Main Biologics Unit (Sensor Node 9)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.65,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Insulins, Monoclonal Antibodies, Erythropoietin",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-01-U10": {
        "unit_id": "CC-FRIDGE-01-U10",
        "unit_name": "Central Pharmacy Main Biologics Unit (Sensor Node 10)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.70,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Insulins, Monoclonal Antibodies, Erythropoietin",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-01-U11": {
        "unit_id": "CC-FRIDGE-01-U11",
        "unit_name": "Central Pharmacy Main Biologics Unit (Sensor Node 11)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.75,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Insulins, Monoclonal Antibodies, Erythropoietin",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-01-U12": {
        "unit_id": "CC-FRIDGE-01-U12",
        "unit_name": "Central Pharmacy Main Biologics Unit (Sensor Node 12)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.80,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Insulins, Monoclonal Antibodies, Erythropoietin",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-01-U13": {
        "unit_id": "CC-FRIDGE-01-U13",
        "unit_name": "Central Pharmacy Main Biologics Unit (Sensor Node 13)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.85,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Insulins, Monoclonal Antibodies, Erythropoietin",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-01-U14": {
        "unit_id": "CC-FRIDGE-01-U14",
        "unit_name": "Central Pharmacy Main Biologics Unit (Sensor Node 14)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.90,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Insulins, Monoclonal Antibodies, Erythropoietin",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-02-U01": {
        "unit_id": "CC-FRIDGE-02-U01",
        "unit_name": "Emergency Ward Immediate Vaccine Refrigerator (Sensor Node 1)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 3.85,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Tetanus Toxoid, Rabies Vaccine, Antivenom",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-02-U02": {
        "unit_id": "CC-FRIDGE-02-U02",
        "unit_name": "Emergency Ward Immediate Vaccine Refrigerator (Sensor Node 2)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 3.90,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Tetanus Toxoid, Rabies Vaccine, Antivenom",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-02-U03": {
        "unit_id": "CC-FRIDGE-02-U03",
        "unit_name": "Emergency Ward Immediate Vaccine Refrigerator (Sensor Node 3)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 3.95,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Tetanus Toxoid, Rabies Vaccine, Antivenom",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-02-U04": {
        "unit_id": "CC-FRIDGE-02-U04",
        "unit_name": "Emergency Ward Immediate Vaccine Refrigerator (Sensor Node 4)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.00,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Tetanus Toxoid, Rabies Vaccine, Antivenom",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-02-U05": {
        "unit_id": "CC-FRIDGE-02-U05",
        "unit_name": "Emergency Ward Immediate Vaccine Refrigerator (Sensor Node 5)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.05,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Tetanus Toxoid, Rabies Vaccine, Antivenom",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-02-U06": {
        "unit_id": "CC-FRIDGE-02-U06",
        "unit_name": "Emergency Ward Immediate Vaccine Refrigerator (Sensor Node 6)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.10,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Tetanus Toxoid, Rabies Vaccine, Antivenom",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-02-U07": {
        "unit_id": "CC-FRIDGE-02-U07",
        "unit_name": "Emergency Ward Immediate Vaccine Refrigerator (Sensor Node 7)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.15,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Tetanus Toxoid, Rabies Vaccine, Antivenom",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-02-U08": {
        "unit_id": "CC-FRIDGE-02-U08",
        "unit_name": "Emergency Ward Immediate Vaccine Refrigerator (Sensor Node 8)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.20,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Tetanus Toxoid, Rabies Vaccine, Antivenom",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-02-U09": {
        "unit_id": "CC-FRIDGE-02-U09",
        "unit_name": "Emergency Ward Immediate Vaccine Refrigerator (Sensor Node 9)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.25,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Tetanus Toxoid, Rabies Vaccine, Antivenom",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-02-U10": {
        "unit_id": "CC-FRIDGE-02-U10",
        "unit_name": "Emergency Ward Immediate Vaccine Refrigerator (Sensor Node 10)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.30,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Tetanus Toxoid, Rabies Vaccine, Antivenom",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-02-U11": {
        "unit_id": "CC-FRIDGE-02-U11",
        "unit_name": "Emergency Ward Immediate Vaccine Refrigerator (Sensor Node 11)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.35,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Tetanus Toxoid, Rabies Vaccine, Antivenom",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-02-U12": {
        "unit_id": "CC-FRIDGE-02-U12",
        "unit_name": "Emergency Ward Immediate Vaccine Refrigerator (Sensor Node 12)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.40,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Tetanus Toxoid, Rabies Vaccine, Antivenom",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-02-U13": {
        "unit_id": "CC-FRIDGE-02-U13",
        "unit_name": "Emergency Ward Immediate Vaccine Refrigerator (Sensor Node 13)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.45,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Tetanus Toxoid, Rabies Vaccine, Antivenom",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-02-U14": {
        "unit_id": "CC-FRIDGE-02-U14",
        "unit_name": "Emergency Ward Immediate Vaccine Refrigerator (Sensor Node 14)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.50,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Tetanus Toxoid, Rabies Vaccine, Antivenom",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FREEZER-01-U01": {
        "unit_id": "CC-FREEZER-01-U01",
        "unit_name": "Ultra-Low Temperature Plasma & Vaccine Freezer (Sensor Node 1)",
        "min_safe_temp_celsius": -80.0,
        "max_safe_temp_celsius": -60.0,
        "current_temperature_celsius": -74.45,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "mRNA Vaccines, Fresh Frozen Plasma, Cryoprecipitate",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FREEZER-01-U02": {
        "unit_id": "CC-FREEZER-01-U02",
        "unit_name": "Ultra-Low Temperature Plasma & Vaccine Freezer (Sensor Node 2)",
        "min_safe_temp_celsius": -80.0,
        "max_safe_temp_celsius": -60.0,
        "current_temperature_celsius": -74.40,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "mRNA Vaccines, Fresh Frozen Plasma, Cryoprecipitate",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FREEZER-01-U03": {
        "unit_id": "CC-FREEZER-01-U03",
        "unit_name": "Ultra-Low Temperature Plasma & Vaccine Freezer (Sensor Node 3)",
        "min_safe_temp_celsius": -80.0,
        "max_safe_temp_celsius": -60.0,
        "current_temperature_celsius": -74.35,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "mRNA Vaccines, Fresh Frozen Plasma, Cryoprecipitate",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FREEZER-01-U04": {
        "unit_id": "CC-FREEZER-01-U04",
        "unit_name": "Ultra-Low Temperature Plasma & Vaccine Freezer (Sensor Node 4)",
        "min_safe_temp_celsius": -80.0,
        "max_safe_temp_celsius": -60.0,
        "current_temperature_celsius": -74.30,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "mRNA Vaccines, Fresh Frozen Plasma, Cryoprecipitate",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FREEZER-01-U05": {
        "unit_id": "CC-FREEZER-01-U05",
        "unit_name": "Ultra-Low Temperature Plasma & Vaccine Freezer (Sensor Node 5)",
        "min_safe_temp_celsius": -80.0,
        "max_safe_temp_celsius": -60.0,
        "current_temperature_celsius": -74.25,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "mRNA Vaccines, Fresh Frozen Plasma, Cryoprecipitate",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FREEZER-01-U06": {
        "unit_id": "CC-FREEZER-01-U06",
        "unit_name": "Ultra-Low Temperature Plasma & Vaccine Freezer (Sensor Node 6)",
        "min_safe_temp_celsius": -80.0,
        "max_safe_temp_celsius": -60.0,
        "current_temperature_celsius": -74.20,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "mRNA Vaccines, Fresh Frozen Plasma, Cryoprecipitate",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FREEZER-01-U07": {
        "unit_id": "CC-FREEZER-01-U07",
        "unit_name": "Ultra-Low Temperature Plasma & Vaccine Freezer (Sensor Node 7)",
        "min_safe_temp_celsius": -80.0,
        "max_safe_temp_celsius": -60.0,
        "current_temperature_celsius": -74.15,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "mRNA Vaccines, Fresh Frozen Plasma, Cryoprecipitate",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FREEZER-01-U08": {
        "unit_id": "CC-FREEZER-01-U08",
        "unit_name": "Ultra-Low Temperature Plasma & Vaccine Freezer (Sensor Node 8)",
        "min_safe_temp_celsius": -80.0,
        "max_safe_temp_celsius": -60.0,
        "current_temperature_celsius": -74.10,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "mRNA Vaccines, Fresh Frozen Plasma, Cryoprecipitate",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FREEZER-01-U09": {
        "unit_id": "CC-FREEZER-01-U09",
        "unit_name": "Ultra-Low Temperature Plasma & Vaccine Freezer (Sensor Node 9)",
        "min_safe_temp_celsius": -80.0,
        "max_safe_temp_celsius": -60.0,
        "current_temperature_celsius": -74.05,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "mRNA Vaccines, Fresh Frozen Plasma, Cryoprecipitate",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FREEZER-01-U10": {
        "unit_id": "CC-FREEZER-01-U10",
        "unit_name": "Ultra-Low Temperature Plasma & Vaccine Freezer (Sensor Node 10)",
        "min_safe_temp_celsius": -80.0,
        "max_safe_temp_celsius": -60.0,
        "current_temperature_celsius": -74.00,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "mRNA Vaccines, Fresh Frozen Plasma, Cryoprecipitate",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FREEZER-01-U11": {
        "unit_id": "CC-FREEZER-01-U11",
        "unit_name": "Ultra-Low Temperature Plasma & Vaccine Freezer (Sensor Node 11)",
        "min_safe_temp_celsius": -80.0,
        "max_safe_temp_celsius": -60.0,
        "current_temperature_celsius": -73.95,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "mRNA Vaccines, Fresh Frozen Plasma, Cryoprecipitate",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FREEZER-01-U12": {
        "unit_id": "CC-FREEZER-01-U12",
        "unit_name": "Ultra-Low Temperature Plasma & Vaccine Freezer (Sensor Node 12)",
        "min_safe_temp_celsius": -80.0,
        "max_safe_temp_celsius": -60.0,
        "current_temperature_celsius": -73.90,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "mRNA Vaccines, Fresh Frozen Plasma, Cryoprecipitate",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FREEZER-01-U13": {
        "unit_id": "CC-FREEZER-01-U13",
        "unit_name": "Ultra-Low Temperature Plasma & Vaccine Freezer (Sensor Node 13)",
        "min_safe_temp_celsius": -80.0,
        "max_safe_temp_celsius": -60.0,
        "current_temperature_celsius": -73.85,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "mRNA Vaccines, Fresh Frozen Plasma, Cryoprecipitate",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FREEZER-01-U14": {
        "unit_id": "CC-FREEZER-01-U14",
        "unit_name": "Ultra-Low Temperature Plasma & Vaccine Freezer (Sensor Node 14)",
        "min_safe_temp_celsius": -80.0,
        "max_safe_temp_celsius": -60.0,
        "current_temperature_celsius": -73.80,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "mRNA Vaccines, Fresh Frozen Plasma, Cryoprecipitate",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-03-U01": {
        "unit_id": "CC-FRIDGE-03-U01",
        "unit_name": "Pediatric Clinic Vaccine Storage Unit (Sensor Node 1)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.55,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "MMR, DTaP, Polio, Varicella, Hepatitis B",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-03-U02": {
        "unit_id": "CC-FRIDGE-03-U02",
        "unit_name": "Pediatric Clinic Vaccine Storage Unit (Sensor Node 2)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.60,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "MMR, DTaP, Polio, Varicella, Hepatitis B",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-03-U03": {
        "unit_id": "CC-FRIDGE-03-U03",
        "unit_name": "Pediatric Clinic Vaccine Storage Unit (Sensor Node 3)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.65,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "MMR, DTaP, Polio, Varicella, Hepatitis B",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-03-U04": {
        "unit_id": "CC-FRIDGE-03-U04",
        "unit_name": "Pediatric Clinic Vaccine Storage Unit (Sensor Node 4)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.70,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "MMR, DTaP, Polio, Varicella, Hepatitis B",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-03-U05": {
        "unit_id": "CC-FRIDGE-03-U05",
        "unit_name": "Pediatric Clinic Vaccine Storage Unit (Sensor Node 5)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.75,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "MMR, DTaP, Polio, Varicella, Hepatitis B",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-03-U06": {
        "unit_id": "CC-FRIDGE-03-U06",
        "unit_name": "Pediatric Clinic Vaccine Storage Unit (Sensor Node 6)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.80,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "MMR, DTaP, Polio, Varicella, Hepatitis B",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-03-U07": {
        "unit_id": "CC-FRIDGE-03-U07",
        "unit_name": "Pediatric Clinic Vaccine Storage Unit (Sensor Node 7)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.85,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "MMR, DTaP, Polio, Varicella, Hepatitis B",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-03-U08": {
        "unit_id": "CC-FRIDGE-03-U08",
        "unit_name": "Pediatric Clinic Vaccine Storage Unit (Sensor Node 8)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.90,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "MMR, DTaP, Polio, Varicella, Hepatitis B",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-03-U09": {
        "unit_id": "CC-FRIDGE-03-U09",
        "unit_name": "Pediatric Clinic Vaccine Storage Unit (Sensor Node 9)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.95,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "MMR, DTaP, Polio, Varicella, Hepatitis B",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-03-U10": {
        "unit_id": "CC-FRIDGE-03-U10",
        "unit_name": "Pediatric Clinic Vaccine Storage Unit (Sensor Node 10)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 5.00,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "MMR, DTaP, Polio, Varicella, Hepatitis B",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-03-U11": {
        "unit_id": "CC-FRIDGE-03-U11",
        "unit_name": "Pediatric Clinic Vaccine Storage Unit (Sensor Node 11)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 5.05,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "MMR, DTaP, Polio, Varicella, Hepatitis B",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-03-U12": {
        "unit_id": "CC-FRIDGE-03-U12",
        "unit_name": "Pediatric Clinic Vaccine Storage Unit (Sensor Node 12)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 5.10,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "MMR, DTaP, Polio, Varicella, Hepatitis B",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-03-U13": {
        "unit_id": "CC-FRIDGE-03-U13",
        "unit_name": "Pediatric Clinic Vaccine Storage Unit (Sensor Node 13)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 5.15,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "MMR, DTaP, Polio, Varicella, Hepatitis B",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-03-U14": {
        "unit_id": "CC-FRIDGE-03-U14",
        "unit_name": "Pediatric Clinic Vaccine Storage Unit (Sensor Node 14)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 5.20,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "MMR, DTaP, Polio, Varicella, Hepatitis B",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-04-U01": {
        "unit_id": "CC-FRIDGE-04-U01",
        "unit_name": "Oncology Chemotherapy & Immunotherapy Unit (Sensor Node 1)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.05,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Pembrolizumab, Trastuzumab, Rituximab",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-04-U02": {
        "unit_id": "CC-FRIDGE-04-U02",
        "unit_name": "Oncology Chemotherapy & Immunotherapy Unit (Sensor Node 2)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.10,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Pembrolizumab, Trastuzumab, Rituximab",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-04-U03": {
        "unit_id": "CC-FRIDGE-04-U03",
        "unit_name": "Oncology Chemotherapy & Immunotherapy Unit (Sensor Node 3)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.15,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Pembrolizumab, Trastuzumab, Rituximab",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-04-U04": {
        "unit_id": "CC-FRIDGE-04-U04",
        "unit_name": "Oncology Chemotherapy & Immunotherapy Unit (Sensor Node 4)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.20,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Pembrolizumab, Trastuzumab, Rituximab",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-04-U05": {
        "unit_id": "CC-FRIDGE-04-U05",
        "unit_name": "Oncology Chemotherapy & Immunotherapy Unit (Sensor Node 5)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.25,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Pembrolizumab, Trastuzumab, Rituximab",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-04-U06": {
        "unit_id": "CC-FRIDGE-04-U06",
        "unit_name": "Oncology Chemotherapy & Immunotherapy Unit (Sensor Node 6)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.30,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Pembrolizumab, Trastuzumab, Rituximab",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-04-U07": {
        "unit_id": "CC-FRIDGE-04-U07",
        "unit_name": "Oncology Chemotherapy & Immunotherapy Unit (Sensor Node 7)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.35,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Pembrolizumab, Trastuzumab, Rituximab",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-04-U08": {
        "unit_id": "CC-FRIDGE-04-U08",
        "unit_name": "Oncology Chemotherapy & Immunotherapy Unit (Sensor Node 8)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.40,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Pembrolizumab, Trastuzumab, Rituximab",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-04-U09": {
        "unit_id": "CC-FRIDGE-04-U09",
        "unit_name": "Oncology Chemotherapy & Immunotherapy Unit (Sensor Node 9)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.45,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Pembrolizumab, Trastuzumab, Rituximab",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-04-U10": {
        "unit_id": "CC-FRIDGE-04-U10",
        "unit_name": "Oncology Chemotherapy & Immunotherapy Unit (Sensor Node 10)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.50,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Pembrolizumab, Trastuzumab, Rituximab",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-04-U11": {
        "unit_id": "CC-FRIDGE-04-U11",
        "unit_name": "Oncology Chemotherapy & Immunotherapy Unit (Sensor Node 11)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.55,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Pembrolizumab, Trastuzumab, Rituximab",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-04-U12": {
        "unit_id": "CC-FRIDGE-04-U12",
        "unit_name": "Oncology Chemotherapy & Immunotherapy Unit (Sensor Node 12)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.60,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Pembrolizumab, Trastuzumab, Rituximab",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-04-U13": {
        "unit_id": "CC-FRIDGE-04-U13",
        "unit_name": "Oncology Chemotherapy & Immunotherapy Unit (Sensor Node 13)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.65,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Pembrolizumab, Trastuzumab, Rituximab",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
    "CC-FRIDGE-04-U14": {
        "unit_id": "CC-FRIDGE-04-U14",
        "unit_name": "Oncology Chemotherapy & Immunotherapy Unit (Sensor Node 14)",
        "min_safe_temp_celsius": 2.0,
        "max_safe_temp_celsius": 8.0,
        "current_temperature_celsius": 4.70,
        "temperature_status": "NORMAL",
        "stored_biologics_categories": "Pembrolizumab, Trastuzumab, Rituximab",
        "backup_battery_level_pct": 98,
        "iot_telemetry_ping_seconds": 30,
        "cellular_failover_active": False,
        "last_calibration_date": "2026-08-01",
    },
}
