"""
MediCore Nexus - Standard Clinical Admission & Outpatient Order Sets
Over 80 pre-configured clinical order sets for evidence-based care pathways.
"""

from typing import Dict, List, Any

CLINICAL_ORDER_SETS: Dict[str, Dict[str, Any]] = {
    "ORD-STEMI-V01": {
        "order_set_id": "ORD-STEMI-V01",
        "title": "Acute Coronary Syndrome / STEMI Admission (Protocol Pathway 1)",
        "department": "Cardiology",
        "standard_orders": ['Aspirin 325mg chewable', 'Ticagrelor 180mg loading dose', 'Heparin IV bolus & infusion', 'Atorvastatin 80mg oral daily', 'Troponin I q3h x 3', '12-Lead ECG stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 16,
    },
    "ORD-STEMI-V02": {
        "order_set_id": "ORD-STEMI-V02",
        "title": "Acute Coronary Syndrome / STEMI Admission (Protocol Pathway 2)",
        "department": "Cardiology",
        "standard_orders": ['Aspirin 325mg chewable', 'Ticagrelor 180mg loading dose', 'Heparin IV bolus & infusion', 'Atorvastatin 80mg oral daily', 'Troponin I q3h x 3', '12-Lead ECG stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 20,
    },
    "ORD-STEMI-V03": {
        "order_set_id": "ORD-STEMI-V03",
        "title": "Acute Coronary Syndrome / STEMI Admission (Protocol Pathway 3)",
        "department": "Cardiology",
        "standard_orders": ['Aspirin 325mg chewable', 'Ticagrelor 180mg loading dose', 'Heparin IV bolus & infusion', 'Atorvastatin 80mg oral daily', 'Troponin I q3h x 3', '12-Lead ECG stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 24,
    },
    "ORD-STEMI-V04": {
        "order_set_id": "ORD-STEMI-V04",
        "title": "Acute Coronary Syndrome / STEMI Admission (Protocol Pathway 4)",
        "department": "Cardiology",
        "standard_orders": ['Aspirin 325mg chewable', 'Ticagrelor 180mg loading dose', 'Heparin IV bolus & infusion', 'Atorvastatin 80mg oral daily', 'Troponin I q3h x 3', '12-Lead ECG stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 28,
    },
    "ORD-STEMI-V05": {
        "order_set_id": "ORD-STEMI-V05",
        "title": "Acute Coronary Syndrome / STEMI Admission (Protocol Pathway 5)",
        "department": "Cardiology",
        "standard_orders": ['Aspirin 325mg chewable', 'Ticagrelor 180mg loading dose', 'Heparin IV bolus & infusion', 'Atorvastatin 80mg oral daily', 'Troponin I q3h x 3', '12-Lead ECG stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 32,
    },
    "ORD-STEMI-V06": {
        "order_set_id": "ORD-STEMI-V06",
        "title": "Acute Coronary Syndrome / STEMI Admission (Protocol Pathway 6)",
        "department": "Cardiology",
        "standard_orders": ['Aspirin 325mg chewable', 'Ticagrelor 180mg loading dose', 'Heparin IV bolus & infusion', 'Atorvastatin 80mg oral daily', 'Troponin I q3h x 3', '12-Lead ECG stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 36,
    },
    "ORD-STEMI-V07": {
        "order_set_id": "ORD-STEMI-V07",
        "title": "Acute Coronary Syndrome / STEMI Admission (Protocol Pathway 7)",
        "department": "Cardiology",
        "standard_orders": ['Aspirin 325mg chewable', 'Ticagrelor 180mg loading dose', 'Heparin IV bolus & infusion', 'Atorvastatin 80mg oral daily', 'Troponin I q3h x 3', '12-Lead ECG stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 40,
    },
    "ORD-STEMI-V08": {
        "order_set_id": "ORD-STEMI-V08",
        "title": "Acute Coronary Syndrome / STEMI Admission (Protocol Pathway 8)",
        "department": "Cardiology",
        "standard_orders": ['Aspirin 325mg chewable', 'Ticagrelor 180mg loading dose', 'Heparin IV bolus & infusion', 'Atorvastatin 80mg oral daily', 'Troponin I q3h x 3', '12-Lead ECG stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 44,
    },
    "ORD-STEMI-V09": {
        "order_set_id": "ORD-STEMI-V09",
        "title": "Acute Coronary Syndrome / STEMI Admission (Protocol Pathway 9)",
        "department": "Cardiology",
        "standard_orders": ['Aspirin 325mg chewable', 'Ticagrelor 180mg loading dose', 'Heparin IV bolus & infusion', 'Atorvastatin 80mg oral daily', 'Troponin I q3h x 3', '12-Lead ECG stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 48,
    },
    "ORD-STEMI-V10": {
        "order_set_id": "ORD-STEMI-V10",
        "title": "Acute Coronary Syndrome / STEMI Admission (Protocol Pathway 10)",
        "department": "Cardiology",
        "standard_orders": ['Aspirin 325mg chewable', 'Ticagrelor 180mg loading dose', 'Heparin IV bolus & infusion', 'Atorvastatin 80mg oral daily', 'Troponin I q3h x 3', '12-Lead ECG stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 52,
    },
    "ORD-STEMI-V11": {
        "order_set_id": "ORD-STEMI-V11",
        "title": "Acute Coronary Syndrome / STEMI Admission (Protocol Pathway 11)",
        "department": "Cardiology",
        "standard_orders": ['Aspirin 325mg chewable', 'Ticagrelor 180mg loading dose', 'Heparin IV bolus & infusion', 'Atorvastatin 80mg oral daily', 'Troponin I q3h x 3', '12-Lead ECG stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 56,
    },
    "ORD-STEMI-V12": {
        "order_set_id": "ORD-STEMI-V12",
        "title": "Acute Coronary Syndrome / STEMI Admission (Protocol Pathway 12)",
        "department": "Cardiology",
        "standard_orders": ['Aspirin 325mg chewable', 'Ticagrelor 180mg loading dose', 'Heparin IV bolus & infusion', 'Atorvastatin 80mg oral daily', 'Troponin I q3h x 3', '12-Lead ECG stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 60,
    },
    "ORD-STEMI-V13": {
        "order_set_id": "ORD-STEMI-V13",
        "title": "Acute Coronary Syndrome / STEMI Admission (Protocol Pathway 13)",
        "department": "Cardiology",
        "standard_orders": ['Aspirin 325mg chewable', 'Ticagrelor 180mg loading dose', 'Heparin IV bolus & infusion', 'Atorvastatin 80mg oral daily', 'Troponin I q3h x 3', '12-Lead ECG stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 64,
    },
    "ORD-STEMI-V14": {
        "order_set_id": "ORD-STEMI-V14",
        "title": "Acute Coronary Syndrome / STEMI Admission (Protocol Pathway 14)",
        "department": "Cardiology",
        "standard_orders": ['Aspirin 325mg chewable', 'Ticagrelor 180mg loading dose', 'Heparin IV bolus & infusion', 'Atorvastatin 80mg oral daily', 'Troponin I q3h x 3', '12-Lead ECG stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 68,
    },
    "ORD-STEMI-V15": {
        "order_set_id": "ORD-STEMI-V15",
        "title": "Acute Coronary Syndrome / STEMI Admission (Protocol Pathway 15)",
        "department": "Cardiology",
        "standard_orders": ['Aspirin 325mg chewable', 'Ticagrelor 180mg loading dose', 'Heparin IV bolus & infusion', 'Atorvastatin 80mg oral daily', 'Troponin I q3h x 3', '12-Lead ECG stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 72,
    },
    "ORD-STEMI-V16": {
        "order_set_id": "ORD-STEMI-V16",
        "title": "Acute Coronary Syndrome / STEMI Admission (Protocol Pathway 16)",
        "department": "Cardiology",
        "standard_orders": ['Aspirin 325mg chewable', 'Ticagrelor 180mg loading dose', 'Heparin IV bolus & infusion', 'Atorvastatin 80mg oral daily', 'Troponin I q3h x 3', '12-Lead ECG stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 76,
    },
    "ORD-STEMI-V17": {
        "order_set_id": "ORD-STEMI-V17",
        "title": "Acute Coronary Syndrome / STEMI Admission (Protocol Pathway 17)",
        "department": "Cardiology",
        "standard_orders": ['Aspirin 325mg chewable', 'Ticagrelor 180mg loading dose', 'Heparin IV bolus & infusion', 'Atorvastatin 80mg oral daily', 'Troponin I q3h x 3', '12-Lead ECG stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 80,
    },
    "ORD-STEMI-V18": {
        "order_set_id": "ORD-STEMI-V18",
        "title": "Acute Coronary Syndrome / STEMI Admission (Protocol Pathway 18)",
        "department": "Cardiology",
        "standard_orders": ['Aspirin 325mg chewable', 'Ticagrelor 180mg loading dose', 'Heparin IV bolus & infusion', 'Atorvastatin 80mg oral daily', 'Troponin I q3h x 3', '12-Lead ECG stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 84,
    },
    "ORD-STEMI-V19": {
        "order_set_id": "ORD-STEMI-V19",
        "title": "Acute Coronary Syndrome / STEMI Admission (Protocol Pathway 19)",
        "department": "Cardiology",
        "standard_orders": ['Aspirin 325mg chewable', 'Ticagrelor 180mg loading dose', 'Heparin IV bolus & infusion', 'Atorvastatin 80mg oral daily', 'Troponin I q3h x 3', '12-Lead ECG stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 88,
    },
    "ORD-DKA-V01": {
        "order_set_id": "ORD-DKA-V01",
        "title": "Diabetic Ketoacidosis (DKA) Protocol (Protocol Pathway 1)",
        "department": "Endocrinology",
        "standard_orders": ['Regular Insulin IV 0.1 units/kg/hr', '0.9% Normal Saline 1000 mL/hr x 2h', 'Potassium Chloride 20 mEq/L in IV fluid', 'Basic Metabolic Panel q2h', 'Fingerstick blood glucose q1h', 'Serum Beta-hydroxybutyrate'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 16,
    },
    "ORD-DKA-V02": {
        "order_set_id": "ORD-DKA-V02",
        "title": "Diabetic Ketoacidosis (DKA) Protocol (Protocol Pathway 2)",
        "department": "Endocrinology",
        "standard_orders": ['Regular Insulin IV 0.1 units/kg/hr', '0.9% Normal Saline 1000 mL/hr x 2h', 'Potassium Chloride 20 mEq/L in IV fluid', 'Basic Metabolic Panel q2h', 'Fingerstick blood glucose q1h', 'Serum Beta-hydroxybutyrate'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 20,
    },
    "ORD-DKA-V03": {
        "order_set_id": "ORD-DKA-V03",
        "title": "Diabetic Ketoacidosis (DKA) Protocol (Protocol Pathway 3)",
        "department": "Endocrinology",
        "standard_orders": ['Regular Insulin IV 0.1 units/kg/hr', '0.9% Normal Saline 1000 mL/hr x 2h', 'Potassium Chloride 20 mEq/L in IV fluid', 'Basic Metabolic Panel q2h', 'Fingerstick blood glucose q1h', 'Serum Beta-hydroxybutyrate'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 24,
    },
    "ORD-DKA-V04": {
        "order_set_id": "ORD-DKA-V04",
        "title": "Diabetic Ketoacidosis (DKA) Protocol (Protocol Pathway 4)",
        "department": "Endocrinology",
        "standard_orders": ['Regular Insulin IV 0.1 units/kg/hr', '0.9% Normal Saline 1000 mL/hr x 2h', 'Potassium Chloride 20 mEq/L in IV fluid', 'Basic Metabolic Panel q2h', 'Fingerstick blood glucose q1h', 'Serum Beta-hydroxybutyrate'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 28,
    },
    "ORD-DKA-V05": {
        "order_set_id": "ORD-DKA-V05",
        "title": "Diabetic Ketoacidosis (DKA) Protocol (Protocol Pathway 5)",
        "department": "Endocrinology",
        "standard_orders": ['Regular Insulin IV 0.1 units/kg/hr', '0.9% Normal Saline 1000 mL/hr x 2h', 'Potassium Chloride 20 mEq/L in IV fluid', 'Basic Metabolic Panel q2h', 'Fingerstick blood glucose q1h', 'Serum Beta-hydroxybutyrate'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 32,
    },
    "ORD-DKA-V06": {
        "order_set_id": "ORD-DKA-V06",
        "title": "Diabetic Ketoacidosis (DKA) Protocol (Protocol Pathway 6)",
        "department": "Endocrinology",
        "standard_orders": ['Regular Insulin IV 0.1 units/kg/hr', '0.9% Normal Saline 1000 mL/hr x 2h', 'Potassium Chloride 20 mEq/L in IV fluid', 'Basic Metabolic Panel q2h', 'Fingerstick blood glucose q1h', 'Serum Beta-hydroxybutyrate'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 36,
    },
    "ORD-DKA-V07": {
        "order_set_id": "ORD-DKA-V07",
        "title": "Diabetic Ketoacidosis (DKA) Protocol (Protocol Pathway 7)",
        "department": "Endocrinology",
        "standard_orders": ['Regular Insulin IV 0.1 units/kg/hr', '0.9% Normal Saline 1000 mL/hr x 2h', 'Potassium Chloride 20 mEq/L in IV fluid', 'Basic Metabolic Panel q2h', 'Fingerstick blood glucose q1h', 'Serum Beta-hydroxybutyrate'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 40,
    },
    "ORD-DKA-V08": {
        "order_set_id": "ORD-DKA-V08",
        "title": "Diabetic Ketoacidosis (DKA) Protocol (Protocol Pathway 8)",
        "department": "Endocrinology",
        "standard_orders": ['Regular Insulin IV 0.1 units/kg/hr', '0.9% Normal Saline 1000 mL/hr x 2h', 'Potassium Chloride 20 mEq/L in IV fluid', 'Basic Metabolic Panel q2h', 'Fingerstick blood glucose q1h', 'Serum Beta-hydroxybutyrate'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 44,
    },
    "ORD-DKA-V09": {
        "order_set_id": "ORD-DKA-V09",
        "title": "Diabetic Ketoacidosis (DKA) Protocol (Protocol Pathway 9)",
        "department": "Endocrinology",
        "standard_orders": ['Regular Insulin IV 0.1 units/kg/hr', '0.9% Normal Saline 1000 mL/hr x 2h', 'Potassium Chloride 20 mEq/L in IV fluid', 'Basic Metabolic Panel q2h', 'Fingerstick blood glucose q1h', 'Serum Beta-hydroxybutyrate'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 48,
    },
    "ORD-DKA-V10": {
        "order_set_id": "ORD-DKA-V10",
        "title": "Diabetic Ketoacidosis (DKA) Protocol (Protocol Pathway 10)",
        "department": "Endocrinology",
        "standard_orders": ['Regular Insulin IV 0.1 units/kg/hr', '0.9% Normal Saline 1000 mL/hr x 2h', 'Potassium Chloride 20 mEq/L in IV fluid', 'Basic Metabolic Panel q2h', 'Fingerstick blood glucose q1h', 'Serum Beta-hydroxybutyrate'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 52,
    },
    "ORD-DKA-V11": {
        "order_set_id": "ORD-DKA-V11",
        "title": "Diabetic Ketoacidosis (DKA) Protocol (Protocol Pathway 11)",
        "department": "Endocrinology",
        "standard_orders": ['Regular Insulin IV 0.1 units/kg/hr', '0.9% Normal Saline 1000 mL/hr x 2h', 'Potassium Chloride 20 mEq/L in IV fluid', 'Basic Metabolic Panel q2h', 'Fingerstick blood glucose q1h', 'Serum Beta-hydroxybutyrate'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 56,
    },
    "ORD-DKA-V12": {
        "order_set_id": "ORD-DKA-V12",
        "title": "Diabetic Ketoacidosis (DKA) Protocol (Protocol Pathway 12)",
        "department": "Endocrinology",
        "standard_orders": ['Regular Insulin IV 0.1 units/kg/hr', '0.9% Normal Saline 1000 mL/hr x 2h', 'Potassium Chloride 20 mEq/L in IV fluid', 'Basic Metabolic Panel q2h', 'Fingerstick blood glucose q1h', 'Serum Beta-hydroxybutyrate'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 60,
    },
    "ORD-DKA-V13": {
        "order_set_id": "ORD-DKA-V13",
        "title": "Diabetic Ketoacidosis (DKA) Protocol (Protocol Pathway 13)",
        "department": "Endocrinology",
        "standard_orders": ['Regular Insulin IV 0.1 units/kg/hr', '0.9% Normal Saline 1000 mL/hr x 2h', 'Potassium Chloride 20 mEq/L in IV fluid', 'Basic Metabolic Panel q2h', 'Fingerstick blood glucose q1h', 'Serum Beta-hydroxybutyrate'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 64,
    },
    "ORD-DKA-V14": {
        "order_set_id": "ORD-DKA-V14",
        "title": "Diabetic Ketoacidosis (DKA) Protocol (Protocol Pathway 14)",
        "department": "Endocrinology",
        "standard_orders": ['Regular Insulin IV 0.1 units/kg/hr', '0.9% Normal Saline 1000 mL/hr x 2h', 'Potassium Chloride 20 mEq/L in IV fluid', 'Basic Metabolic Panel q2h', 'Fingerstick blood glucose q1h', 'Serum Beta-hydroxybutyrate'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 68,
    },
    "ORD-DKA-V15": {
        "order_set_id": "ORD-DKA-V15",
        "title": "Diabetic Ketoacidosis (DKA) Protocol (Protocol Pathway 15)",
        "department": "Endocrinology",
        "standard_orders": ['Regular Insulin IV 0.1 units/kg/hr', '0.9% Normal Saline 1000 mL/hr x 2h', 'Potassium Chloride 20 mEq/L in IV fluid', 'Basic Metabolic Panel q2h', 'Fingerstick blood glucose q1h', 'Serum Beta-hydroxybutyrate'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 72,
    },
    "ORD-DKA-V16": {
        "order_set_id": "ORD-DKA-V16",
        "title": "Diabetic Ketoacidosis (DKA) Protocol (Protocol Pathway 16)",
        "department": "Endocrinology",
        "standard_orders": ['Regular Insulin IV 0.1 units/kg/hr', '0.9% Normal Saline 1000 mL/hr x 2h', 'Potassium Chloride 20 mEq/L in IV fluid', 'Basic Metabolic Panel q2h', 'Fingerstick blood glucose q1h', 'Serum Beta-hydroxybutyrate'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 76,
    },
    "ORD-DKA-V17": {
        "order_set_id": "ORD-DKA-V17",
        "title": "Diabetic Ketoacidosis (DKA) Protocol (Protocol Pathway 17)",
        "department": "Endocrinology",
        "standard_orders": ['Regular Insulin IV 0.1 units/kg/hr', '0.9% Normal Saline 1000 mL/hr x 2h', 'Potassium Chloride 20 mEq/L in IV fluid', 'Basic Metabolic Panel q2h', 'Fingerstick blood glucose q1h', 'Serum Beta-hydroxybutyrate'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 80,
    },
    "ORD-DKA-V18": {
        "order_set_id": "ORD-DKA-V18",
        "title": "Diabetic Ketoacidosis (DKA) Protocol (Protocol Pathway 18)",
        "department": "Endocrinology",
        "standard_orders": ['Regular Insulin IV 0.1 units/kg/hr', '0.9% Normal Saline 1000 mL/hr x 2h', 'Potassium Chloride 20 mEq/L in IV fluid', 'Basic Metabolic Panel q2h', 'Fingerstick blood glucose q1h', 'Serum Beta-hydroxybutyrate'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 84,
    },
    "ORD-DKA-V19": {
        "order_set_id": "ORD-DKA-V19",
        "title": "Diabetic Ketoacidosis (DKA) Protocol (Protocol Pathway 19)",
        "department": "Endocrinology",
        "standard_orders": ['Regular Insulin IV 0.1 units/kg/hr', '0.9% Normal Saline 1000 mL/hr x 2h', 'Potassium Chloride 20 mEq/L in IV fluid', 'Basic Metabolic Panel q2h', 'Fingerstick blood glucose q1h', 'Serum Beta-hydroxybutyrate'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 88,
    },
    "ORD-SEPSIS-V01": {
        "order_set_id": "ORD-SEPSIS-V01",
        "title": "Severe Sepsis & Septic Shock Bundle (Protocol Pathway 1)",
        "department": "Critical Care",
        "standard_orders": ['Vancomycin 15-20 mg/kg IV q12h', 'Cefepime 2g IV q8h', "Lactated Ringer's 30 mL/kg IV bolus", 'Serum Lactate stat and q2h', 'Blood Cultures x 2 sets prior to antibiotics', 'Continuous pulse oximetry & BP monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 16,
    },
    "ORD-SEPSIS-V02": {
        "order_set_id": "ORD-SEPSIS-V02",
        "title": "Severe Sepsis & Septic Shock Bundle (Protocol Pathway 2)",
        "department": "Critical Care",
        "standard_orders": ['Vancomycin 15-20 mg/kg IV q12h', 'Cefepime 2g IV q8h', "Lactated Ringer's 30 mL/kg IV bolus", 'Serum Lactate stat and q2h', 'Blood Cultures x 2 sets prior to antibiotics', 'Continuous pulse oximetry & BP monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 20,
    },
    "ORD-SEPSIS-V03": {
        "order_set_id": "ORD-SEPSIS-V03",
        "title": "Severe Sepsis & Septic Shock Bundle (Protocol Pathway 3)",
        "department": "Critical Care",
        "standard_orders": ['Vancomycin 15-20 mg/kg IV q12h', 'Cefepime 2g IV q8h', "Lactated Ringer's 30 mL/kg IV bolus", 'Serum Lactate stat and q2h', 'Blood Cultures x 2 sets prior to antibiotics', 'Continuous pulse oximetry & BP monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 24,
    },
    "ORD-SEPSIS-V04": {
        "order_set_id": "ORD-SEPSIS-V04",
        "title": "Severe Sepsis & Septic Shock Bundle (Protocol Pathway 4)",
        "department": "Critical Care",
        "standard_orders": ['Vancomycin 15-20 mg/kg IV q12h', 'Cefepime 2g IV q8h', "Lactated Ringer's 30 mL/kg IV bolus", 'Serum Lactate stat and q2h', 'Blood Cultures x 2 sets prior to antibiotics', 'Continuous pulse oximetry & BP monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 28,
    },
    "ORD-SEPSIS-V05": {
        "order_set_id": "ORD-SEPSIS-V05",
        "title": "Severe Sepsis & Septic Shock Bundle (Protocol Pathway 5)",
        "department": "Critical Care",
        "standard_orders": ['Vancomycin 15-20 mg/kg IV q12h', 'Cefepime 2g IV q8h', "Lactated Ringer's 30 mL/kg IV bolus", 'Serum Lactate stat and q2h', 'Blood Cultures x 2 sets prior to antibiotics', 'Continuous pulse oximetry & BP monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 32,
    },
    "ORD-SEPSIS-V06": {
        "order_set_id": "ORD-SEPSIS-V06",
        "title": "Severe Sepsis & Septic Shock Bundle (Protocol Pathway 6)",
        "department": "Critical Care",
        "standard_orders": ['Vancomycin 15-20 mg/kg IV q12h', 'Cefepime 2g IV q8h', "Lactated Ringer's 30 mL/kg IV bolus", 'Serum Lactate stat and q2h', 'Blood Cultures x 2 sets prior to antibiotics', 'Continuous pulse oximetry & BP monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 36,
    },
    "ORD-SEPSIS-V07": {
        "order_set_id": "ORD-SEPSIS-V07",
        "title": "Severe Sepsis & Septic Shock Bundle (Protocol Pathway 7)",
        "department": "Critical Care",
        "standard_orders": ['Vancomycin 15-20 mg/kg IV q12h', 'Cefepime 2g IV q8h', "Lactated Ringer's 30 mL/kg IV bolus", 'Serum Lactate stat and q2h', 'Blood Cultures x 2 sets prior to antibiotics', 'Continuous pulse oximetry & BP monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 40,
    },
    "ORD-SEPSIS-V08": {
        "order_set_id": "ORD-SEPSIS-V08",
        "title": "Severe Sepsis & Septic Shock Bundle (Protocol Pathway 8)",
        "department": "Critical Care",
        "standard_orders": ['Vancomycin 15-20 mg/kg IV q12h', 'Cefepime 2g IV q8h', "Lactated Ringer's 30 mL/kg IV bolus", 'Serum Lactate stat and q2h', 'Blood Cultures x 2 sets prior to antibiotics', 'Continuous pulse oximetry & BP monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 44,
    },
    "ORD-SEPSIS-V09": {
        "order_set_id": "ORD-SEPSIS-V09",
        "title": "Severe Sepsis & Septic Shock Bundle (Protocol Pathway 9)",
        "department": "Critical Care",
        "standard_orders": ['Vancomycin 15-20 mg/kg IV q12h', 'Cefepime 2g IV q8h', "Lactated Ringer's 30 mL/kg IV bolus", 'Serum Lactate stat and q2h', 'Blood Cultures x 2 sets prior to antibiotics', 'Continuous pulse oximetry & BP monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 48,
    },
    "ORD-SEPSIS-V10": {
        "order_set_id": "ORD-SEPSIS-V10",
        "title": "Severe Sepsis & Septic Shock Bundle (Protocol Pathway 10)",
        "department": "Critical Care",
        "standard_orders": ['Vancomycin 15-20 mg/kg IV q12h', 'Cefepime 2g IV q8h', "Lactated Ringer's 30 mL/kg IV bolus", 'Serum Lactate stat and q2h', 'Blood Cultures x 2 sets prior to antibiotics', 'Continuous pulse oximetry & BP monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 52,
    },
    "ORD-SEPSIS-V11": {
        "order_set_id": "ORD-SEPSIS-V11",
        "title": "Severe Sepsis & Septic Shock Bundle (Protocol Pathway 11)",
        "department": "Critical Care",
        "standard_orders": ['Vancomycin 15-20 mg/kg IV q12h', 'Cefepime 2g IV q8h', "Lactated Ringer's 30 mL/kg IV bolus", 'Serum Lactate stat and q2h', 'Blood Cultures x 2 sets prior to antibiotics', 'Continuous pulse oximetry & BP monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 56,
    },
    "ORD-SEPSIS-V12": {
        "order_set_id": "ORD-SEPSIS-V12",
        "title": "Severe Sepsis & Septic Shock Bundle (Protocol Pathway 12)",
        "department": "Critical Care",
        "standard_orders": ['Vancomycin 15-20 mg/kg IV q12h', 'Cefepime 2g IV q8h', "Lactated Ringer's 30 mL/kg IV bolus", 'Serum Lactate stat and q2h', 'Blood Cultures x 2 sets prior to antibiotics', 'Continuous pulse oximetry & BP monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 60,
    },
    "ORD-SEPSIS-V13": {
        "order_set_id": "ORD-SEPSIS-V13",
        "title": "Severe Sepsis & Septic Shock Bundle (Protocol Pathway 13)",
        "department": "Critical Care",
        "standard_orders": ['Vancomycin 15-20 mg/kg IV q12h', 'Cefepime 2g IV q8h', "Lactated Ringer's 30 mL/kg IV bolus", 'Serum Lactate stat and q2h', 'Blood Cultures x 2 sets prior to antibiotics', 'Continuous pulse oximetry & BP monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 64,
    },
    "ORD-SEPSIS-V14": {
        "order_set_id": "ORD-SEPSIS-V14",
        "title": "Severe Sepsis & Septic Shock Bundle (Protocol Pathway 14)",
        "department": "Critical Care",
        "standard_orders": ['Vancomycin 15-20 mg/kg IV q12h', 'Cefepime 2g IV q8h', "Lactated Ringer's 30 mL/kg IV bolus", 'Serum Lactate stat and q2h', 'Blood Cultures x 2 sets prior to antibiotics', 'Continuous pulse oximetry & BP monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 68,
    },
    "ORD-SEPSIS-V15": {
        "order_set_id": "ORD-SEPSIS-V15",
        "title": "Severe Sepsis & Septic Shock Bundle (Protocol Pathway 15)",
        "department": "Critical Care",
        "standard_orders": ['Vancomycin 15-20 mg/kg IV q12h', 'Cefepime 2g IV q8h', "Lactated Ringer's 30 mL/kg IV bolus", 'Serum Lactate stat and q2h', 'Blood Cultures x 2 sets prior to antibiotics', 'Continuous pulse oximetry & BP monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 72,
    },
    "ORD-SEPSIS-V16": {
        "order_set_id": "ORD-SEPSIS-V16",
        "title": "Severe Sepsis & Septic Shock Bundle (Protocol Pathway 16)",
        "department": "Critical Care",
        "standard_orders": ['Vancomycin 15-20 mg/kg IV q12h', 'Cefepime 2g IV q8h', "Lactated Ringer's 30 mL/kg IV bolus", 'Serum Lactate stat and q2h', 'Blood Cultures x 2 sets prior to antibiotics', 'Continuous pulse oximetry & BP monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 76,
    },
    "ORD-SEPSIS-V17": {
        "order_set_id": "ORD-SEPSIS-V17",
        "title": "Severe Sepsis & Septic Shock Bundle (Protocol Pathway 17)",
        "department": "Critical Care",
        "standard_orders": ['Vancomycin 15-20 mg/kg IV q12h', 'Cefepime 2g IV q8h', "Lactated Ringer's 30 mL/kg IV bolus", 'Serum Lactate stat and q2h', 'Blood Cultures x 2 sets prior to antibiotics', 'Continuous pulse oximetry & BP monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 80,
    },
    "ORD-SEPSIS-V18": {
        "order_set_id": "ORD-SEPSIS-V18",
        "title": "Severe Sepsis & Septic Shock Bundle (Protocol Pathway 18)",
        "department": "Critical Care",
        "standard_orders": ['Vancomycin 15-20 mg/kg IV q12h', 'Cefepime 2g IV q8h', "Lactated Ringer's 30 mL/kg IV bolus", 'Serum Lactate stat and q2h', 'Blood Cultures x 2 sets prior to antibiotics', 'Continuous pulse oximetry & BP monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 84,
    },
    "ORD-SEPSIS-V19": {
        "order_set_id": "ORD-SEPSIS-V19",
        "title": "Severe Sepsis & Septic Shock Bundle (Protocol Pathway 19)",
        "department": "Critical Care",
        "standard_orders": ['Vancomycin 15-20 mg/kg IV q12h', 'Cefepime 2g IV q8h', "Lactated Ringer's 30 mL/kg IV bolus", 'Serum Lactate stat and q2h', 'Blood Cultures x 2 sets prior to antibiotics', 'Continuous pulse oximetry & BP monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 88,
    },
    "ORD-ASTHMA-V01": {
        "order_set_id": "ORD-ASTHMA-V01",
        "title": "Acute Asthma Exacerbation Protocol (Protocol Pathway 1)",
        "department": "Pulmonology",
        "standard_orders": ['Albuterol 2.5mg / Ipratropium 0.5mg nebulized q20min x 3', 'Methylprednisolone 60mg IV q6h', 'Oxygen via nasal cannula titrate SpO2 > 92%', 'Peak Expiratory Flow Rate (PEFR) pre/post tx', 'Chest X-Ray 1-view stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 16,
    },
    "ORD-ASTHMA-V02": {
        "order_set_id": "ORD-ASTHMA-V02",
        "title": "Acute Asthma Exacerbation Protocol (Protocol Pathway 2)",
        "department": "Pulmonology",
        "standard_orders": ['Albuterol 2.5mg / Ipratropium 0.5mg nebulized q20min x 3', 'Methylprednisolone 60mg IV q6h', 'Oxygen via nasal cannula titrate SpO2 > 92%', 'Peak Expiratory Flow Rate (PEFR) pre/post tx', 'Chest X-Ray 1-view stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 20,
    },
    "ORD-ASTHMA-V03": {
        "order_set_id": "ORD-ASTHMA-V03",
        "title": "Acute Asthma Exacerbation Protocol (Protocol Pathway 3)",
        "department": "Pulmonology",
        "standard_orders": ['Albuterol 2.5mg / Ipratropium 0.5mg nebulized q20min x 3', 'Methylprednisolone 60mg IV q6h', 'Oxygen via nasal cannula titrate SpO2 > 92%', 'Peak Expiratory Flow Rate (PEFR) pre/post tx', 'Chest X-Ray 1-view stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 24,
    },
    "ORD-ASTHMA-V04": {
        "order_set_id": "ORD-ASTHMA-V04",
        "title": "Acute Asthma Exacerbation Protocol (Protocol Pathway 4)",
        "department": "Pulmonology",
        "standard_orders": ['Albuterol 2.5mg / Ipratropium 0.5mg nebulized q20min x 3', 'Methylprednisolone 60mg IV q6h', 'Oxygen via nasal cannula titrate SpO2 > 92%', 'Peak Expiratory Flow Rate (PEFR) pre/post tx', 'Chest X-Ray 1-view stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 28,
    },
    "ORD-ASTHMA-V05": {
        "order_set_id": "ORD-ASTHMA-V05",
        "title": "Acute Asthma Exacerbation Protocol (Protocol Pathway 5)",
        "department": "Pulmonology",
        "standard_orders": ['Albuterol 2.5mg / Ipratropium 0.5mg nebulized q20min x 3', 'Methylprednisolone 60mg IV q6h', 'Oxygen via nasal cannula titrate SpO2 > 92%', 'Peak Expiratory Flow Rate (PEFR) pre/post tx', 'Chest X-Ray 1-view stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 32,
    },
    "ORD-ASTHMA-V06": {
        "order_set_id": "ORD-ASTHMA-V06",
        "title": "Acute Asthma Exacerbation Protocol (Protocol Pathway 6)",
        "department": "Pulmonology",
        "standard_orders": ['Albuterol 2.5mg / Ipratropium 0.5mg nebulized q20min x 3', 'Methylprednisolone 60mg IV q6h', 'Oxygen via nasal cannula titrate SpO2 > 92%', 'Peak Expiratory Flow Rate (PEFR) pre/post tx', 'Chest X-Ray 1-view stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 36,
    },
    "ORD-ASTHMA-V07": {
        "order_set_id": "ORD-ASTHMA-V07",
        "title": "Acute Asthma Exacerbation Protocol (Protocol Pathway 7)",
        "department": "Pulmonology",
        "standard_orders": ['Albuterol 2.5mg / Ipratropium 0.5mg nebulized q20min x 3', 'Methylprednisolone 60mg IV q6h', 'Oxygen via nasal cannula titrate SpO2 > 92%', 'Peak Expiratory Flow Rate (PEFR) pre/post tx', 'Chest X-Ray 1-view stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 40,
    },
    "ORD-ASTHMA-V08": {
        "order_set_id": "ORD-ASTHMA-V08",
        "title": "Acute Asthma Exacerbation Protocol (Protocol Pathway 8)",
        "department": "Pulmonology",
        "standard_orders": ['Albuterol 2.5mg / Ipratropium 0.5mg nebulized q20min x 3', 'Methylprednisolone 60mg IV q6h', 'Oxygen via nasal cannula titrate SpO2 > 92%', 'Peak Expiratory Flow Rate (PEFR) pre/post tx', 'Chest X-Ray 1-view stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 44,
    },
    "ORD-ASTHMA-V09": {
        "order_set_id": "ORD-ASTHMA-V09",
        "title": "Acute Asthma Exacerbation Protocol (Protocol Pathway 9)",
        "department": "Pulmonology",
        "standard_orders": ['Albuterol 2.5mg / Ipratropium 0.5mg nebulized q20min x 3', 'Methylprednisolone 60mg IV q6h', 'Oxygen via nasal cannula titrate SpO2 > 92%', 'Peak Expiratory Flow Rate (PEFR) pre/post tx', 'Chest X-Ray 1-view stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 48,
    },
    "ORD-ASTHMA-V10": {
        "order_set_id": "ORD-ASTHMA-V10",
        "title": "Acute Asthma Exacerbation Protocol (Protocol Pathway 10)",
        "department": "Pulmonology",
        "standard_orders": ['Albuterol 2.5mg / Ipratropium 0.5mg nebulized q20min x 3', 'Methylprednisolone 60mg IV q6h', 'Oxygen via nasal cannula titrate SpO2 > 92%', 'Peak Expiratory Flow Rate (PEFR) pre/post tx', 'Chest X-Ray 1-view stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 52,
    },
    "ORD-ASTHMA-V11": {
        "order_set_id": "ORD-ASTHMA-V11",
        "title": "Acute Asthma Exacerbation Protocol (Protocol Pathway 11)",
        "department": "Pulmonology",
        "standard_orders": ['Albuterol 2.5mg / Ipratropium 0.5mg nebulized q20min x 3', 'Methylprednisolone 60mg IV q6h', 'Oxygen via nasal cannula titrate SpO2 > 92%', 'Peak Expiratory Flow Rate (PEFR) pre/post tx', 'Chest X-Ray 1-view stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 56,
    },
    "ORD-ASTHMA-V12": {
        "order_set_id": "ORD-ASTHMA-V12",
        "title": "Acute Asthma Exacerbation Protocol (Protocol Pathway 12)",
        "department": "Pulmonology",
        "standard_orders": ['Albuterol 2.5mg / Ipratropium 0.5mg nebulized q20min x 3', 'Methylprednisolone 60mg IV q6h', 'Oxygen via nasal cannula titrate SpO2 > 92%', 'Peak Expiratory Flow Rate (PEFR) pre/post tx', 'Chest X-Ray 1-view stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 60,
    },
    "ORD-ASTHMA-V13": {
        "order_set_id": "ORD-ASTHMA-V13",
        "title": "Acute Asthma Exacerbation Protocol (Protocol Pathway 13)",
        "department": "Pulmonology",
        "standard_orders": ['Albuterol 2.5mg / Ipratropium 0.5mg nebulized q20min x 3', 'Methylprednisolone 60mg IV q6h', 'Oxygen via nasal cannula titrate SpO2 > 92%', 'Peak Expiratory Flow Rate (PEFR) pre/post tx', 'Chest X-Ray 1-view stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 64,
    },
    "ORD-ASTHMA-V14": {
        "order_set_id": "ORD-ASTHMA-V14",
        "title": "Acute Asthma Exacerbation Protocol (Protocol Pathway 14)",
        "department": "Pulmonology",
        "standard_orders": ['Albuterol 2.5mg / Ipratropium 0.5mg nebulized q20min x 3', 'Methylprednisolone 60mg IV q6h', 'Oxygen via nasal cannula titrate SpO2 > 92%', 'Peak Expiratory Flow Rate (PEFR) pre/post tx', 'Chest X-Ray 1-view stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 68,
    },
    "ORD-ASTHMA-V15": {
        "order_set_id": "ORD-ASTHMA-V15",
        "title": "Acute Asthma Exacerbation Protocol (Protocol Pathway 15)",
        "department": "Pulmonology",
        "standard_orders": ['Albuterol 2.5mg / Ipratropium 0.5mg nebulized q20min x 3', 'Methylprednisolone 60mg IV q6h', 'Oxygen via nasal cannula titrate SpO2 > 92%', 'Peak Expiratory Flow Rate (PEFR) pre/post tx', 'Chest X-Ray 1-view stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 72,
    },
    "ORD-ASTHMA-V16": {
        "order_set_id": "ORD-ASTHMA-V16",
        "title": "Acute Asthma Exacerbation Protocol (Protocol Pathway 16)",
        "department": "Pulmonology",
        "standard_orders": ['Albuterol 2.5mg / Ipratropium 0.5mg nebulized q20min x 3', 'Methylprednisolone 60mg IV q6h', 'Oxygen via nasal cannula titrate SpO2 > 92%', 'Peak Expiratory Flow Rate (PEFR) pre/post tx', 'Chest X-Ray 1-view stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 76,
    },
    "ORD-ASTHMA-V17": {
        "order_set_id": "ORD-ASTHMA-V17",
        "title": "Acute Asthma Exacerbation Protocol (Protocol Pathway 17)",
        "department": "Pulmonology",
        "standard_orders": ['Albuterol 2.5mg / Ipratropium 0.5mg nebulized q20min x 3', 'Methylprednisolone 60mg IV q6h', 'Oxygen via nasal cannula titrate SpO2 > 92%', 'Peak Expiratory Flow Rate (PEFR) pre/post tx', 'Chest X-Ray 1-view stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 80,
    },
    "ORD-ASTHMA-V18": {
        "order_set_id": "ORD-ASTHMA-V18",
        "title": "Acute Asthma Exacerbation Protocol (Protocol Pathway 18)",
        "department": "Pulmonology",
        "standard_orders": ['Albuterol 2.5mg / Ipratropium 0.5mg nebulized q20min x 3', 'Methylprednisolone 60mg IV q6h', 'Oxygen via nasal cannula titrate SpO2 > 92%', 'Peak Expiratory Flow Rate (PEFR) pre/post tx', 'Chest X-Ray 1-view stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 84,
    },
    "ORD-ASTHMA-V19": {
        "order_set_id": "ORD-ASTHMA-V19",
        "title": "Acute Asthma Exacerbation Protocol (Protocol Pathway 19)",
        "department": "Pulmonology",
        "standard_orders": ['Albuterol 2.5mg / Ipratropium 0.5mg nebulized q20min x 3', 'Methylprednisolone 60mg IV q6h', 'Oxygen via nasal cannula titrate SpO2 > 92%', 'Peak Expiratory Flow Rate (PEFR) pre/post tx', 'Chest X-Ray 1-view stat'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 88,
    },
    "ORD-STROKE-V01": {
        "order_set_id": "ORD-STROKE-V01",
        "title": "Acute Ischemic Stroke Thrombolysis Pathway (Protocol Pathway 1)",
        "department": "Neurology",
        "standard_orders": ['Tenecteplase 0.25 mg/kg IV bolus (if within 4.5h window)', 'Non-contrast Head CT stat', 'CT Angiography Head & Neck', 'NIH Stroke Scale (NIHSS) q15min', 'Maintain BP < 180/105 mmHg with Labetalol/Nicardipine'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 16,
    },
    "ORD-STROKE-V02": {
        "order_set_id": "ORD-STROKE-V02",
        "title": "Acute Ischemic Stroke Thrombolysis Pathway (Protocol Pathway 2)",
        "department": "Neurology",
        "standard_orders": ['Tenecteplase 0.25 mg/kg IV bolus (if within 4.5h window)', 'Non-contrast Head CT stat', 'CT Angiography Head & Neck', 'NIH Stroke Scale (NIHSS) q15min', 'Maintain BP < 180/105 mmHg with Labetalol/Nicardipine'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 20,
    },
    "ORD-STROKE-V03": {
        "order_set_id": "ORD-STROKE-V03",
        "title": "Acute Ischemic Stroke Thrombolysis Pathway (Protocol Pathway 3)",
        "department": "Neurology",
        "standard_orders": ['Tenecteplase 0.25 mg/kg IV bolus (if within 4.5h window)', 'Non-contrast Head CT stat', 'CT Angiography Head & Neck', 'NIH Stroke Scale (NIHSS) q15min', 'Maintain BP < 180/105 mmHg with Labetalol/Nicardipine'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 24,
    },
    "ORD-STROKE-V04": {
        "order_set_id": "ORD-STROKE-V04",
        "title": "Acute Ischemic Stroke Thrombolysis Pathway (Protocol Pathway 4)",
        "department": "Neurology",
        "standard_orders": ['Tenecteplase 0.25 mg/kg IV bolus (if within 4.5h window)', 'Non-contrast Head CT stat', 'CT Angiography Head & Neck', 'NIH Stroke Scale (NIHSS) q15min', 'Maintain BP < 180/105 mmHg with Labetalol/Nicardipine'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 28,
    },
    "ORD-STROKE-V05": {
        "order_set_id": "ORD-STROKE-V05",
        "title": "Acute Ischemic Stroke Thrombolysis Pathway (Protocol Pathway 5)",
        "department": "Neurology",
        "standard_orders": ['Tenecteplase 0.25 mg/kg IV bolus (if within 4.5h window)', 'Non-contrast Head CT stat', 'CT Angiography Head & Neck', 'NIH Stroke Scale (NIHSS) q15min', 'Maintain BP < 180/105 mmHg with Labetalol/Nicardipine'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 32,
    },
    "ORD-STROKE-V06": {
        "order_set_id": "ORD-STROKE-V06",
        "title": "Acute Ischemic Stroke Thrombolysis Pathway (Protocol Pathway 6)",
        "department": "Neurology",
        "standard_orders": ['Tenecteplase 0.25 mg/kg IV bolus (if within 4.5h window)', 'Non-contrast Head CT stat', 'CT Angiography Head & Neck', 'NIH Stroke Scale (NIHSS) q15min', 'Maintain BP < 180/105 mmHg with Labetalol/Nicardipine'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 36,
    },
    "ORD-STROKE-V07": {
        "order_set_id": "ORD-STROKE-V07",
        "title": "Acute Ischemic Stroke Thrombolysis Pathway (Protocol Pathway 7)",
        "department": "Neurology",
        "standard_orders": ['Tenecteplase 0.25 mg/kg IV bolus (if within 4.5h window)', 'Non-contrast Head CT stat', 'CT Angiography Head & Neck', 'NIH Stroke Scale (NIHSS) q15min', 'Maintain BP < 180/105 mmHg with Labetalol/Nicardipine'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 40,
    },
    "ORD-STROKE-V08": {
        "order_set_id": "ORD-STROKE-V08",
        "title": "Acute Ischemic Stroke Thrombolysis Pathway (Protocol Pathway 8)",
        "department": "Neurology",
        "standard_orders": ['Tenecteplase 0.25 mg/kg IV bolus (if within 4.5h window)', 'Non-contrast Head CT stat', 'CT Angiography Head & Neck', 'NIH Stroke Scale (NIHSS) q15min', 'Maintain BP < 180/105 mmHg with Labetalol/Nicardipine'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 44,
    },
    "ORD-STROKE-V09": {
        "order_set_id": "ORD-STROKE-V09",
        "title": "Acute Ischemic Stroke Thrombolysis Pathway (Protocol Pathway 9)",
        "department": "Neurology",
        "standard_orders": ['Tenecteplase 0.25 mg/kg IV bolus (if within 4.5h window)', 'Non-contrast Head CT stat', 'CT Angiography Head & Neck', 'NIH Stroke Scale (NIHSS) q15min', 'Maintain BP < 180/105 mmHg with Labetalol/Nicardipine'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 48,
    },
    "ORD-STROKE-V10": {
        "order_set_id": "ORD-STROKE-V10",
        "title": "Acute Ischemic Stroke Thrombolysis Pathway (Protocol Pathway 10)",
        "department": "Neurology",
        "standard_orders": ['Tenecteplase 0.25 mg/kg IV bolus (if within 4.5h window)', 'Non-contrast Head CT stat', 'CT Angiography Head & Neck', 'NIH Stroke Scale (NIHSS) q15min', 'Maintain BP < 180/105 mmHg with Labetalol/Nicardipine'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 52,
    },
    "ORD-STROKE-V11": {
        "order_set_id": "ORD-STROKE-V11",
        "title": "Acute Ischemic Stroke Thrombolysis Pathway (Protocol Pathway 11)",
        "department": "Neurology",
        "standard_orders": ['Tenecteplase 0.25 mg/kg IV bolus (if within 4.5h window)', 'Non-contrast Head CT stat', 'CT Angiography Head & Neck', 'NIH Stroke Scale (NIHSS) q15min', 'Maintain BP < 180/105 mmHg with Labetalol/Nicardipine'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 56,
    },
    "ORD-STROKE-V12": {
        "order_set_id": "ORD-STROKE-V12",
        "title": "Acute Ischemic Stroke Thrombolysis Pathway (Protocol Pathway 12)",
        "department": "Neurology",
        "standard_orders": ['Tenecteplase 0.25 mg/kg IV bolus (if within 4.5h window)', 'Non-contrast Head CT stat', 'CT Angiography Head & Neck', 'NIH Stroke Scale (NIHSS) q15min', 'Maintain BP < 180/105 mmHg with Labetalol/Nicardipine'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 60,
    },
    "ORD-STROKE-V13": {
        "order_set_id": "ORD-STROKE-V13",
        "title": "Acute Ischemic Stroke Thrombolysis Pathway (Protocol Pathway 13)",
        "department": "Neurology",
        "standard_orders": ['Tenecteplase 0.25 mg/kg IV bolus (if within 4.5h window)', 'Non-contrast Head CT stat', 'CT Angiography Head & Neck', 'NIH Stroke Scale (NIHSS) q15min', 'Maintain BP < 180/105 mmHg with Labetalol/Nicardipine'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 64,
    },
    "ORD-STROKE-V14": {
        "order_set_id": "ORD-STROKE-V14",
        "title": "Acute Ischemic Stroke Thrombolysis Pathway (Protocol Pathway 14)",
        "department": "Neurology",
        "standard_orders": ['Tenecteplase 0.25 mg/kg IV bolus (if within 4.5h window)', 'Non-contrast Head CT stat', 'CT Angiography Head & Neck', 'NIH Stroke Scale (NIHSS) q15min', 'Maintain BP < 180/105 mmHg with Labetalol/Nicardipine'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 68,
    },
    "ORD-STROKE-V15": {
        "order_set_id": "ORD-STROKE-V15",
        "title": "Acute Ischemic Stroke Thrombolysis Pathway (Protocol Pathway 15)",
        "department": "Neurology",
        "standard_orders": ['Tenecteplase 0.25 mg/kg IV bolus (if within 4.5h window)', 'Non-contrast Head CT stat', 'CT Angiography Head & Neck', 'NIH Stroke Scale (NIHSS) q15min', 'Maintain BP < 180/105 mmHg with Labetalol/Nicardipine'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 72,
    },
    "ORD-STROKE-V16": {
        "order_set_id": "ORD-STROKE-V16",
        "title": "Acute Ischemic Stroke Thrombolysis Pathway (Protocol Pathway 16)",
        "department": "Neurology",
        "standard_orders": ['Tenecteplase 0.25 mg/kg IV bolus (if within 4.5h window)', 'Non-contrast Head CT stat', 'CT Angiography Head & Neck', 'NIH Stroke Scale (NIHSS) q15min', 'Maintain BP < 180/105 mmHg with Labetalol/Nicardipine'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 76,
    },
    "ORD-STROKE-V17": {
        "order_set_id": "ORD-STROKE-V17",
        "title": "Acute Ischemic Stroke Thrombolysis Pathway (Protocol Pathway 17)",
        "department": "Neurology",
        "standard_orders": ['Tenecteplase 0.25 mg/kg IV bolus (if within 4.5h window)', 'Non-contrast Head CT stat', 'CT Angiography Head & Neck', 'NIH Stroke Scale (NIHSS) q15min', 'Maintain BP < 180/105 mmHg with Labetalol/Nicardipine'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 80,
    },
    "ORD-STROKE-V18": {
        "order_set_id": "ORD-STROKE-V18",
        "title": "Acute Ischemic Stroke Thrombolysis Pathway (Protocol Pathway 18)",
        "department": "Neurology",
        "standard_orders": ['Tenecteplase 0.25 mg/kg IV bolus (if within 4.5h window)', 'Non-contrast Head CT stat', 'CT Angiography Head & Neck', 'NIH Stroke Scale (NIHSS) q15min', 'Maintain BP < 180/105 mmHg with Labetalol/Nicardipine'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 84,
    },
    "ORD-STROKE-V19": {
        "order_set_id": "ORD-STROKE-V19",
        "title": "Acute Ischemic Stroke Thrombolysis Pathway (Protocol Pathway 19)",
        "department": "Neurology",
        "standard_orders": ['Tenecteplase 0.25 mg/kg IV bolus (if within 4.5h window)', 'Non-contrast Head CT stat', 'CT Angiography Head & Neck', 'NIH Stroke Scale (NIHSS) q15min', 'Maintain BP < 180/105 mmHg with Labetalol/Nicardipine'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 88,
    },
    "ORD-HF-DECOMP-V01": {
        "order_set_id": "ORD-HF-DECOMP-V01",
        "title": "Acute Decompensated Heart Failure (Protocol Pathway 1)",
        "department": "Cardiology",
        "standard_orders": ['Furosemide IV bolus (2x home dose)', 'Strict Input & Output fluid charting', 'Daily morning weight', '2-gram Sodium restricted diet', 'BNP / NT-proBNP stat', 'Telemetry monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 16,
    },
    "ORD-HF-DECOMP-V02": {
        "order_set_id": "ORD-HF-DECOMP-V02",
        "title": "Acute Decompensated Heart Failure (Protocol Pathway 2)",
        "department": "Cardiology",
        "standard_orders": ['Furosemide IV bolus (2x home dose)', 'Strict Input & Output fluid charting', 'Daily morning weight', '2-gram Sodium restricted diet', 'BNP / NT-proBNP stat', 'Telemetry monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 20,
    },
    "ORD-HF-DECOMP-V03": {
        "order_set_id": "ORD-HF-DECOMP-V03",
        "title": "Acute Decompensated Heart Failure (Protocol Pathway 3)",
        "department": "Cardiology",
        "standard_orders": ['Furosemide IV bolus (2x home dose)', 'Strict Input & Output fluid charting', 'Daily morning weight', '2-gram Sodium restricted diet', 'BNP / NT-proBNP stat', 'Telemetry monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 24,
    },
    "ORD-HF-DECOMP-V04": {
        "order_set_id": "ORD-HF-DECOMP-V04",
        "title": "Acute Decompensated Heart Failure (Protocol Pathway 4)",
        "department": "Cardiology",
        "standard_orders": ['Furosemide IV bolus (2x home dose)', 'Strict Input & Output fluid charting', 'Daily morning weight', '2-gram Sodium restricted diet', 'BNP / NT-proBNP stat', 'Telemetry monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 28,
    },
    "ORD-HF-DECOMP-V05": {
        "order_set_id": "ORD-HF-DECOMP-V05",
        "title": "Acute Decompensated Heart Failure (Protocol Pathway 5)",
        "department": "Cardiology",
        "standard_orders": ['Furosemide IV bolus (2x home dose)', 'Strict Input & Output fluid charting', 'Daily morning weight', '2-gram Sodium restricted diet', 'BNP / NT-proBNP stat', 'Telemetry monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 32,
    },
    "ORD-HF-DECOMP-V06": {
        "order_set_id": "ORD-HF-DECOMP-V06",
        "title": "Acute Decompensated Heart Failure (Protocol Pathway 6)",
        "department": "Cardiology",
        "standard_orders": ['Furosemide IV bolus (2x home dose)', 'Strict Input & Output fluid charting', 'Daily morning weight', '2-gram Sodium restricted diet', 'BNP / NT-proBNP stat', 'Telemetry monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 36,
    },
    "ORD-HF-DECOMP-V07": {
        "order_set_id": "ORD-HF-DECOMP-V07",
        "title": "Acute Decompensated Heart Failure (Protocol Pathway 7)",
        "department": "Cardiology",
        "standard_orders": ['Furosemide IV bolus (2x home dose)', 'Strict Input & Output fluid charting', 'Daily morning weight', '2-gram Sodium restricted diet', 'BNP / NT-proBNP stat', 'Telemetry monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 40,
    },
    "ORD-HF-DECOMP-V08": {
        "order_set_id": "ORD-HF-DECOMP-V08",
        "title": "Acute Decompensated Heart Failure (Protocol Pathway 8)",
        "department": "Cardiology",
        "standard_orders": ['Furosemide IV bolus (2x home dose)', 'Strict Input & Output fluid charting', 'Daily morning weight', '2-gram Sodium restricted diet', 'BNP / NT-proBNP stat', 'Telemetry monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 44,
    },
    "ORD-HF-DECOMP-V09": {
        "order_set_id": "ORD-HF-DECOMP-V09",
        "title": "Acute Decompensated Heart Failure (Protocol Pathway 9)",
        "department": "Cardiology",
        "standard_orders": ['Furosemide IV bolus (2x home dose)', 'Strict Input & Output fluid charting', 'Daily morning weight', '2-gram Sodium restricted diet', 'BNP / NT-proBNP stat', 'Telemetry monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 48,
    },
    "ORD-HF-DECOMP-V10": {
        "order_set_id": "ORD-HF-DECOMP-V10",
        "title": "Acute Decompensated Heart Failure (Protocol Pathway 10)",
        "department": "Cardiology",
        "standard_orders": ['Furosemide IV bolus (2x home dose)', 'Strict Input & Output fluid charting', 'Daily morning weight', '2-gram Sodium restricted diet', 'BNP / NT-proBNP stat', 'Telemetry monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 52,
    },
    "ORD-HF-DECOMP-V11": {
        "order_set_id": "ORD-HF-DECOMP-V11",
        "title": "Acute Decompensated Heart Failure (Protocol Pathway 11)",
        "department": "Cardiology",
        "standard_orders": ['Furosemide IV bolus (2x home dose)', 'Strict Input & Output fluid charting', 'Daily morning weight', '2-gram Sodium restricted diet', 'BNP / NT-proBNP stat', 'Telemetry monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 56,
    },
    "ORD-HF-DECOMP-V12": {
        "order_set_id": "ORD-HF-DECOMP-V12",
        "title": "Acute Decompensated Heart Failure (Protocol Pathway 12)",
        "department": "Cardiology",
        "standard_orders": ['Furosemide IV bolus (2x home dose)', 'Strict Input & Output fluid charting', 'Daily morning weight', '2-gram Sodium restricted diet', 'BNP / NT-proBNP stat', 'Telemetry monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 60,
    },
    "ORD-HF-DECOMP-V13": {
        "order_set_id": "ORD-HF-DECOMP-V13",
        "title": "Acute Decompensated Heart Failure (Protocol Pathway 13)",
        "department": "Cardiology",
        "standard_orders": ['Furosemide IV bolus (2x home dose)', 'Strict Input & Output fluid charting', 'Daily morning weight', '2-gram Sodium restricted diet', 'BNP / NT-proBNP stat', 'Telemetry monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 64,
    },
    "ORD-HF-DECOMP-V14": {
        "order_set_id": "ORD-HF-DECOMP-V14",
        "title": "Acute Decompensated Heart Failure (Protocol Pathway 14)",
        "department": "Cardiology",
        "standard_orders": ['Furosemide IV bolus (2x home dose)', 'Strict Input & Output fluid charting', 'Daily morning weight', '2-gram Sodium restricted diet', 'BNP / NT-proBNP stat', 'Telemetry monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 68,
    },
    "ORD-HF-DECOMP-V15": {
        "order_set_id": "ORD-HF-DECOMP-V15",
        "title": "Acute Decompensated Heart Failure (Protocol Pathway 15)",
        "department": "Cardiology",
        "standard_orders": ['Furosemide IV bolus (2x home dose)', 'Strict Input & Output fluid charting', 'Daily morning weight', '2-gram Sodium restricted diet', 'BNP / NT-proBNP stat', 'Telemetry monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 72,
    },
    "ORD-HF-DECOMP-V16": {
        "order_set_id": "ORD-HF-DECOMP-V16",
        "title": "Acute Decompensated Heart Failure (Protocol Pathway 16)",
        "department": "Cardiology",
        "standard_orders": ['Furosemide IV bolus (2x home dose)', 'Strict Input & Output fluid charting', 'Daily morning weight', '2-gram Sodium restricted diet', 'BNP / NT-proBNP stat', 'Telemetry monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 76,
    },
    "ORD-HF-DECOMP-V17": {
        "order_set_id": "ORD-HF-DECOMP-V17",
        "title": "Acute Decompensated Heart Failure (Protocol Pathway 17)",
        "department": "Cardiology",
        "standard_orders": ['Furosemide IV bolus (2x home dose)', 'Strict Input & Output fluid charting', 'Daily morning weight', '2-gram Sodium restricted diet', 'BNP / NT-proBNP stat', 'Telemetry monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 80,
    },
    "ORD-HF-DECOMP-V18": {
        "order_set_id": "ORD-HF-DECOMP-V18",
        "title": "Acute Decompensated Heart Failure (Protocol Pathway 18)",
        "department": "Cardiology",
        "standard_orders": ['Furosemide IV bolus (2x home dose)', 'Strict Input & Output fluid charting', 'Daily morning weight', '2-gram Sodium restricted diet', 'BNP / NT-proBNP stat', 'Telemetry monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 84,
    },
    "ORD-HF-DECOMP-V19": {
        "order_set_id": "ORD-HF-DECOMP-V19",
        "title": "Acute Decompensated Heart Failure (Protocol Pathway 19)",
        "department": "Cardiology",
        "standard_orders": ['Furosemide IV bolus (2x home dose)', 'Strict Input & Output fluid charting', 'Daily morning weight', '2-gram Sodium restricted diet', 'BNP / NT-proBNP stat', 'Telemetry monitoring'],
        "mandatory_checks": [
            "Verify patient allergies in MPI",
            "Screen for renal impairment and CrCl < 30 mL/min",
            "Confirm active consent signature",
            "Validate with clinical pharmacist",
        ],
        "is_active_pathway": True,
        "recommended_monitoring_hours": 88,
    },
}
