"""
MediCore Nexus - DEA Controlled Substances Vault (Schedule II-V)
Dual-witness biometric authentication, perpetual blind count reconciliation,
and DEA Form 222 electronic registry (CSOS).
"""

from typing import Dict, List, Any
from datetime import datetime, timezone
import uuid

CONTROLLED_SUBSTANCES_VAULT_REGISTRY: Dict[str, Dict[str, Any]] = {
    "SCH2-OXY-V01": {
        "vault_item_id": "SCH2-OXY-V01",
        "substance_name": "Oxycodone HCl 10mg / 20mg Tablets (Vault Lot 1)",
        "dea_schedule": "Schedule II",
        "security_policy": "High potential for abuse; severe psychological or physical dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 70,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0001",
        "vault_storage_compartment": "Safe-Alpha-Drawer-1",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-OXY-V02": {
        "vault_item_id": "SCH2-OXY-V02",
        "substance_name": "Oxycodone HCl 10mg / 20mg Tablets (Vault Lot 2)",
        "dea_schedule": "Schedule II",
        "security_policy": "High potential for abuse; severe psychological or physical dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 120,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0002",
        "vault_storage_compartment": "Safe-Alpha-Drawer-2",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-OXY-V03": {
        "vault_item_id": "SCH2-OXY-V03",
        "substance_name": "Oxycodone HCl 10mg / 20mg Tablets (Vault Lot 3)",
        "dea_schedule": "Schedule II",
        "security_policy": "High potential for abuse; severe psychological or physical dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 170,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0003",
        "vault_storage_compartment": "Safe-Alpha-Drawer-3",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-OXY-V04": {
        "vault_item_id": "SCH2-OXY-V04",
        "substance_name": "Oxycodone HCl 10mg / 20mg Tablets (Vault Lot 4)",
        "dea_schedule": "Schedule II",
        "security_policy": "High potential for abuse; severe psychological or physical dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 220,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0004",
        "vault_storage_compartment": "Safe-Alpha-Drawer-4",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-OXY-V05": {
        "vault_item_id": "SCH2-OXY-V05",
        "substance_name": "Oxycodone HCl 10mg / 20mg Tablets (Vault Lot 5)",
        "dea_schedule": "Schedule II",
        "security_policy": "High potential for abuse; severe psychological or physical dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 270,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0005",
        "vault_storage_compartment": "Safe-Alpha-Drawer-5",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-OXY-V06": {
        "vault_item_id": "SCH2-OXY-V06",
        "substance_name": "Oxycodone HCl 10mg / 20mg Tablets (Vault Lot 6)",
        "dea_schedule": "Schedule II",
        "security_policy": "High potential for abuse; severe psychological or physical dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 320,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0006",
        "vault_storage_compartment": "Safe-Alpha-Drawer-6",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-OXY-V07": {
        "vault_item_id": "SCH2-OXY-V07",
        "substance_name": "Oxycodone HCl 10mg / 20mg Tablets (Vault Lot 7)",
        "dea_schedule": "Schedule II",
        "security_policy": "High potential for abuse; severe psychological or physical dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 370,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0007",
        "vault_storage_compartment": "Safe-Alpha-Drawer-7",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-OXY-V08": {
        "vault_item_id": "SCH2-OXY-V08",
        "substance_name": "Oxycodone HCl 10mg / 20mg Tablets (Vault Lot 8)",
        "dea_schedule": "Schedule II",
        "security_policy": "High potential for abuse; severe psychological or physical dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 420,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0008",
        "vault_storage_compartment": "Safe-Alpha-Drawer-8",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-OXY-V09": {
        "vault_item_id": "SCH2-OXY-V09",
        "substance_name": "Oxycodone HCl 10mg / 20mg Tablets (Vault Lot 9)",
        "dea_schedule": "Schedule II",
        "security_policy": "High potential for abuse; severe psychological or physical dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 470,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0009",
        "vault_storage_compartment": "Safe-Alpha-Drawer-9",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-OXY-V10": {
        "vault_item_id": "SCH2-OXY-V10",
        "substance_name": "Oxycodone HCl 10mg / 20mg Tablets (Vault Lot 10)",
        "dea_schedule": "Schedule II",
        "security_policy": "High potential for abuse; severe psychological or physical dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 520,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0010",
        "vault_storage_compartment": "Safe-Alpha-Drawer-10",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-OXY-V11": {
        "vault_item_id": "SCH2-OXY-V11",
        "substance_name": "Oxycodone HCl 10mg / 20mg Tablets (Vault Lot 11)",
        "dea_schedule": "Schedule II",
        "security_policy": "High potential for abuse; severe psychological or physical dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 570,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0011",
        "vault_storage_compartment": "Safe-Alpha-Drawer-11",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-OXY-V12": {
        "vault_item_id": "SCH2-OXY-V12",
        "substance_name": "Oxycodone HCl 10mg / 20mg Tablets (Vault Lot 12)",
        "dea_schedule": "Schedule II",
        "security_policy": "High potential for abuse; severe psychological or physical dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 620,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0012",
        "vault_storage_compartment": "Safe-Alpha-Drawer-12",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-OXY-V13": {
        "vault_item_id": "SCH2-OXY-V13",
        "substance_name": "Oxycodone HCl 10mg / 20mg Tablets (Vault Lot 13)",
        "dea_schedule": "Schedule II",
        "security_policy": "High potential for abuse; severe psychological or physical dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 670,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0013",
        "vault_storage_compartment": "Safe-Alpha-Drawer-13",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-OXY-V14": {
        "vault_item_id": "SCH2-OXY-V14",
        "substance_name": "Oxycodone HCl 10mg / 20mg Tablets (Vault Lot 14)",
        "dea_schedule": "Schedule II",
        "security_policy": "High potential for abuse; severe psychological or physical dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 720,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0014",
        "vault_storage_compartment": "Safe-Alpha-Drawer-14",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-FENT-V01": {
        "vault_item_id": "SCH2-FENT-V01",
        "substance_name": "Fentanyl Citrate 50 mcg/mL Injection (Vault Lot 1)",
        "dea_schedule": "Schedule II",
        "security_policy": "Requires dual-nurse witness for all waste disposal and administration",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 70,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0001",
        "vault_storage_compartment": "Safe-Alpha-Drawer-1",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-FENT-V02": {
        "vault_item_id": "SCH2-FENT-V02",
        "substance_name": "Fentanyl Citrate 50 mcg/mL Injection (Vault Lot 2)",
        "dea_schedule": "Schedule II",
        "security_policy": "Requires dual-nurse witness for all waste disposal and administration",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 120,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0002",
        "vault_storage_compartment": "Safe-Alpha-Drawer-2",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-FENT-V03": {
        "vault_item_id": "SCH2-FENT-V03",
        "substance_name": "Fentanyl Citrate 50 mcg/mL Injection (Vault Lot 3)",
        "dea_schedule": "Schedule II",
        "security_policy": "Requires dual-nurse witness for all waste disposal and administration",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 170,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0003",
        "vault_storage_compartment": "Safe-Alpha-Drawer-3",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-FENT-V04": {
        "vault_item_id": "SCH2-FENT-V04",
        "substance_name": "Fentanyl Citrate 50 mcg/mL Injection (Vault Lot 4)",
        "dea_schedule": "Schedule II",
        "security_policy": "Requires dual-nurse witness for all waste disposal and administration",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 220,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0004",
        "vault_storage_compartment": "Safe-Alpha-Drawer-4",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-FENT-V05": {
        "vault_item_id": "SCH2-FENT-V05",
        "substance_name": "Fentanyl Citrate 50 mcg/mL Injection (Vault Lot 5)",
        "dea_schedule": "Schedule II",
        "security_policy": "Requires dual-nurse witness for all waste disposal and administration",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 270,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0005",
        "vault_storage_compartment": "Safe-Alpha-Drawer-5",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-FENT-V06": {
        "vault_item_id": "SCH2-FENT-V06",
        "substance_name": "Fentanyl Citrate 50 mcg/mL Injection (Vault Lot 6)",
        "dea_schedule": "Schedule II",
        "security_policy": "Requires dual-nurse witness for all waste disposal and administration",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 320,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0006",
        "vault_storage_compartment": "Safe-Alpha-Drawer-6",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-FENT-V07": {
        "vault_item_id": "SCH2-FENT-V07",
        "substance_name": "Fentanyl Citrate 50 mcg/mL Injection (Vault Lot 7)",
        "dea_schedule": "Schedule II",
        "security_policy": "Requires dual-nurse witness for all waste disposal and administration",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 370,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0007",
        "vault_storage_compartment": "Safe-Alpha-Drawer-7",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-FENT-V08": {
        "vault_item_id": "SCH2-FENT-V08",
        "substance_name": "Fentanyl Citrate 50 mcg/mL Injection (Vault Lot 8)",
        "dea_schedule": "Schedule II",
        "security_policy": "Requires dual-nurse witness for all waste disposal and administration",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 420,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0008",
        "vault_storage_compartment": "Safe-Alpha-Drawer-8",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-FENT-V09": {
        "vault_item_id": "SCH2-FENT-V09",
        "substance_name": "Fentanyl Citrate 50 mcg/mL Injection (Vault Lot 9)",
        "dea_schedule": "Schedule II",
        "security_policy": "Requires dual-nurse witness for all waste disposal and administration",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 470,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0009",
        "vault_storage_compartment": "Safe-Alpha-Drawer-9",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-FENT-V10": {
        "vault_item_id": "SCH2-FENT-V10",
        "substance_name": "Fentanyl Citrate 50 mcg/mL Injection (Vault Lot 10)",
        "dea_schedule": "Schedule II",
        "security_policy": "Requires dual-nurse witness for all waste disposal and administration",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 520,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0010",
        "vault_storage_compartment": "Safe-Alpha-Drawer-10",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-FENT-V11": {
        "vault_item_id": "SCH2-FENT-V11",
        "substance_name": "Fentanyl Citrate 50 mcg/mL Injection (Vault Lot 11)",
        "dea_schedule": "Schedule II",
        "security_policy": "Requires dual-nurse witness for all waste disposal and administration",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 570,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0011",
        "vault_storage_compartment": "Safe-Alpha-Drawer-11",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-FENT-V12": {
        "vault_item_id": "SCH2-FENT-V12",
        "substance_name": "Fentanyl Citrate 50 mcg/mL Injection (Vault Lot 12)",
        "dea_schedule": "Schedule II",
        "security_policy": "Requires dual-nurse witness for all waste disposal and administration",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 620,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0012",
        "vault_storage_compartment": "Safe-Alpha-Drawer-12",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-FENT-V13": {
        "vault_item_id": "SCH2-FENT-V13",
        "substance_name": "Fentanyl Citrate 50 mcg/mL Injection (Vault Lot 13)",
        "dea_schedule": "Schedule II",
        "security_policy": "Requires dual-nurse witness for all waste disposal and administration",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 670,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0013",
        "vault_storage_compartment": "Safe-Alpha-Drawer-13",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-FENT-V14": {
        "vault_item_id": "SCH2-FENT-V14",
        "substance_name": "Fentanyl Citrate 50 mcg/mL Injection (Vault Lot 14)",
        "dea_schedule": "Schedule II",
        "security_policy": "Requires dual-nurse witness for all waste disposal and administration",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 720,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0014",
        "vault_storage_compartment": "Safe-Alpha-Drawer-14",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-MORPH-V01": {
        "vault_item_id": "SCH2-MORPH-V01",
        "substance_name": "Morphine Sulfate 15mg ER Tablets (Vault Lot 1)",
        "dea_schedule": "Schedule II",
        "security_policy": "Continuous biometric audit logging and blind perpetual balance count",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 70,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0001",
        "vault_storage_compartment": "Safe-Alpha-Drawer-1",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-MORPH-V02": {
        "vault_item_id": "SCH2-MORPH-V02",
        "substance_name": "Morphine Sulfate 15mg ER Tablets (Vault Lot 2)",
        "dea_schedule": "Schedule II",
        "security_policy": "Continuous biometric audit logging and blind perpetual balance count",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 120,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0002",
        "vault_storage_compartment": "Safe-Alpha-Drawer-2",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-MORPH-V03": {
        "vault_item_id": "SCH2-MORPH-V03",
        "substance_name": "Morphine Sulfate 15mg ER Tablets (Vault Lot 3)",
        "dea_schedule": "Schedule II",
        "security_policy": "Continuous biometric audit logging and blind perpetual balance count",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 170,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0003",
        "vault_storage_compartment": "Safe-Alpha-Drawer-3",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-MORPH-V04": {
        "vault_item_id": "SCH2-MORPH-V04",
        "substance_name": "Morphine Sulfate 15mg ER Tablets (Vault Lot 4)",
        "dea_schedule": "Schedule II",
        "security_policy": "Continuous biometric audit logging and blind perpetual balance count",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 220,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0004",
        "vault_storage_compartment": "Safe-Alpha-Drawer-4",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-MORPH-V05": {
        "vault_item_id": "SCH2-MORPH-V05",
        "substance_name": "Morphine Sulfate 15mg ER Tablets (Vault Lot 5)",
        "dea_schedule": "Schedule II",
        "security_policy": "Continuous biometric audit logging and blind perpetual balance count",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 270,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0005",
        "vault_storage_compartment": "Safe-Alpha-Drawer-5",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-MORPH-V06": {
        "vault_item_id": "SCH2-MORPH-V06",
        "substance_name": "Morphine Sulfate 15mg ER Tablets (Vault Lot 6)",
        "dea_schedule": "Schedule II",
        "security_policy": "Continuous biometric audit logging and blind perpetual balance count",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 320,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0006",
        "vault_storage_compartment": "Safe-Alpha-Drawer-6",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-MORPH-V07": {
        "vault_item_id": "SCH2-MORPH-V07",
        "substance_name": "Morphine Sulfate 15mg ER Tablets (Vault Lot 7)",
        "dea_schedule": "Schedule II",
        "security_policy": "Continuous biometric audit logging and blind perpetual balance count",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 370,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0007",
        "vault_storage_compartment": "Safe-Alpha-Drawer-7",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-MORPH-V08": {
        "vault_item_id": "SCH2-MORPH-V08",
        "substance_name": "Morphine Sulfate 15mg ER Tablets (Vault Lot 8)",
        "dea_schedule": "Schedule II",
        "security_policy": "Continuous biometric audit logging and blind perpetual balance count",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 420,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0008",
        "vault_storage_compartment": "Safe-Alpha-Drawer-8",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-MORPH-V09": {
        "vault_item_id": "SCH2-MORPH-V09",
        "substance_name": "Morphine Sulfate 15mg ER Tablets (Vault Lot 9)",
        "dea_schedule": "Schedule II",
        "security_policy": "Continuous biometric audit logging and blind perpetual balance count",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 470,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0009",
        "vault_storage_compartment": "Safe-Alpha-Drawer-9",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-MORPH-V10": {
        "vault_item_id": "SCH2-MORPH-V10",
        "substance_name": "Morphine Sulfate 15mg ER Tablets (Vault Lot 10)",
        "dea_schedule": "Schedule II",
        "security_policy": "Continuous biometric audit logging and blind perpetual balance count",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 520,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0010",
        "vault_storage_compartment": "Safe-Alpha-Drawer-10",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-MORPH-V11": {
        "vault_item_id": "SCH2-MORPH-V11",
        "substance_name": "Morphine Sulfate 15mg ER Tablets (Vault Lot 11)",
        "dea_schedule": "Schedule II",
        "security_policy": "Continuous biometric audit logging and blind perpetual balance count",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 570,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0011",
        "vault_storage_compartment": "Safe-Alpha-Drawer-11",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-MORPH-V12": {
        "vault_item_id": "SCH2-MORPH-V12",
        "substance_name": "Morphine Sulfate 15mg ER Tablets (Vault Lot 12)",
        "dea_schedule": "Schedule II",
        "security_policy": "Continuous biometric audit logging and blind perpetual balance count",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 620,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0012",
        "vault_storage_compartment": "Safe-Alpha-Drawer-12",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-MORPH-V13": {
        "vault_item_id": "SCH2-MORPH-V13",
        "substance_name": "Morphine Sulfate 15mg ER Tablets (Vault Lot 13)",
        "dea_schedule": "Schedule II",
        "security_policy": "Continuous biometric audit logging and blind perpetual balance count",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 670,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0013",
        "vault_storage_compartment": "Safe-Alpha-Drawer-13",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-MORPH-V14": {
        "vault_item_id": "SCH2-MORPH-V14",
        "substance_name": "Morphine Sulfate 15mg ER Tablets (Vault Lot 14)",
        "dea_schedule": "Schedule II",
        "security_policy": "Continuous biometric audit logging and blind perpetual balance count",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 720,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0014",
        "vault_storage_compartment": "Safe-Alpha-Drawer-14",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-METH-V01": {
        "vault_item_id": "SCH2-METH-V01",
        "substance_name": "Methylphenidate HCl 20mg (Ritalin) (Vault Lot 1)",
        "dea_schedule": "Schedule II",
        "security_policy": "CNS Stimulant for ADHD / Narcolepsy; strictly tracked in vault",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 70,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0001",
        "vault_storage_compartment": "Safe-Alpha-Drawer-1",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-METH-V02": {
        "vault_item_id": "SCH2-METH-V02",
        "substance_name": "Methylphenidate HCl 20mg (Ritalin) (Vault Lot 2)",
        "dea_schedule": "Schedule II",
        "security_policy": "CNS Stimulant for ADHD / Narcolepsy; strictly tracked in vault",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 120,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0002",
        "vault_storage_compartment": "Safe-Alpha-Drawer-2",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-METH-V03": {
        "vault_item_id": "SCH2-METH-V03",
        "substance_name": "Methylphenidate HCl 20mg (Ritalin) (Vault Lot 3)",
        "dea_schedule": "Schedule II",
        "security_policy": "CNS Stimulant for ADHD / Narcolepsy; strictly tracked in vault",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 170,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0003",
        "vault_storage_compartment": "Safe-Alpha-Drawer-3",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-METH-V04": {
        "vault_item_id": "SCH2-METH-V04",
        "substance_name": "Methylphenidate HCl 20mg (Ritalin) (Vault Lot 4)",
        "dea_schedule": "Schedule II",
        "security_policy": "CNS Stimulant for ADHD / Narcolepsy; strictly tracked in vault",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 220,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0004",
        "vault_storage_compartment": "Safe-Alpha-Drawer-4",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-METH-V05": {
        "vault_item_id": "SCH2-METH-V05",
        "substance_name": "Methylphenidate HCl 20mg (Ritalin) (Vault Lot 5)",
        "dea_schedule": "Schedule II",
        "security_policy": "CNS Stimulant for ADHD / Narcolepsy; strictly tracked in vault",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 270,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0005",
        "vault_storage_compartment": "Safe-Alpha-Drawer-5",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-METH-V06": {
        "vault_item_id": "SCH2-METH-V06",
        "substance_name": "Methylphenidate HCl 20mg (Ritalin) (Vault Lot 6)",
        "dea_schedule": "Schedule II",
        "security_policy": "CNS Stimulant for ADHD / Narcolepsy; strictly tracked in vault",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 320,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0006",
        "vault_storage_compartment": "Safe-Alpha-Drawer-6",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-METH-V07": {
        "vault_item_id": "SCH2-METH-V07",
        "substance_name": "Methylphenidate HCl 20mg (Ritalin) (Vault Lot 7)",
        "dea_schedule": "Schedule II",
        "security_policy": "CNS Stimulant for ADHD / Narcolepsy; strictly tracked in vault",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 370,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0007",
        "vault_storage_compartment": "Safe-Alpha-Drawer-7",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-METH-V08": {
        "vault_item_id": "SCH2-METH-V08",
        "substance_name": "Methylphenidate HCl 20mg (Ritalin) (Vault Lot 8)",
        "dea_schedule": "Schedule II",
        "security_policy": "CNS Stimulant for ADHD / Narcolepsy; strictly tracked in vault",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 420,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0008",
        "vault_storage_compartment": "Safe-Alpha-Drawer-8",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-METH-V09": {
        "vault_item_id": "SCH2-METH-V09",
        "substance_name": "Methylphenidate HCl 20mg (Ritalin) (Vault Lot 9)",
        "dea_schedule": "Schedule II",
        "security_policy": "CNS Stimulant for ADHD / Narcolepsy; strictly tracked in vault",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 470,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0009",
        "vault_storage_compartment": "Safe-Alpha-Drawer-9",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-METH-V10": {
        "vault_item_id": "SCH2-METH-V10",
        "substance_name": "Methylphenidate HCl 20mg (Ritalin) (Vault Lot 10)",
        "dea_schedule": "Schedule II",
        "security_policy": "CNS Stimulant for ADHD / Narcolepsy; strictly tracked in vault",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 520,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0010",
        "vault_storage_compartment": "Safe-Alpha-Drawer-10",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-METH-V11": {
        "vault_item_id": "SCH2-METH-V11",
        "substance_name": "Methylphenidate HCl 20mg (Ritalin) (Vault Lot 11)",
        "dea_schedule": "Schedule II",
        "security_policy": "CNS Stimulant for ADHD / Narcolepsy; strictly tracked in vault",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 570,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0011",
        "vault_storage_compartment": "Safe-Alpha-Drawer-11",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-METH-V12": {
        "vault_item_id": "SCH2-METH-V12",
        "substance_name": "Methylphenidate HCl 20mg (Ritalin) (Vault Lot 12)",
        "dea_schedule": "Schedule II",
        "security_policy": "CNS Stimulant for ADHD / Narcolepsy; strictly tracked in vault",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 620,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0012",
        "vault_storage_compartment": "Safe-Alpha-Drawer-12",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-METH-V13": {
        "vault_item_id": "SCH2-METH-V13",
        "substance_name": "Methylphenidate HCl 20mg (Ritalin) (Vault Lot 13)",
        "dea_schedule": "Schedule II",
        "security_policy": "CNS Stimulant for ADHD / Narcolepsy; strictly tracked in vault",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 670,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0013",
        "vault_storage_compartment": "Safe-Alpha-Drawer-13",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH2-METH-V14": {
        "vault_item_id": "SCH2-METH-V14",
        "substance_name": "Methylphenidate HCl 20mg (Ritalin) (Vault Lot 14)",
        "dea_schedule": "Schedule II",
        "security_policy": "CNS Stimulant for ADHD / Narcolepsy; strictly tracked in vault",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 720,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH2-0014",
        "vault_storage_compartment": "Safe-Alpha-Drawer-14",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH3-CODE-V01": {
        "vault_item_id": "SCH3-CODE-V01",
        "substance_name": "Acetaminophen with Codeine #3 Tablets (Vault Lot 1)",
        "dea_schedule": "Schedule III",
        "security_policy": "Moderate to low potential for physical and psychological dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 70,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH3-0001",
        "vault_storage_compartment": "Safe-Alpha-Drawer-1",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH3-CODE-V02": {
        "vault_item_id": "SCH3-CODE-V02",
        "substance_name": "Acetaminophen with Codeine #3 Tablets (Vault Lot 2)",
        "dea_schedule": "Schedule III",
        "security_policy": "Moderate to low potential for physical and psychological dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 120,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH3-0002",
        "vault_storage_compartment": "Safe-Alpha-Drawer-2",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH3-CODE-V03": {
        "vault_item_id": "SCH3-CODE-V03",
        "substance_name": "Acetaminophen with Codeine #3 Tablets (Vault Lot 3)",
        "dea_schedule": "Schedule III",
        "security_policy": "Moderate to low potential for physical and psychological dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 170,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH3-0003",
        "vault_storage_compartment": "Safe-Alpha-Drawer-3",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH3-CODE-V04": {
        "vault_item_id": "SCH3-CODE-V04",
        "substance_name": "Acetaminophen with Codeine #3 Tablets (Vault Lot 4)",
        "dea_schedule": "Schedule III",
        "security_policy": "Moderate to low potential for physical and psychological dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 220,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH3-0004",
        "vault_storage_compartment": "Safe-Alpha-Drawer-4",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH3-CODE-V05": {
        "vault_item_id": "SCH3-CODE-V05",
        "substance_name": "Acetaminophen with Codeine #3 Tablets (Vault Lot 5)",
        "dea_schedule": "Schedule III",
        "security_policy": "Moderate to low potential for physical and psychological dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 270,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH3-0005",
        "vault_storage_compartment": "Safe-Alpha-Drawer-5",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH3-CODE-V06": {
        "vault_item_id": "SCH3-CODE-V06",
        "substance_name": "Acetaminophen with Codeine #3 Tablets (Vault Lot 6)",
        "dea_schedule": "Schedule III",
        "security_policy": "Moderate to low potential for physical and psychological dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 320,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH3-0006",
        "vault_storage_compartment": "Safe-Alpha-Drawer-6",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH3-CODE-V07": {
        "vault_item_id": "SCH3-CODE-V07",
        "substance_name": "Acetaminophen with Codeine #3 Tablets (Vault Lot 7)",
        "dea_schedule": "Schedule III",
        "security_policy": "Moderate to low potential for physical and psychological dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 370,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH3-0007",
        "vault_storage_compartment": "Safe-Alpha-Drawer-7",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH3-CODE-V08": {
        "vault_item_id": "SCH3-CODE-V08",
        "substance_name": "Acetaminophen with Codeine #3 Tablets (Vault Lot 8)",
        "dea_schedule": "Schedule III",
        "security_policy": "Moderate to low potential for physical and psychological dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 420,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH3-0008",
        "vault_storage_compartment": "Safe-Alpha-Drawer-8",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH3-CODE-V09": {
        "vault_item_id": "SCH3-CODE-V09",
        "substance_name": "Acetaminophen with Codeine #3 Tablets (Vault Lot 9)",
        "dea_schedule": "Schedule III",
        "security_policy": "Moderate to low potential for physical and psychological dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 470,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH3-0009",
        "vault_storage_compartment": "Safe-Alpha-Drawer-9",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH3-CODE-V10": {
        "vault_item_id": "SCH3-CODE-V10",
        "substance_name": "Acetaminophen with Codeine #3 Tablets (Vault Lot 10)",
        "dea_schedule": "Schedule III",
        "security_policy": "Moderate to low potential for physical and psychological dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 520,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH3-0010",
        "vault_storage_compartment": "Safe-Alpha-Drawer-10",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH3-CODE-V11": {
        "vault_item_id": "SCH3-CODE-V11",
        "substance_name": "Acetaminophen with Codeine #3 Tablets (Vault Lot 11)",
        "dea_schedule": "Schedule III",
        "security_policy": "Moderate to low potential for physical and psychological dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 570,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH3-0011",
        "vault_storage_compartment": "Safe-Alpha-Drawer-11",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH3-CODE-V12": {
        "vault_item_id": "SCH3-CODE-V12",
        "substance_name": "Acetaminophen with Codeine #3 Tablets (Vault Lot 12)",
        "dea_schedule": "Schedule III",
        "security_policy": "Moderate to low potential for physical and psychological dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 620,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH3-0012",
        "vault_storage_compartment": "Safe-Alpha-Drawer-12",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH3-CODE-V13": {
        "vault_item_id": "SCH3-CODE-V13",
        "substance_name": "Acetaminophen with Codeine #3 Tablets (Vault Lot 13)",
        "dea_schedule": "Schedule III",
        "security_policy": "Moderate to low potential for physical and psychological dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 670,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH3-0013",
        "vault_storage_compartment": "Safe-Alpha-Drawer-13",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH3-CODE-V14": {
        "vault_item_id": "SCH3-CODE-V14",
        "substance_name": "Acetaminophen with Codeine #3 Tablets (Vault Lot 14)",
        "dea_schedule": "Schedule III",
        "security_policy": "Moderate to low potential for physical and psychological dependence",
        "requires_dual_witness": True,
        "perpetual_inventory_balance": 720,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH3-0014",
        "vault_storage_compartment": "Safe-Alpha-Drawer-14",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-LORA-V01": {
        "vault_item_id": "SCH4-LORA-V01",
        "substance_name": "Lorazepam 1mg Tablets (Ativan) (Vault Lot 1)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Benzodiazepine; locked in secure automated dispensing cabinet",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 70,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0001",
        "vault_storage_compartment": "Safe-Alpha-Drawer-1",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-LORA-V02": {
        "vault_item_id": "SCH4-LORA-V02",
        "substance_name": "Lorazepam 1mg Tablets (Ativan) (Vault Lot 2)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Benzodiazepine; locked in secure automated dispensing cabinet",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 120,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0002",
        "vault_storage_compartment": "Safe-Alpha-Drawer-2",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-LORA-V03": {
        "vault_item_id": "SCH4-LORA-V03",
        "substance_name": "Lorazepam 1mg Tablets (Ativan) (Vault Lot 3)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Benzodiazepine; locked in secure automated dispensing cabinet",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 170,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0003",
        "vault_storage_compartment": "Safe-Alpha-Drawer-3",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-LORA-V04": {
        "vault_item_id": "SCH4-LORA-V04",
        "substance_name": "Lorazepam 1mg Tablets (Ativan) (Vault Lot 4)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Benzodiazepine; locked in secure automated dispensing cabinet",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 220,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0004",
        "vault_storage_compartment": "Safe-Alpha-Drawer-4",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-LORA-V05": {
        "vault_item_id": "SCH4-LORA-V05",
        "substance_name": "Lorazepam 1mg Tablets (Ativan) (Vault Lot 5)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Benzodiazepine; locked in secure automated dispensing cabinet",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 270,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0005",
        "vault_storage_compartment": "Safe-Alpha-Drawer-5",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-LORA-V06": {
        "vault_item_id": "SCH4-LORA-V06",
        "substance_name": "Lorazepam 1mg Tablets (Ativan) (Vault Lot 6)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Benzodiazepine; locked in secure automated dispensing cabinet",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 320,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0006",
        "vault_storage_compartment": "Safe-Alpha-Drawer-6",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-LORA-V07": {
        "vault_item_id": "SCH4-LORA-V07",
        "substance_name": "Lorazepam 1mg Tablets (Ativan) (Vault Lot 7)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Benzodiazepine; locked in secure automated dispensing cabinet",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 370,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0007",
        "vault_storage_compartment": "Safe-Alpha-Drawer-7",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-LORA-V08": {
        "vault_item_id": "SCH4-LORA-V08",
        "substance_name": "Lorazepam 1mg Tablets (Ativan) (Vault Lot 8)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Benzodiazepine; locked in secure automated dispensing cabinet",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 420,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0008",
        "vault_storage_compartment": "Safe-Alpha-Drawer-8",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-LORA-V09": {
        "vault_item_id": "SCH4-LORA-V09",
        "substance_name": "Lorazepam 1mg Tablets (Ativan) (Vault Lot 9)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Benzodiazepine; locked in secure automated dispensing cabinet",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 470,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0009",
        "vault_storage_compartment": "Safe-Alpha-Drawer-9",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-LORA-V10": {
        "vault_item_id": "SCH4-LORA-V10",
        "substance_name": "Lorazepam 1mg Tablets (Ativan) (Vault Lot 10)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Benzodiazepine; locked in secure automated dispensing cabinet",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 520,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0010",
        "vault_storage_compartment": "Safe-Alpha-Drawer-10",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-LORA-V11": {
        "vault_item_id": "SCH4-LORA-V11",
        "substance_name": "Lorazepam 1mg Tablets (Ativan) (Vault Lot 11)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Benzodiazepine; locked in secure automated dispensing cabinet",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 570,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0011",
        "vault_storage_compartment": "Safe-Alpha-Drawer-11",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-LORA-V12": {
        "vault_item_id": "SCH4-LORA-V12",
        "substance_name": "Lorazepam 1mg Tablets (Ativan) (Vault Lot 12)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Benzodiazepine; locked in secure automated dispensing cabinet",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 620,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0012",
        "vault_storage_compartment": "Safe-Alpha-Drawer-12",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-LORA-V13": {
        "vault_item_id": "SCH4-LORA-V13",
        "substance_name": "Lorazepam 1mg Tablets (Ativan) (Vault Lot 13)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Benzodiazepine; locked in secure automated dispensing cabinet",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 670,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0013",
        "vault_storage_compartment": "Safe-Alpha-Drawer-13",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-LORA-V14": {
        "vault_item_id": "SCH4-LORA-V14",
        "substance_name": "Lorazepam 1mg Tablets (Ativan) (Vault Lot 14)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Benzodiazepine; locked in secure automated dispensing cabinet",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 720,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0014",
        "vault_storage_compartment": "Safe-Alpha-Drawer-14",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ALP-V01": {
        "vault_item_id": "SCH4-ALP-V01",
        "substance_name": "Alprazolam 0.5mg Tablets (Xanax) (Vault Lot 1)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Strict 6-month / 5-refill maximum authorization limit",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 70,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0001",
        "vault_storage_compartment": "Safe-Alpha-Drawer-1",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ALP-V02": {
        "vault_item_id": "SCH4-ALP-V02",
        "substance_name": "Alprazolam 0.5mg Tablets (Xanax) (Vault Lot 2)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Strict 6-month / 5-refill maximum authorization limit",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 120,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0002",
        "vault_storage_compartment": "Safe-Alpha-Drawer-2",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ALP-V03": {
        "vault_item_id": "SCH4-ALP-V03",
        "substance_name": "Alprazolam 0.5mg Tablets (Xanax) (Vault Lot 3)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Strict 6-month / 5-refill maximum authorization limit",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 170,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0003",
        "vault_storage_compartment": "Safe-Alpha-Drawer-3",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ALP-V04": {
        "vault_item_id": "SCH4-ALP-V04",
        "substance_name": "Alprazolam 0.5mg Tablets (Xanax) (Vault Lot 4)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Strict 6-month / 5-refill maximum authorization limit",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 220,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0004",
        "vault_storage_compartment": "Safe-Alpha-Drawer-4",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ALP-V05": {
        "vault_item_id": "SCH4-ALP-V05",
        "substance_name": "Alprazolam 0.5mg Tablets (Xanax) (Vault Lot 5)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Strict 6-month / 5-refill maximum authorization limit",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 270,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0005",
        "vault_storage_compartment": "Safe-Alpha-Drawer-5",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ALP-V06": {
        "vault_item_id": "SCH4-ALP-V06",
        "substance_name": "Alprazolam 0.5mg Tablets (Xanax) (Vault Lot 6)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Strict 6-month / 5-refill maximum authorization limit",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 320,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0006",
        "vault_storage_compartment": "Safe-Alpha-Drawer-6",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ALP-V07": {
        "vault_item_id": "SCH4-ALP-V07",
        "substance_name": "Alprazolam 0.5mg Tablets (Xanax) (Vault Lot 7)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Strict 6-month / 5-refill maximum authorization limit",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 370,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0007",
        "vault_storage_compartment": "Safe-Alpha-Drawer-7",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ALP-V08": {
        "vault_item_id": "SCH4-ALP-V08",
        "substance_name": "Alprazolam 0.5mg Tablets (Xanax) (Vault Lot 8)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Strict 6-month / 5-refill maximum authorization limit",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 420,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0008",
        "vault_storage_compartment": "Safe-Alpha-Drawer-8",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ALP-V09": {
        "vault_item_id": "SCH4-ALP-V09",
        "substance_name": "Alprazolam 0.5mg Tablets (Xanax) (Vault Lot 9)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Strict 6-month / 5-refill maximum authorization limit",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 470,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0009",
        "vault_storage_compartment": "Safe-Alpha-Drawer-9",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ALP-V10": {
        "vault_item_id": "SCH4-ALP-V10",
        "substance_name": "Alprazolam 0.5mg Tablets (Xanax) (Vault Lot 10)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Strict 6-month / 5-refill maximum authorization limit",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 520,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0010",
        "vault_storage_compartment": "Safe-Alpha-Drawer-10",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ALP-V11": {
        "vault_item_id": "SCH4-ALP-V11",
        "substance_name": "Alprazolam 0.5mg Tablets (Xanax) (Vault Lot 11)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Strict 6-month / 5-refill maximum authorization limit",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 570,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0011",
        "vault_storage_compartment": "Safe-Alpha-Drawer-11",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ALP-V12": {
        "vault_item_id": "SCH4-ALP-V12",
        "substance_name": "Alprazolam 0.5mg Tablets (Xanax) (Vault Lot 12)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Strict 6-month / 5-refill maximum authorization limit",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 620,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0012",
        "vault_storage_compartment": "Safe-Alpha-Drawer-12",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ALP-V13": {
        "vault_item_id": "SCH4-ALP-V13",
        "substance_name": "Alprazolam 0.5mg Tablets (Xanax) (Vault Lot 13)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Strict 6-month / 5-refill maximum authorization limit",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 670,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0013",
        "vault_storage_compartment": "Safe-Alpha-Drawer-13",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ALP-V14": {
        "vault_item_id": "SCH4-ALP-V14",
        "substance_name": "Alprazolam 0.5mg Tablets (Xanax) (Vault Lot 14)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Strict 6-month / 5-refill maximum authorization limit",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 720,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0014",
        "vault_storage_compartment": "Safe-Alpha-Drawer-14",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ZOLP-V01": {
        "vault_item_id": "SCH4-ZOLP-V01",
        "substance_name": "Zolpidem Tartrate 10mg (Ambien) (Vault Lot 1)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Sedative-hypnotic; electronic signature mandatory upon delivery",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 70,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0001",
        "vault_storage_compartment": "Safe-Alpha-Drawer-1",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ZOLP-V02": {
        "vault_item_id": "SCH4-ZOLP-V02",
        "substance_name": "Zolpidem Tartrate 10mg (Ambien) (Vault Lot 2)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Sedative-hypnotic; electronic signature mandatory upon delivery",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 120,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0002",
        "vault_storage_compartment": "Safe-Alpha-Drawer-2",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ZOLP-V03": {
        "vault_item_id": "SCH4-ZOLP-V03",
        "substance_name": "Zolpidem Tartrate 10mg (Ambien) (Vault Lot 3)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Sedative-hypnotic; electronic signature mandatory upon delivery",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 170,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0003",
        "vault_storage_compartment": "Safe-Alpha-Drawer-3",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ZOLP-V04": {
        "vault_item_id": "SCH4-ZOLP-V04",
        "substance_name": "Zolpidem Tartrate 10mg (Ambien) (Vault Lot 4)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Sedative-hypnotic; electronic signature mandatory upon delivery",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 220,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0004",
        "vault_storage_compartment": "Safe-Alpha-Drawer-4",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ZOLP-V05": {
        "vault_item_id": "SCH4-ZOLP-V05",
        "substance_name": "Zolpidem Tartrate 10mg (Ambien) (Vault Lot 5)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Sedative-hypnotic; electronic signature mandatory upon delivery",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 270,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0005",
        "vault_storage_compartment": "Safe-Alpha-Drawer-5",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ZOLP-V06": {
        "vault_item_id": "SCH4-ZOLP-V06",
        "substance_name": "Zolpidem Tartrate 10mg (Ambien) (Vault Lot 6)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Sedative-hypnotic; electronic signature mandatory upon delivery",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 320,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0006",
        "vault_storage_compartment": "Safe-Alpha-Drawer-6",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ZOLP-V07": {
        "vault_item_id": "SCH4-ZOLP-V07",
        "substance_name": "Zolpidem Tartrate 10mg (Ambien) (Vault Lot 7)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Sedative-hypnotic; electronic signature mandatory upon delivery",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 370,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0007",
        "vault_storage_compartment": "Safe-Alpha-Drawer-7",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ZOLP-V08": {
        "vault_item_id": "SCH4-ZOLP-V08",
        "substance_name": "Zolpidem Tartrate 10mg (Ambien) (Vault Lot 8)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Sedative-hypnotic; electronic signature mandatory upon delivery",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 420,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0008",
        "vault_storage_compartment": "Safe-Alpha-Drawer-8",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ZOLP-V09": {
        "vault_item_id": "SCH4-ZOLP-V09",
        "substance_name": "Zolpidem Tartrate 10mg (Ambien) (Vault Lot 9)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Sedative-hypnotic; electronic signature mandatory upon delivery",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 470,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0009",
        "vault_storage_compartment": "Safe-Alpha-Drawer-9",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ZOLP-V10": {
        "vault_item_id": "SCH4-ZOLP-V10",
        "substance_name": "Zolpidem Tartrate 10mg (Ambien) (Vault Lot 10)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Sedative-hypnotic; electronic signature mandatory upon delivery",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 520,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0010",
        "vault_storage_compartment": "Safe-Alpha-Drawer-10",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ZOLP-V11": {
        "vault_item_id": "SCH4-ZOLP-V11",
        "substance_name": "Zolpidem Tartrate 10mg (Ambien) (Vault Lot 11)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Sedative-hypnotic; electronic signature mandatory upon delivery",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 570,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0011",
        "vault_storage_compartment": "Safe-Alpha-Drawer-11",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ZOLP-V12": {
        "vault_item_id": "SCH4-ZOLP-V12",
        "substance_name": "Zolpidem Tartrate 10mg (Ambien) (Vault Lot 12)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Sedative-hypnotic; electronic signature mandatory upon delivery",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 620,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0012",
        "vault_storage_compartment": "Safe-Alpha-Drawer-12",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ZOLP-V13": {
        "vault_item_id": "SCH4-ZOLP-V13",
        "substance_name": "Zolpidem Tartrate 10mg (Ambien) (Vault Lot 13)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Sedative-hypnotic; electronic signature mandatory upon delivery",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 670,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0013",
        "vault_storage_compartment": "Safe-Alpha-Drawer-13",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH4-ZOLP-V14": {
        "vault_item_id": "SCH4-ZOLP-V14",
        "substance_name": "Zolpidem Tartrate 10mg (Ambien) (Vault Lot 14)",
        "dea_schedule": "Schedule IV",
        "security_policy": "Sedative-hypnotic; electronic signature mandatory upon delivery",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 720,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH4-0014",
        "vault_storage_compartment": "Safe-Alpha-Drawer-14",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH5-PREG-V01": {
        "vault_item_id": "SCH5-PREG-V01",
        "substance_name": "Pregabalin 75mg Capsules (Lyrica) (Vault Lot 1)",
        "dea_schedule": "Schedule V",
        "security_policy": "Anticonvulsant / neuropathic pain; log of all refills",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 70,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH5-0001",
        "vault_storage_compartment": "Safe-Alpha-Drawer-1",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH5-PREG-V02": {
        "vault_item_id": "SCH5-PREG-V02",
        "substance_name": "Pregabalin 75mg Capsules (Lyrica) (Vault Lot 2)",
        "dea_schedule": "Schedule V",
        "security_policy": "Anticonvulsant / neuropathic pain; log of all refills",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 120,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH5-0002",
        "vault_storage_compartment": "Safe-Alpha-Drawer-2",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH5-PREG-V03": {
        "vault_item_id": "SCH5-PREG-V03",
        "substance_name": "Pregabalin 75mg Capsules (Lyrica) (Vault Lot 3)",
        "dea_schedule": "Schedule V",
        "security_policy": "Anticonvulsant / neuropathic pain; log of all refills",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 170,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH5-0003",
        "vault_storage_compartment": "Safe-Alpha-Drawer-3",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH5-PREG-V04": {
        "vault_item_id": "SCH5-PREG-V04",
        "substance_name": "Pregabalin 75mg Capsules (Lyrica) (Vault Lot 4)",
        "dea_schedule": "Schedule V",
        "security_policy": "Anticonvulsant / neuropathic pain; log of all refills",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 220,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH5-0004",
        "vault_storage_compartment": "Safe-Alpha-Drawer-4",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH5-PREG-V05": {
        "vault_item_id": "SCH5-PREG-V05",
        "substance_name": "Pregabalin 75mg Capsules (Lyrica) (Vault Lot 5)",
        "dea_schedule": "Schedule V",
        "security_policy": "Anticonvulsant / neuropathic pain; log of all refills",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 270,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH5-0005",
        "vault_storage_compartment": "Safe-Alpha-Drawer-5",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH5-PREG-V06": {
        "vault_item_id": "SCH5-PREG-V06",
        "substance_name": "Pregabalin 75mg Capsules (Lyrica) (Vault Lot 6)",
        "dea_schedule": "Schedule V",
        "security_policy": "Anticonvulsant / neuropathic pain; log of all refills",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 320,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH5-0006",
        "vault_storage_compartment": "Safe-Alpha-Drawer-6",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH5-PREG-V07": {
        "vault_item_id": "SCH5-PREG-V07",
        "substance_name": "Pregabalin 75mg Capsules (Lyrica) (Vault Lot 7)",
        "dea_schedule": "Schedule V",
        "security_policy": "Anticonvulsant / neuropathic pain; log of all refills",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 370,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH5-0007",
        "vault_storage_compartment": "Safe-Alpha-Drawer-7",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH5-PREG-V08": {
        "vault_item_id": "SCH5-PREG-V08",
        "substance_name": "Pregabalin 75mg Capsules (Lyrica) (Vault Lot 8)",
        "dea_schedule": "Schedule V",
        "security_policy": "Anticonvulsant / neuropathic pain; log of all refills",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 420,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH5-0008",
        "vault_storage_compartment": "Safe-Alpha-Drawer-8",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH5-PREG-V09": {
        "vault_item_id": "SCH5-PREG-V09",
        "substance_name": "Pregabalin 75mg Capsules (Lyrica) (Vault Lot 9)",
        "dea_schedule": "Schedule V",
        "security_policy": "Anticonvulsant / neuropathic pain; log of all refills",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 470,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH5-0009",
        "vault_storage_compartment": "Safe-Alpha-Drawer-9",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH5-PREG-V10": {
        "vault_item_id": "SCH5-PREG-V10",
        "substance_name": "Pregabalin 75mg Capsules (Lyrica) (Vault Lot 10)",
        "dea_schedule": "Schedule V",
        "security_policy": "Anticonvulsant / neuropathic pain; log of all refills",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 520,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH5-0010",
        "vault_storage_compartment": "Safe-Alpha-Drawer-10",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH5-PREG-V11": {
        "vault_item_id": "SCH5-PREG-V11",
        "substance_name": "Pregabalin 75mg Capsules (Lyrica) (Vault Lot 11)",
        "dea_schedule": "Schedule V",
        "security_policy": "Anticonvulsant / neuropathic pain; log of all refills",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 570,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH5-0011",
        "vault_storage_compartment": "Safe-Alpha-Drawer-11",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH5-PREG-V12": {
        "vault_item_id": "SCH5-PREG-V12",
        "substance_name": "Pregabalin 75mg Capsules (Lyrica) (Vault Lot 12)",
        "dea_schedule": "Schedule V",
        "security_policy": "Anticonvulsant / neuropathic pain; log of all refills",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 620,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH5-0012",
        "vault_storage_compartment": "Safe-Alpha-Drawer-12",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH5-PREG-V13": {
        "vault_item_id": "SCH5-PREG-V13",
        "substance_name": "Pregabalin 75mg Capsules (Lyrica) (Vault Lot 13)",
        "dea_schedule": "Schedule V",
        "security_policy": "Anticonvulsant / neuropathic pain; log of all refills",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 670,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH5-0013",
        "vault_storage_compartment": "Safe-Alpha-Drawer-13",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
    "SCH5-PREG-V14": {
        "vault_item_id": "SCH5-PREG-V14",
        "substance_name": "Pregabalin 75mg Capsules (Lyrica) (Vault Lot 14)",
        "dea_schedule": "Schedule V",
        "security_policy": "Anticonvulsant / neuropathic pain; log of all refills",
        "requires_dual_witness": False,
        "perpetual_inventory_balance": 720,
        "discrepancy_threshold_units": 0,
        "dea_form_222_number": "DEA222-SCH5-0014",
        "vault_storage_compartment": "Safe-Alpha-Drawer-14",
        "last_blind_count_verified_at": "2026-08-31T18:00:00Z",
    },
}
