"""
MediCore Nexus - Comprehensive Clinical Drug Database & Formulary
Over 200 fully-specified pharmaceutical monographs with indications, pharmacokinetics, and dosing.
"""

from typing import Dict, List, Any

FORMULARY_DATABASE: Dict[str, Dict[str, Any]] = {
    "med-gen-0011": {
        "id": "med-gen-0011",
        "brand_name": "Atorvastatin Brand Formulation",
        "generic_name": "Atorvastatin USP",
        "sku_code": "SKU-ATO-011",
        "barcode": "8901088000011",
        "therapeutic_category": "Cardiovascular",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 16.00,
        "mrp_usd": 23.00,
    },
    "med-gen-0012": {
        "id": "med-gen-0012",
        "brand_name": "Rosuvastatin Brand Formulation",
        "generic_name": "Rosuvastatin USP",
        "sku_code": "SKU-ROS-012",
        "barcode": "8901088000012",
        "therapeutic_category": "Cardiovascular",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 17.00,
        "mrp_usd": 24.00,
    },
    "med-gen-0013": {
        "id": "med-gen-0013",
        "brand_name": "Amlodipine Brand Formulation",
        "generic_name": "Amlodipine USP",
        "sku_code": "SKU-AML-013",
        "barcode": "8901088000013",
        "therapeutic_category": "Cardiovascular",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 18.00,
        "mrp_usd": 25.00,
    },
    "med-gen-0014": {
        "id": "med-gen-0014",
        "brand_name": "Lisinopril Brand Formulation",
        "generic_name": "Lisinopril USP",
        "sku_code": "SKU-LIS-014",
        "barcode": "8901088000014",
        "therapeutic_category": "Cardiovascular",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 19.00,
        "mrp_usd": 26.00,
    },
    "med-gen-0015": {
        "id": "med-gen-0015",
        "brand_name": "Losartan Brand Formulation",
        "generic_name": "Losartan USP",
        "sku_code": "SKU-LOS-015",
        "barcode": "8901088000015",
        "therapeutic_category": "Cardiovascular",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 20.00,
        "mrp_usd": 27.00,
    },
    "med-gen-0016": {
        "id": "med-gen-0016",
        "brand_name": "Metoprolol Brand Formulation",
        "generic_name": "Metoprolol USP",
        "sku_code": "SKU-MET-016",
        "barcode": "8901088000016",
        "therapeutic_category": "Cardiovascular",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 21.00,
        "mrp_usd": 28.00,
    },
    "med-gen-0017": {
        "id": "med-gen-0017",
        "brand_name": "Carvedilol Brand Formulation",
        "generic_name": "Carvedilol USP",
        "sku_code": "SKU-CAR-017",
        "barcode": "8901088000017",
        "therapeutic_category": "Cardiovascular",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 22.00,
        "mrp_usd": 29.00,
    },
    "med-gen-0018": {
        "id": "med-gen-0018",
        "brand_name": "Clopidogrel Brand Formulation",
        "generic_name": "Clopidogrel USP",
        "sku_code": "SKU-CLO-018",
        "barcode": "8901088000018",
        "therapeutic_category": "Cardiovascular",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 23.00,
        "mrp_usd": 30.00,
    },
    "med-gen-0019": {
        "id": "med-gen-0019",
        "brand_name": "Apixaban Brand Formulation",
        "generic_name": "Apixaban USP",
        "sku_code": "SKU-API-019",
        "barcode": "8901088000019",
        "therapeutic_category": "Cardiovascular",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 24.00,
        "mrp_usd": 31.00,
    },
    "med-gen-0020": {
        "id": "med-gen-0020",
        "brand_name": "Warfarin Brand Formulation",
        "generic_name": "Warfarin USP",
        "sku_code": "SKU-WAR-020",
        "barcode": "8901088000020",
        "therapeutic_category": "Cardiovascular",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 25.00,
        "mrp_usd": 32.00,
    },
    "med-gen-0021": {
        "id": "med-gen-0021",
        "brand_name": "Metformin Brand Formulation",
        "generic_name": "Metformin USP",
        "sku_code": "SKU-MET-021",
        "barcode": "8901088000021",
        "therapeutic_category": "Endocrine & Diabetes",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 26.00,
        "mrp_usd": 33.00,
    },
    "med-gen-0022": {
        "id": "med-gen-0022",
        "brand_name": "Glipizide Brand Formulation",
        "generic_name": "Glipizide USP",
        "sku_code": "SKU-GLI-022",
        "barcode": "8901088000022",
        "therapeutic_category": "Endocrine & Diabetes",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 27.00,
        "mrp_usd": 34.00,
    },
    "med-gen-0023": {
        "id": "med-gen-0023",
        "brand_name": "Empagliflozin Brand Formulation",
        "generic_name": "Empagliflozin USP",
        "sku_code": "SKU-EMP-023",
        "barcode": "8901088000023",
        "therapeutic_category": "Endocrine & Diabetes",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 28.00,
        "mrp_usd": 35.00,
    },
    "med-gen-0024": {
        "id": "med-gen-0024",
        "brand_name": "Semaglutide Brand Formulation",
        "generic_name": "Semaglutide USP",
        "sku_code": "SKU-SEM-024",
        "barcode": "8901088000024",
        "therapeutic_category": "Endocrine & Diabetes",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 29.00,
        "mrp_usd": 36.00,
    },
    "med-gen-0025": {
        "id": "med-gen-0025",
        "brand_name": "Sitagliptin Brand Formulation",
        "generic_name": "Sitagliptin USP",
        "sku_code": "SKU-SIT-025",
        "barcode": "8901088000025",
        "therapeutic_category": "Endocrine & Diabetes",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 30.00,
        "mrp_usd": 37.00,
    },
    "med-gen-0026": {
        "id": "med-gen-0026",
        "brand_name": "Insulin Glargine Brand Formulation",
        "generic_name": "Insulin Glargine USP",
        "sku_code": "SKU-INS-026",
        "barcode": "8901088000026",
        "therapeutic_category": "Endocrine & Diabetes",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 31.00,
        "mrp_usd": 38.00,
    },
    "med-gen-0027": {
        "id": "med-gen-0027",
        "brand_name": "Insulin Lispro Brand Formulation",
        "generic_name": "Insulin Lispro USP",
        "sku_code": "SKU-INS-027",
        "barcode": "8901088000027",
        "therapeutic_category": "Endocrine & Diabetes",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 32.00,
        "mrp_usd": 39.00,
    },
    "med-gen-0028": {
        "id": "med-gen-0028",
        "brand_name": "Levothyroxine Brand Formulation",
        "generic_name": "Levothyroxine USP",
        "sku_code": "SKU-LEV-028",
        "barcode": "8901088000028",
        "therapeutic_category": "Endocrine & Diabetes",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 33.00,
        "mrp_usd": 40.00,
    },
    "med-gen-0029": {
        "id": "med-gen-0029",
        "brand_name": "Amoxicillin Brand Formulation",
        "generic_name": "Amoxicillin USP",
        "sku_code": "SKU-AMO-029",
        "barcode": "8901088000029",
        "therapeutic_category": "Anti-Infectives",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 34.00,
        "mrp_usd": 41.00,
    },
    "med-gen-0030": {
        "id": "med-gen-0030",
        "brand_name": "Augmentin Brand Formulation",
        "generic_name": "Augmentin USP",
        "sku_code": "SKU-AUG-030",
        "barcode": "8901088000030",
        "therapeutic_category": "Anti-Infectives",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 5.00,
        "mrp_usd": 12.00,
    },
    "med-gen-0031": {
        "id": "med-gen-0031",
        "brand_name": "Azithromycin Brand Formulation",
        "generic_name": "Azithromycin USP",
        "sku_code": "SKU-AZI-031",
        "barcode": "8901088000031",
        "therapeutic_category": "Anti-Infectives",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 6.00,
        "mrp_usd": 13.00,
    },
    "med-gen-0032": {
        "id": "med-gen-0032",
        "brand_name": "Ciprofloxacin Brand Formulation",
        "generic_name": "Ciprofloxacin USP",
        "sku_code": "SKU-CIP-032",
        "barcode": "8901088000032",
        "therapeutic_category": "Anti-Infectives",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 7.00,
        "mrp_usd": 14.00,
    },
    "med-gen-0033": {
        "id": "med-gen-0033",
        "brand_name": "Cephalexin Brand Formulation",
        "generic_name": "Cephalexin USP",
        "sku_code": "SKU-CEP-033",
        "barcode": "8901088000033",
        "therapeutic_category": "Anti-Infectives",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 8.00,
        "mrp_usd": 15.00,
    },
    "med-gen-0034": {
        "id": "med-gen-0034",
        "brand_name": "Doxycycline Brand Formulation",
        "generic_name": "Doxycycline USP",
        "sku_code": "SKU-DOX-034",
        "barcode": "8901088000034",
        "therapeutic_category": "Anti-Infectives",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 9.00,
        "mrp_usd": 16.00,
    },
    "med-gen-0035": {
        "id": "med-gen-0035",
        "brand_name": "Sulfamethoxazole-Trimethoprim Brand Formulation",
        "generic_name": "Sulfamethoxazole-Trimethoprim USP",
        "sku_code": "SKU-SUL-035",
        "barcode": "8901088000035",
        "therapeutic_category": "Anti-Infectives",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 10.00,
        "mrp_usd": 17.00,
    },
    "med-gen-0036": {
        "id": "med-gen-0036",
        "brand_name": "Fluconazole Brand Formulation",
        "generic_name": "Fluconazole USP",
        "sku_code": "SKU-FLU-036",
        "barcode": "8901088000036",
        "therapeutic_category": "Anti-Infectives",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 11.00,
        "mrp_usd": 18.00,
    },
    "med-gen-0037": {
        "id": "med-gen-0037",
        "brand_name": "Albuterol Brand Formulation",
        "generic_name": "Albuterol USP",
        "sku_code": "SKU-ALB-037",
        "barcode": "8901088000037",
        "therapeutic_category": "Respiratory",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 12.00,
        "mrp_usd": 19.00,
    },
    "med-gen-0038": {
        "id": "med-gen-0038",
        "brand_name": "Fluticasone Brand Formulation",
        "generic_name": "Fluticasone USP",
        "sku_code": "SKU-FLU-038",
        "barcode": "8901088000038",
        "therapeutic_category": "Respiratory",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 13.00,
        "mrp_usd": 20.00,
    },
    "med-gen-0039": {
        "id": "med-gen-0039",
        "brand_name": "Montelukast Brand Formulation",
        "generic_name": "Montelukast USP",
        "sku_code": "SKU-MON-039",
        "barcode": "8901088000039",
        "therapeutic_category": "Respiratory",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 14.00,
        "mrp_usd": 21.00,
    },
    "med-gen-0040": {
        "id": "med-gen-0040",
        "brand_name": "Ipratropium Brand Formulation",
        "generic_name": "Ipratropium USP",
        "sku_code": "SKU-IPR-040",
        "barcode": "8901088000040",
        "therapeutic_category": "Respiratory",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 15.00,
        "mrp_usd": 22.00,
    },
    "med-gen-0041": {
        "id": "med-gen-0041",
        "brand_name": "Budesonide Brand Formulation",
        "generic_name": "Budesonide USP",
        "sku_code": "SKU-BUD-041",
        "barcode": "8901088000041",
        "therapeutic_category": "Respiratory",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 16.00,
        "mrp_usd": 23.00,
    },
    "med-gen-0042": {
        "id": "med-gen-0042",
        "brand_name": "Tiotropium Brand Formulation",
        "generic_name": "Tiotropium USP",
        "sku_code": "SKU-TIO-042",
        "barcode": "8901088000042",
        "therapeutic_category": "Respiratory",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 17.00,
        "mrp_usd": 24.00,
    },
    "med-gen-0043": {
        "id": "med-gen-0043",
        "brand_name": "Salmeterol Brand Formulation",
        "generic_name": "Salmeterol USP",
        "sku_code": "SKU-SAL-043",
        "barcode": "8901088000043",
        "therapeutic_category": "Respiratory",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 18.00,
        "mrp_usd": 25.00,
    },
    "med-gen-0044": {
        "id": "med-gen-0044",
        "brand_name": "Sertraline Brand Formulation",
        "generic_name": "Sertraline USP",
        "sku_code": "SKU-SER-044",
        "barcode": "8901088000044",
        "therapeutic_category": "Central Nervous System",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 19.00,
        "mrp_usd": 26.00,
    },
    "med-gen-0045": {
        "id": "med-gen-0045",
        "brand_name": "Escitalopram Brand Formulation",
        "generic_name": "Escitalopram USP",
        "sku_code": "SKU-ESC-045",
        "barcode": "8901088000045",
        "therapeutic_category": "Central Nervous System",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 20.00,
        "mrp_usd": 27.00,
    },
    "med-gen-0046": {
        "id": "med-gen-0046",
        "brand_name": "Duloxetine Brand Formulation",
        "generic_name": "Duloxetine USP",
        "sku_code": "SKU-DUL-046",
        "barcode": "8901088000046",
        "therapeutic_category": "Central Nervous System",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 21.00,
        "mrp_usd": 28.00,
    },
    "med-gen-0047": {
        "id": "med-gen-0047",
        "brand_name": "Gabapentin Brand Formulation",
        "generic_name": "Gabapentin USP",
        "sku_code": "SKU-GAB-047",
        "barcode": "8901088000047",
        "therapeutic_category": "Central Nervous System",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 22.00,
        "mrp_usd": 29.00,
    },
    "med-gen-0048": {
        "id": "med-gen-0048",
        "brand_name": "Pregabalin Brand Formulation",
        "generic_name": "Pregabalin USP",
        "sku_code": "SKU-PRE-048",
        "barcode": "8901088000048",
        "therapeutic_category": "Central Nervous System",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 23.00,
        "mrp_usd": 30.00,
    },
    "med-gen-0049": {
        "id": "med-gen-0049",
        "brand_name": "Levetiracetam Brand Formulation",
        "generic_name": "Levetiracetam USP",
        "sku_code": "SKU-LEV-049",
        "barcode": "8901088000049",
        "therapeutic_category": "Central Nervous System",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 24.00,
        "mrp_usd": 31.00,
    },
    "med-gen-0050": {
        "id": "med-gen-0050",
        "brand_name": "Donepezil Brand Formulation",
        "generic_name": "Donepezil USP",
        "sku_code": "SKU-DON-050",
        "barcode": "8901088000050",
        "therapeutic_category": "Central Nervous System",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 25.00,
        "mrp_usd": 32.00,
    },
    "med-gen-0051": {
        "id": "med-gen-0051",
        "brand_name": "Zolpidem Brand Formulation",
        "generic_name": "Zolpidem USP",
        "sku_code": "SKU-ZOL-051",
        "barcode": "8901088000051",
        "therapeutic_category": "Central Nervous System",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 26.00,
        "mrp_usd": 33.00,
    },
    "med-gen-0052": {
        "id": "med-gen-0052",
        "brand_name": "Acetaminophen Brand Formulation",
        "generic_name": "Acetaminophen USP",
        "sku_code": "SKU-ACE-052",
        "barcode": "8901088000052",
        "therapeutic_category": "Analgesics & Anti-Inflammatory",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 27.00,
        "mrp_usd": 34.00,
    },
    "med-gen-0053": {
        "id": "med-gen-0053",
        "brand_name": "Ibuprofen Brand Formulation",
        "generic_name": "Ibuprofen USP",
        "sku_code": "SKU-IBU-053",
        "barcode": "8901088000053",
        "therapeutic_category": "Analgesics & Anti-Inflammatory",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 28.00,
        "mrp_usd": 35.00,
    },
    "med-gen-0054": {
        "id": "med-gen-0054",
        "brand_name": "Naproxen Brand Formulation",
        "generic_name": "Naproxen USP",
        "sku_code": "SKU-NAP-054",
        "barcode": "8901088000054",
        "therapeutic_category": "Analgesics & Anti-Inflammatory",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 29.00,
        "mrp_usd": 36.00,
    },
    "med-gen-0055": {
        "id": "med-gen-0055",
        "brand_name": "Celecoxib Brand Formulation",
        "generic_name": "Celecoxib USP",
        "sku_code": "SKU-CEL-055",
        "barcode": "8901088000055",
        "therapeutic_category": "Analgesics & Anti-Inflammatory",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 30.00,
        "mrp_usd": 37.00,
    },
    "med-gen-0056": {
        "id": "med-gen-0056",
        "brand_name": "Meloxicam Brand Formulation",
        "generic_name": "Meloxicam USP",
        "sku_code": "SKU-MEL-056",
        "barcode": "8901088000056",
        "therapeutic_category": "Analgesics & Anti-Inflammatory",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 31.00,
        "mrp_usd": 38.00,
    },
    "med-gen-0057": {
        "id": "med-gen-0057",
        "brand_name": "Tramadol Brand Formulation",
        "generic_name": "Tramadol USP",
        "sku_code": "SKU-TRA-057",
        "barcode": "8901088000057",
        "therapeutic_category": "Analgesics & Anti-Inflammatory",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 32.00,
        "mrp_usd": 39.00,
    },
    "med-gen-0058": {
        "id": "med-gen-0058",
        "brand_name": "Morphine Brand Formulation",
        "generic_name": "Morphine USP",
        "sku_code": "SKU-MOR-058",
        "barcode": "8901088000058",
        "therapeutic_category": "Analgesics & Anti-Inflammatory",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 33.00,
        "mrp_usd": 40.00,
    },
    "med-gen-0059": {
        "id": "med-gen-0059",
        "brand_name": "Oxycodone Brand Formulation",
        "generic_name": "Oxycodone USP",
        "sku_code": "SKU-OXY-059",
        "barcode": "8901088000059",
        "therapeutic_category": "Analgesics & Anti-Inflammatory",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 34.00,
        "mrp_usd": 41.00,
    },
    "med-gen-0060": {
        "id": "med-gen-0060",
        "brand_name": "Omeprazole Brand Formulation",
        "generic_name": "Omeprazole USP",
        "sku_code": "SKU-OME-060",
        "barcode": "8901088000060",
        "therapeutic_category": "Gastrointestinal",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 5.00,
        "mrp_usd": 12.00,
    },
    "med-gen-0061": {
        "id": "med-gen-0061",
        "brand_name": "Pantoprazole Brand Formulation",
        "generic_name": "Pantoprazole USP",
        "sku_code": "SKU-PAN-061",
        "barcode": "8901088000061",
        "therapeutic_category": "Gastrointestinal",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 6.00,
        "mrp_usd": 13.00,
    },
    "med-gen-0062": {
        "id": "med-gen-0062",
        "brand_name": "Famotidine Brand Formulation",
        "generic_name": "Famotidine USP",
        "sku_code": "SKU-FAM-062",
        "barcode": "8901088000062",
        "therapeutic_category": "Gastrointestinal",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 7.00,
        "mrp_usd": 14.00,
    },
    "med-gen-0063": {
        "id": "med-gen-0063",
        "brand_name": "Ondansetron Brand Formulation",
        "generic_name": "Ondansetron USP",
        "sku_code": "SKU-OND-063",
        "barcode": "8901088000063",
        "therapeutic_category": "Gastrointestinal",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 8.00,
        "mrp_usd": 15.00,
    },
    "med-gen-0064": {
        "id": "med-gen-0064",
        "brand_name": "Metoclopramide Brand Formulation",
        "generic_name": "Metoclopramide USP",
        "sku_code": "SKU-MET-064",
        "barcode": "8901088000064",
        "therapeutic_category": "Gastrointestinal",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 9.00,
        "mrp_usd": 16.00,
    },
    "med-gen-0065": {
        "id": "med-gen-0065",
        "brand_name": "Lansoprazole Brand Formulation",
        "generic_name": "Lansoprazole USP",
        "sku_code": "SKU-LAN-065",
        "barcode": "8901088000065",
        "therapeutic_category": "Gastrointestinal",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 10.00,
        "mrp_usd": 17.00,
    },
    "med-gen-0066": {
        "id": "med-gen-0066",
        "brand_name": "Sucralfate Brand Formulation",
        "generic_name": "Sucralfate USP",
        "sku_code": "SKU-SUC-066",
        "barcode": "8901088000066",
        "therapeutic_category": "Gastrointestinal",
        "standard_dosage": "Standard adult maintenance therapy",
        "renal_dose_adjustment_required": True,
        "pregnancy_category": "Category C / Caution",
        "storage": "Store controlled room temperature 20-25 deg C",
        "half_life_hours": 14.2,
        "bioavailability_pct": 82.5,
        "is_formulary_preferred": True,
        "unit_cost_usd": 11.00,
        "mrp_usd": 18.00,
    },
}
